(define (problem mprime-x-6)
   (:domain mystery-prime-typed)
   (:objects okra pork lamb wurst shrimp muffin broccoli potato - food
             curiosity achievement satisfaction - pleasure
             grief loneliness dread jealousy sciatica hangover-12 depression-13 - pain
)
   (:init
(= (locale okra) 8)
(= (locale pork) 9)
(= (locale lamb) 3)
(= (locale wurst) 0)
(= (locale shrimp) 0)
(= (locale muffin) 2)
(= (locale broccoli) 8)
(= (locale potato) 2)
(= (harmony curiosity) 3)
(= (harmony achievement) 1)
(= (harmony satisfaction) 1)
(eats okra potato)
(eats okra pork)
(eats okra okra)
(eats pork lamb)
(eats lamb potato)
(eats wurst muffin)
(eats wurst pork)
(eats shrimp okra)
(eats muffin pork)
(eats broccoli pork)
(eats potato potato)
(eats potato lamb)
(eats potato wurst)
(craves achievement potato)
(craves curiosity broccoli)
(craves curiosity lamb)
(craves curiosity shrimp)
(craves depression-13 lamb)
(craves dread potato)
(craves grief potato)
(craves hangover-12 potato)
(craves jealousy lamb)
(craves loneliness broccoli)
(craves satisfaction lamb)
(craves satisfaction okra)
(craves satisfaction pork)
(craves sciatica muffin))
   (:goal (and (craves depression-13 shrimp) (craves jealousy pork))))
