(define (problem mprime-x-7)
   (:domain mystery-prime-typed)
   (:objects tofu orange cherry chicken apple pepper bacon turkey - food
             satisfaction entertainment rest-6 satiety-7 - pleasure
             hangover depression abrasion anxiety anger angina boils grief loneliness dread jealousy sciatica hangover-12 - pain
)
   (:init
(= (locale tofu) 9)
(= (locale orange) 8)
(= (locale cherry) 1)
(= (locale chicken) 8)
(= (locale apple) 6)
(= (locale pepper) 9)
(= (locale bacon) 3)
(= (locale turkey) 7)
(= (harmony satisfaction) 1)
(= (harmony entertainment) 1)
(= (harmony rest-6) 1)
(= (harmony satiety-7) 1)
(eats tofu cherry)
(eats tofu pepper)
(eats orange orange)
(eats cherry apple)
(eats cherry turkey)
(eats chicken cherry)
(eats apple pepper)
(eats pepper cherry)
(eats bacon chicken)
(eats bacon bacon)
(eats bacon pepper)
(eats turkey cherry)
(craves abrasion cherry)
(craves anger chicken)
(craves anger tofu)
(craves angina apple)
(craves angina cherry)
(craves anxiety turkey)
(craves boils orange)
(craves depression bacon)
(craves depression turkey)
(craves dread chicken)
(craves entertainment chicken)
(craves entertainment turkey)
(craves grief orange)
(craves hangover pepper)
(craves hangover turkey)
(craves hangover-12 chicken)
(craves jealousy pepper)
(craves jealousy tofu)
(craves loneliness tofu)
(craves rest-6 bacon)
(craves rest-6 cherry)
(craves rest-6 tofu)
(craves satiety-7 apple)
(craves satiety-7 cherry)
(craves satiety-7 turkey)
(craves satisfaction orange)
(craves satisfaction pepper)
(craves satisfaction turkey)
(craves sciatica orange)
(craves sciatica turkey))
   (:goal (and (craves jealousy cherry) (craves anxiety apple) (craves depression pepper))))
