(define (problem mprime-x-3)
   (:domain mystery-prime-typed)
   (:objects shrimp muffin broccoli potato lettuce melon tofu orange - food
             rest satiety curiosity - pleasure
             anxiety anger angina boils grief loneliness dread jealousy sciatica hangover-12 - pain
)
   (:init
(= (locale shrimp) 8)
(= (locale muffin) 2)
(= (locale broccoli) 5)
(= (locale potato) 6)
(= (locale lettuce) 9)
(= (locale melon) 0)
(= (locale tofu) 1)
(= (locale orange) 6)
(= (harmony rest) 1)
(= (harmony satiety) 2)
(= (harmony curiosity) 3)
(eats shrimp muffin)
(eats muffin potato)
(eats muffin tofu)
(eats broccoli shrimp)
(eats broccoli orange)
(eats broccoli melon)
(eats potato shrimp)
(eats potato tofu)
(eats lettuce broccoli)
(eats melon broccoli)
(eats melon tofu)
(eats melon lettuce)
(eats tofu broccoli)
(eats tofu tofu)
(eats tofu muffin)
(eats orange muffin)
(eats orange orange)
(eats orange lettuce)
(craves anger broccoli)
(craves angina muffin)
(craves anxiety potato)
(craves boils melon)
(craves boils shrimp)
(craves curiosity broccoli)
(craves curiosity shrimp)
(craves curiosity tofu)
(craves dread tofu)
(craves grief shrimp)
(craves hangover-12 lettuce)
(craves jealousy melon)
(craves loneliness orange)
(craves rest lettuce)
(craves rest potato)
(craves rest shrimp)
(craves satiety muffin)
(craves satiety tofu)
(craves sciatica lettuce)
(craves sciatica tofu))
   (:goal (and (craves hangover-12 shrimp) (craves grief tofu))))
