(define (problem mprime-x-8)
   (:domain mystery-prime-typed)
   (:objects broccoli potato lettuce melon tofu orange cherry chicken apple - food
             achievement satisfaction entertainment rest-6 - pleasure
             sciatica hangover-12 depression-13 abrasion-14 anxiety-15 anger-16 angina-17 boils-18 grief-19 loneliness-20 dread-21 jealousy-22 - pain
)
   (:init
(= (locale broccoli) 0)
(= (locale potato) 0)
(= (locale lettuce) 9)
(= (locale melon) 8)
(= (locale tofu) 7)
(= (locale orange) 3)
(= (locale cherry) 9)
(= (locale chicken) 4)
(= (locale apple) 3)
(= (harmony achievement) 2)
(= (harmony satisfaction) 1)
(= (harmony entertainment) 1)
(= (harmony rest-6) 1)
(eats broccoli chicken)
(eats potato apple)
(eats potato cherry)
(eats potato broccoli)
(eats lettuce apple)
(eats lettuce lettuce)
(eats melon potato)
(eats tofu cherry)
(eats tofu orange)
(eats orange apple)
(eats orange potato)
(eats cherry melon)
(eats cherry broccoli)
(eats cherry cherry)
(eats chicken lettuce)
(eats chicken potato)
(eats apple orange)
(craves abrasion-14 potato)
(craves achievement chicken)
(craves achievement tofu)
(craves anger-16 apple)
(craves angina-17 chicken)
(craves anxiety-15 potato)
(craves boils-18 potato)
(craves depression-13 orange)
(craves depression-13 tofu)
(craves dread-21 broccoli)
(craves dread-21 potato)
(craves entertainment potato)
(craves grief-19 cherry)
(craves grief-19 lettuce)
(craves hangover-12 orange)
(craves jealousy-22 orange)
(craves jealousy-22 potato)
(craves loneliness-20 tofu)
(craves rest-6 apple)
(craves rest-6 chicken)
(craves rest-6 tofu)
(craves satisfaction apple)
(craves satisfaction melon)
(craves satisfaction potato)
(craves sciatica broccoli))
   (:goal (and (craves jealousy-22 apple) (craves angina-17 tofu) (craves loneliness-20 chicken))))
