(define (problem mprime-x-1)
   (:domain mystery-prime-typed)
   (:objects pear flounder okra pork lamb wurst shrimp muffin broccoli potato lettuce - food
             rest satiety curiosity achievement - pleasure
             jealousy sciatica hangover-12 depression-13 abrasion-14 anxiety-15 anger-16 angina-17 boils-18 grief-19 loneliness-20 - pain
)
   (:init
(= (locale pear) 4)
(= (locale flounder) 2)
(= (locale okra) 8)
(= (locale pork) 3)
(= (locale lamb) 2)
(= (locale wurst) 1)
(= (locale shrimp) 6)
(= (locale muffin) 1)
(= (locale broccoli) 2)
(= (locale potato) 1)
(= (locale lettuce) 9)
(= (harmony rest) 1)
(= (harmony satiety) 1)
(= (harmony curiosity) 1)
(= (harmony achievement) 1)
(eats pear pear)
(eats flounder shrimp)
(eats flounder muffin)
(eats flounder pork)
(eats okra lettuce)
(eats pork muffin)
(eats pork lettuce)
(eats pork flounder)
(eats lamb lamb)
(eats lamb broccoli)
(eats lamb pear)
(eats wurst pork)
(eats wurst potato)
(eats wurst broccoli)
(eats shrimp lettuce)
(eats shrimp flounder)
(eats muffin lamb)
(eats muffin flounder)
(eats muffin broccoli)
(eats broccoli lamb)
(eats potato broccoli)
(eats potato muffin)
(eats lettuce wurst)
(eats lettuce okra)
(craves abrasion-14 lamb)
(craves abrasion-14 potato)
(craves achievement flounder)
(craves achievement muffin)
(craves anger-16 broccoli)
(craves angina-17 muffin)
(craves anxiety-15 okra)
(craves boils-18 okra)
(craves boils-18 potato)
(craves curiosity shrimp)
(craves curiosity wurst)
(craves depression-13 shrimp)
(craves grief-19 pear)
(craves grief-19 shrimp)
(craves hangover-12 muffin)
(craves hangover-12 pork)
(craves jealousy flounder)
(craves jealousy potato)
(craves loneliness-20 flounder)
(craves loneliness-20 potato)
(craves rest broccoli)
(craves rest okra)
(craves rest shrimp)
(craves satiety lamb)
(craves satiety pork)
(craves satiety wurst)
(craves sciatica wurst))
   (:goal (and (craves sciatica lamb) (craves boils-18 broccoli))))
