(define (problem mprime-x-5)
   (:domain mystery-prime-typed)
   (:objects lettuce melon tofu orange cherry chicken apple pepper bacon - food
             satiety curiosity achievement satisfaction - pleasure
             dread jealousy sciatica hangover-12 depression-13 abrasion-14 anxiety-15 anger-16 angina-17 boils-18 grief-19 loneliness-20 - pain
)
   (:init
(= (locale lettuce) 2)
(= (locale melon) 0)
(= (locale tofu) 9)
(= (locale orange) 4)
(= (locale cherry) 8)
(= (locale chicken) 9)
(= (locale apple) 0)
(= (locale pepper) 0)
(= (locale bacon) 1)
(= (harmony satiety) 2)
(= (harmony curiosity) 3)
(= (harmony achievement) 2)
(= (harmony satisfaction) 1)
(eats lettuce chicken)
(eats lettuce pepper)
(eats melon melon)
(eats melon cherry)
(eats melon orange)
(eats tofu pepper)
(eats tofu melon)
(eats orange apple)
(eats orange tofu)
(eats cherry melon)
(eats cherry lettuce)
(eats chicken cherry)
(eats apple bacon)
(eats apple pepper)
(eats pepper orange)
(eats pepper tofu)
(eats pepper melon)
(eats bacon melon)
(craves abrasion-14 bacon)
(craves achievement bacon)
(craves achievement cherry)
(craves achievement tofu)
(craves anger-16 bacon)
(craves anger-16 lettuce)
(craves angina-17 melon)
(craves angina-17 pepper)
(craves anxiety-15 pepper)
(craves anxiety-15 tofu)
(craves boils-18 bacon)
(craves boils-18 orange)
(craves curiosity cherry)
(craves depression-13 melon)
(craves dread chicken)
(craves dread pepper)
(craves grief-19 pepper)
(craves hangover-12 apple)
(craves jealousy apple)
(craves jealousy bacon)
(craves loneliness-20 bacon)
(craves satiety bacon)
(craves satiety chicken)
(craves satiety tofu)
(craves satisfaction lettuce)
(craves sciatica bacon)
(craves sciatica lettuce))
   (:goal (and (craves abrasion-14 tofu) (craves sciatica tofu))))
