(define (problem mprime-x-9)
   (:domain mystery-prime-typed)
   (:objects apple pepper bacon turkey papaya rice-22 pear-23 flounder-24 okra-25 - food
             rest satiety - pleasure
             loneliness dread jealousy sciatica hangover-12 depression-13 abrasion-14 anxiety-15 anger-16 angina-17 boils-18 grief-19 - pain
)
   (:init
(= (locale apple) 5)
(= (locale pepper) 1)
(= (locale bacon) 6)
(= (locale turkey) 7)
(= (locale papaya) 9)
(= (locale rice-22) 6)
(= (locale pear-23) 3)
(= (locale flounder-24) 0)
(= (locale okra-25) 0)
(= (harmony rest) 3)
(= (harmony satiety) 1)
(eats apple apple)
(eats apple rice-22)
(eats pepper rice-22)
(eats pepper papaya)
(eats bacon turkey)
(eats turkey rice-22)
(eats turkey okra-25)
(eats papaya pepper)
(eats papaya okra-25)
(eats papaya rice-22)
(eats rice-22 okra-25)
(eats rice-22 flounder-24)
(eats rice-22 apple)
(eats pear-23 bacon)
(eats pear-23 okra-25)
(eats pear-23 rice-22)
(eats flounder-24 pepper)
(eats flounder-24 okra-25)
(eats flounder-24 pear-23)
(eats okra-25 pepper)
(craves abrasion-14 flounder-24)
(craves abrasion-14 papaya)
(craves anger-16 flounder-24)
(craves anger-16 rice-22)
(craves angina-17 turkey)
(craves anxiety-15 bacon)
(craves anxiety-15 okra-25)
(craves boils-18 pear-23)
(craves depression-13 apple)
(craves dread turkey)
(craves grief-19 bacon)
(craves grief-19 okra-25)
(craves hangover-12 apple)
(craves hangover-12 okra-25)
(craves jealousy flounder-24)
(craves jealousy pear-23)
(craves loneliness pepper)
(craves rest apple)
(craves rest okra-25)
(craves rest pear-23)
(craves satiety okra-25)
(craves satiety rice-22)
(craves sciatica rice-22))
   (:goal (and (craves jealousy apple))))
