(define (problem mprime-x-2)
   (:domain mystery-prime-typed)
   (:objects apple pepper bacon turkey papaya rice-22 pear-23 flounder-24 okra-25 - food
             entertainment rest-6 satiety-7 curiosity-8 - pleasure
             anger angina boils grief loneliness dread jealousy sciatica hangover-12 depression-13 - pain
)
   (:init
(= (locale apple) 2)
(= (locale pepper) 7)
(= (locale bacon) 8)
(= (locale turkey) 0)
(= (locale papaya) 5)
(= (locale rice-22) 1)
(= (locale pear-23) 9)
(= (locale flounder-24) 8)
(= (locale okra-25) 5)
(= (harmony entertainment) 1)
(= (harmony rest-6) 2)
(= (harmony satiety-7) 1)
(= (harmony curiosity-8) 3)
(eats apple rice-22)
(eats apple pear-23)
(eats apple turkey)
(eats pepper rice-22)
(eats pepper apple)
(eats pepper okra-25)
(eats bacon bacon)
(eats turkey turkey)
(eats turkey okra-25)
(eats papaya pepper)
(eats papaya bacon)
(eats papaya rice-22)
(eats rice-22 papaya)
(eats rice-22 turkey)
(eats pear-23 papaya)
(eats pear-23 pepper)
(eats flounder-24 rice-22)
(eats flounder-24 apple)
(eats okra-25 bacon)
(eats okra-25 okra-25)
(craves anger rice-22)
(craves angina pepper)
(craves angina turkey)
(craves boils apple)
(craves curiosity-8 bacon)
(craves curiosity-8 flounder-24)
(craves curiosity-8 pepper)
(craves depression-13 bacon)
(craves depression-13 turkey)
(craves dread pepper)
(craves entertainment okra-25)
(craves entertainment rice-22)
(craves entertainment turkey)
(craves grief papaya)
(craves hangover-12 papaya)
(craves jealousy pepper)
(craves jealousy rice-22)
(craves loneliness apple)
(craves rest-6 apple)
(craves rest-6 papaya)
(craves rest-6 pear-23)
(craves satiety-7 bacon)
(craves satiety-7 flounder-24)
(craves sciatica rice-22)
(craves sciatica turkey))
   (:goal (and (craves boils papaya) (craves anger okra-25) (craves jealousy bacon))))
