(define (problem mprime-x-4)
   (:domain mystery-prime-typed)
   (:objects chicken apple pepper bacon turkey papaya rice-22 pear-23 flounder-24 - food
             achievement satisfaction - pleasure
             dread jealousy sciatica hangover-12 depression-13 abrasion-14 anxiety-15 anger-16 angina-17 - pain
)
   (:init
(= (locale chicken) 7)
(= (locale apple) 3)
(= (locale pepper) 3)
(= (locale bacon) 1)
(= (locale turkey) 7)
(= (locale papaya) 9)
(= (locale rice-22) 6)
(= (locale pear-23) 5)
(= (locale flounder-24) 6)
(= (harmony achievement) 3)
(= (harmony satisfaction) 1)
(eats chicken turkey)
(eats chicken pepper)
(eats apple pear-23)
(eats apple rice-22)
(eats apple flounder-24)
(eats pepper rice-22)
(eats bacon bacon)
(eats bacon pepper)
(eats bacon chicken)
(eats turkey turkey)
(eats turkey pear-23)
(eats turkey bacon)
(eats papaya papaya)
(eats papaya pear-23)
(eats rice-22 apple)
(eats rice-22 pear-23)
(eats pear-23 apple)
(eats pear-23 rice-22)
(eats flounder-24 chicken)
(eats flounder-24 pear-23)
(craves abrasion-14 chicken)
(craves abrasion-14 pear-23)
(craves achievement papaya)
(craves anger-16 bacon)
(craves anger-16 papaya)
(craves angina-17 flounder-24)
(craves anxiety-15 flounder-24)
(craves anxiety-15 pear-23)
(craves depression-13 pepper)
(craves depression-13 rice-22)
(craves dread chicken)
(craves dread flounder-24)
(craves hangover-12 papaya)
(craves hangover-12 rice-22)
(craves jealousy chicken)
(craves satisfaction apple)
(craves satisfaction bacon)
(craves satisfaction flounder-24)
(craves sciatica flounder-24)
(craves sciatica pear-23))
   (:goal (and (craves anxiety-15 bacon))))
