(define (problem mprime-x-1)
   (:domain mystery-prime-typed)
   (:objects bacon turkey papaya rice-22 pear-23 flounder-24 okra-25 pork-26 - food
             achievement satisfaction entertainment - pleasure
             sciatica hangover-12 - pain
)
   (:init
(= (locale bacon) 7)
(= (locale turkey) 8)
(= (locale papaya) 5)
(= (locale rice-22) 0)
(= (locale pear-23) 8)
(= (locale flounder-24) 4)
(= (locale okra-25) 1)
(= (locale pork-26) 3)
(= (harmony achievement) 1)
(= (harmony satisfaction) 3)
(= (harmony entertainment) 1)
(eats bacon bacon)
(eats turkey pear-23)
(eats papaya papaya)
(eats rice-22 papaya)
(eats rice-22 bacon)
(eats pear-23 flounder-24)
(eats pear-23 pork-26)
(eats flounder-24 papaya)
(eats okra-25 pear-23)
(eats pork-26 okra-25)
(eats pork-26 flounder-24)
(eats pork-26 bacon)
(craves achievement pear-23)
(craves achievement rice-22)
(craves satisfaction flounder-24)
(craves entertainment flounder-24)
(craves sciatica pear-23)
(craves sciatica okra-25)
(craves hangover-12 bacon))
   (:goal (and (craves satisfaction flounder-24))))
