(define (problem mprime-x-3)
   (:domain mystery-prime-typed)
   (:objects bacon turkey papaya rice-22 pear-23 flounder-24 okra-25 pork-26 lamb-27 wurst-28 - food
             entertainment rest-6 satiety-7 curiosity-8 achievement-9 - pleasure
             abrasion anxiety anger angina boils - pain
)
   (:init
(= (locale bacon) 5)
(= (locale turkey) 9)
(= (locale papaya) 3)
(= (locale rice-22) 0)
(= (locale pear-23) 5)
(= (locale flounder-24) 4)
(= (locale okra-25) 4)
(= (locale pork-26) 8)
(= (locale lamb-27) 5)
(= (locale wurst-28) 4)
(= (harmony entertainment) 2)
(= (harmony rest-6) 1)
(= (harmony satiety-7) 2)
(= (harmony curiosity-8) 3)
(= (harmony achievement-9) 2)
(eats bacon wurst-28)
(eats bacon okra-25)
(eats bacon flounder-24)
(eats turkey pear-23)
(eats turkey papaya)
(eats papaya wurst-28)
(eats rice-22 lamb-27)
(eats rice-22 wurst-28)
(eats rice-22 pear-23)
(eats pear-23 lamb-27)
(eats pear-23 okra-25)
(eats flounder-24 papaya)
(eats flounder-24 turkey)
(eats okra-25 lamb-27)
(eats okra-25 pork-26)
(eats pork-26 lamb-27)
(eats pork-26 pork-26)
(eats pork-26 papaya)
(eats lamb-27 bacon)
(eats wurst-28 flounder-24)
(eats wurst-28 bacon)
(eats wurst-28 wurst-28)
(craves entertainment bacon)
(craves rest-6 wurst-28)
(craves rest-6 pork-26)
(craves satiety-7 okra-25)
(craves satiety-7 pork-26)
(craves curiosity-8 bacon)
(craves curiosity-8 okra-25)
(craves achievement-9 okra-25)
(craves abrasion bacon)
(craves abrasion rice-22)
(craves anxiety flounder-24)
(craves anxiety papaya)
(craves anger flounder-24)
(craves anger papaya)
(craves angina flounder-24)
(craves boils flounder-24))
   (:goal (and (craves entertainment bacon) (craves curiosity-8 okra-25))))
