(define (problem mprime-x-2)
   (:domain mystery-prime-typed)
   (:objects broccoli potato lettuce melon tofu orange cherry chicken apple - food
             entertainment rest-6 satiety-7 curiosity-8 - pleasure
             angina boils grief loneliness dread jealousy sciatica hangover-12 depression-13 - pain
)
   (:init
(= (locale broccoli) 2)
(= (locale potato) 1)
(= (locale lettuce) 9)
(= (locale melon) 4)
(= (locale tofu) 2)
(= (locale orange) 9)
(= (locale cherry) 2)
(= (locale chicken) 9)
(= (locale apple) 9)
(= (harmony entertainment) 2)
(= (harmony rest-6) 2)
(= (harmony satiety-7) 3)
(= (harmony curiosity-8) 3)
(eats broccoli lettuce)
(eats broccoli cherry)
(eats potato melon)
(eats lettuce lettuce)
(eats melon melon)
(eats melon broccoli)
(eats tofu potato)
(eats tofu lettuce)
(eats tofu melon)
(eats orange broccoli)
(eats orange chicken)
(eats orange apple)
(eats cherry lettuce)
(eats cherry potato)
(eats chicken broccoli)
(eats apple cherry)
(eats apple chicken)
(eats apple melon)
(craves entertainment cherry)
(craves entertainment melon)
(craves rest-6 chicken)
(craves rest-6 lettuce)
(craves satiety-7 lettuce)
(craves satiety-7 potato)
(craves curiosity-8 orange)
(craves angina tofu)
(craves angina broccoli)
(craves boils orange)
(craves grief cherry)
(craves grief potato)
(craves loneliness apple)
(craves loneliness melon)
(craves dread cherry)
(craves dread lettuce)
(craves jealousy tofu)
(craves sciatica orange)
(craves hangover-12 broccoli)
(craves depression-13 orange)
(craves depression-13 broccoli))
   (:goal (and (craves grief potato) (craves sciatica orange) (craves hangover-12 broccoli))))
