(define (problem mprime-x-7)
   (:domain mystery-prime-typed)
   (:objects muffin broccoli potato lettuce melon tofu orange cherry - food
             entertainment rest-6 satiety-7 curiosity-8 achievement-9 - pleasure
             anger angina boils grief - pain
)
   (:init
(= (locale muffin) 0)
(= (locale broccoli) 2)
(= (locale potato) 9)
(= (locale lettuce) 8)
(= (locale melon) 6)
(= (locale tofu) 3)
(= (locale orange) 2)
(= (locale cherry) 1)
(= (harmony entertainment) 2)
(= (harmony rest-6) 2)
(= (harmony satiety-7) 2)
(= (harmony curiosity-8) 1)
(= (harmony achievement-9) 3)
(eats muffin melon)
(eats muffin cherry)
(eats muffin potato)
(eats broccoli lettuce)
(eats broccoli tofu)
(eats potato potato)
(eats lettuce muffin)
(eats lettuce melon)
(eats lettuce orange)
(eats melon muffin)
(eats melon melon)
(eats tofu lettuce)
(eats tofu muffin)
(eats orange orange)
(eats orange potato)
(eats orange broccoli)
(eats cherry tofu)
(craves entertainment muffin)
(craves rest-6 muffin)
(craves rest-6 broccoli)
(craves satiety-7 lettuce)
(craves curiosity-8 potato)
(craves curiosity-8 lettuce)
(craves achievement-9 broccoli)
(craves achievement-9 lettuce)
(craves anger cherry)
(craves angina tofu)
(craves angina cherry)
(craves boils lettuce)
(craves grief lettuce)
(craves grief potato))
   (:goal (and (craves rest-6 broccoli) (craves achievement-9 lettuce) (craves rest-6 muffin))))
