(define (problem mprime-x-6)
   (:domain mystery-prime-typed)
   (:objects pepper bacon turkey papaya rice-22 pear-23 flounder-24 okra-25 - food
             satiety curiosity achievement - pleasure
             anxiety anger angina boils grief loneliness - pain
)
   (:init
(= (locale pepper) 6)
(= (locale bacon) 2)
(= (locale turkey) 4)
(= (locale papaya) 6)
(= (locale rice-22) 7)
(= (locale pear-23) 0)
(= (locale flounder-24) 0)
(= (locale okra-25) 8)
(= (harmony satiety) 2)
(= (harmony curiosity) 3)
(= (harmony achievement) 2)
(eats pepper rice-22)
(eats pepper okra-25)
(eats bacon pepper)
(eats bacon turkey)
(eats bacon bacon)
(eats turkey rice-22)
(eats turkey okra-25)
(eats turkey papaya)
(eats papaya bacon)
(eats papaya pear-23)
(eats papaya pepper)
(eats rice-22 papaya)
(eats rice-22 bacon)
(eats rice-22 turkey)
(eats pear-23 pepper)
(eats pear-23 rice-22)
(eats flounder-24 bacon)
(eats flounder-24 okra-25)
(eats flounder-24 pear-23)
(eats okra-25 pepper)
(eats okra-25 rice-22)
(eats okra-25 papaya)
(craves satiety flounder-24)
(craves satiety turkey)
(craves curiosity bacon)
(craves achievement flounder-24)
(craves achievement okra-25)
(craves anxiety flounder-24)
(craves anger bacon)
(craves anger pepper)
(craves angina flounder-24)
(craves angina okra-25)
(craves boils pepper)
(craves grief bacon)
(craves loneliness pear-23)
(craves loneliness turkey))
   (:goal (and (craves anger bacon))))
