(define (problem mprime-x-9)
   (:domain mystery-prime-typed)
   (:objects lettuce melon tofu orange cherry chicken apple pepper bacon - food
             rest satiety curiosity - pleasure
             depression abrasion anxiety anger - pain
)
   (:init
(= (locale lettuce) 0)
(= (locale melon) 2)
(= (locale tofu) 9)
(= (locale orange) 4)
(= (locale cherry) 4)
(= (locale chicken) 3)
(= (locale apple) 1)
(= (locale pepper) 0)
(= (locale bacon) 6)
(= (harmony rest) 2)
(= (harmony satiety) 3)
(= (harmony curiosity) 2)
(eats lettuce tofu)
(eats lettuce chicken)
(eats lettuce orange)
(eats melon tofu)
(eats tofu chicken)
(eats tofu orange)
(eats orange lettuce)
(eats cherry tofu)
(eats cherry apple)
(eats chicken apple)
(eats chicken tofu)
(eats chicken pepper)
(eats apple orange)
(eats apple bacon)
(eats apple cherry)
(eats pepper bacon)
(eats pepper pepper)
(eats pepper lettuce)
(eats bacon lettuce)
(eats bacon bacon)
(craves rest tofu)
(craves satiety orange)
(craves curiosity melon)
(craves depression tofu)
(craves abrasion lettuce)
(craves abrasion cherry)
(craves anxiety pepper)
(craves anxiety apple)
(craves anger pepper)
(craves anger orange))
   (:goal (and (craves rest tofu))))
