(define (problem mprime-x-5)
   (:domain mystery-prime-typed)
   (:objects flounder okra pork lamb wurst shrimp muffin broccoli potato lettuce - food
             rest satiety curiosity - pleasure
             hangover depression abrasion - pain
)
   (:init
(= (locale flounder) 4)
(= (locale okra) 5)
(= (locale pork) 8)
(= (locale lamb) 1)
(= (locale wurst) 3)
(= (locale shrimp) 1)
(= (locale muffin) 0)
(= (locale broccoli) 2)
(= (locale potato) 8)
(= (locale lettuce) 8)
(= (harmony rest) 3)
(= (harmony satiety) 3)
(= (harmony curiosity) 1)
(eats flounder muffin)
(eats okra lettuce)
(eats okra shrimp)
(eats okra okra)
(eats pork wurst)
(eats pork potato)
(eats lamb flounder)
(eats lamb muffin)
(eats wurst wurst)
(eats shrimp broccoli)
(eats shrimp wurst)
(eats shrimp pork)
(eats muffin flounder)
(eats muffin broccoli)
(eats broccoli lamb)
(eats broccoli okra)
(eats potato lamb)
(eats potato wurst)
(eats lettuce broccoli)
(craves rest flounder)
(craves satiety muffin)
(craves satiety broccoli)
(craves curiosity lettuce)
(craves hangover okra)
(craves hangover wurst)
(craves depression flounder)
(craves depression okra)
(craves abrasion muffin))
   (:goal (and (craves satiety broccoli) (craves rest flounder))))
