(define (problem mprime-x-10)
   (:domain mystery-prime-typed)
   (:objects cherry chicken apple pepper bacon turkey papaya rice-22 - food
             entertainment rest-6 satiety-7 - pleasure
             anxiety anger angina boils grief loneliness dread jealousy sciatica - pain
)
   (:init
(= (locale cherry) 1)
(= (locale chicken) 0)
(= (locale apple) 9)
(= (locale pepper) 4)
(= (locale bacon) 6)
(= (locale turkey) 7)
(= (locale papaya) 4)
(= (locale rice-22) 5)
(= (harmony entertainment) 2)
(= (harmony rest-6) 3)
(= (harmony satiety-7) 1)
(eats cherry apple)
(eats cherry papaya)
(eats cherry rice-22)
(eats chicken rice-22)
(eats chicken papaya)
(eats chicken pepper)
(eats apple apple)
(eats apple pepper)
(eats apple chicken)
(eats pepper cherry)
(eats bacon chicken)
(eats bacon pepper)
(eats bacon cherry)
(eats turkey bacon)
(eats turkey apple)
(eats papaya chicken)
(eats papaya apple)
(eats rice-22 rice-22)
(eats rice-22 turkey)
(craves entertainment pepper)
(craves rest-6 cherry)
(craves satiety-7 bacon)
(craves anxiety rice-22)
(craves anger rice-22)
(craves angina pepper)
(craves boils turkey)
(craves boils cherry)
(craves grief pepper)
(craves grief rice-22)
(craves loneliness cherry)
(craves dread pepper)
(craves jealousy rice-22)
(craves jealousy turkey)
(craves sciatica cherry)
(craves sciatica chicken))
   (:goal (and (craves jealousy rice-22) (craves jealousy turkey))))
