(define (problem mprime-x-8)
   (:domain mystery-prime-typed)
   (:objects wurst shrimp muffin broccoli potato lettuce melon tofu - food
             entertainment rest-6 satiety-7 - pleasure
             depression abrasion anxiety anger angina boils - pain
)
   (:init
(= (locale wurst) 3)
(= (locale shrimp) 4)
(= (locale muffin) 1)
(= (locale broccoli) 4)
(= (locale potato) 8)
(= (locale lettuce) 8)
(= (locale melon) 0)
(= (locale tofu) 0)
(= (harmony entertainment) 2)
(= (harmony rest-6) 2)
(= (harmony satiety-7) 3)
(eats wurst potato)
(eats wurst lettuce)
(eats shrimp muffin)
(eats muffin shrimp)
(eats broccoli wurst)
(eats broccoli muffin)
(eats broccoli shrimp)
(eats potato potato)
(eats lettuce wurst)
(eats lettuce melon)
(eats melon muffin)
(eats melon broccoli)
(eats tofu wurst)
(eats tofu tofu)
(craves entertainment muffin)
(craves rest-6 wurst)
(craves satiety-7 muffin)
(craves depression broccoli)
(craves depression lettuce)
(craves abrasion shrimp)
(craves abrasion melon)
(craves anxiety muffin)
(craves anxiety broccoli)
(craves anger broccoli)
(craves anger muffin)
(craves angina lettuce)
(craves boils tofu)
(craves boils lettuce))
   (:goal (and (craves angina lettuce) (craves entertainment muffin))))
