(define (problem mprime-x-12)
   (:domain mystery-prime-typed)
   (:objects orange cherry chicken apple pepper bacon turkey papaya rice-22 pear-23 flounder-24 okra-25 pork-26 lamb-27 wurst-28 shrimp-29 - food
             rest satiety curiosity achievement satisfaction - pleasure
             hangover depression abrasion anxiety anger angina boils grief loneliness dread jealousy sciatica hangover-12 depression-13 abrasion-14 anxiety-15 anger-16 angina-17 boils-18 grief-19 - pain
)
   (:init
(= (locale orange) 8)
(= (locale cherry) 2)
(= (locale chicken) 12)
(= (locale apple) 0)
(= (locale pepper) 3)
(= (locale bacon) 11)
(= (locale turkey) 1)
(= (locale papaya) 5)
(= (locale rice-22) 12)
(= (locale pear-23) 2)
(= (locale flounder-24) 11)
(= (locale okra-25) 11)
(= (locale pork-26) 11)
(= (locale lamb-27) 11)
(= (locale wurst-28) 0)
(= (locale shrimp-29) 0)
(= (harmony rest) 3)
(= (harmony satiety) 3)
(= (harmony curiosity) 3)
(= (harmony achievement) 3)
(= (harmony satisfaction) 3)
(eats orange papaya)
(eats orange rice-22)
(eats cherry cherry)
(eats cherry pepper)
(eats chicken bacon)
(eats chicken pork-26)
(eats chicken rice-22)
(eats apple pear-23)
(eats apple lamb-27)
(eats pepper pepper)
(eats bacon papaya)
(eats bacon bacon)
(eats turkey pepper)
(eats papaya shrimp-29)
(eats papaya rice-22)
(eats papaya papaya)
(eats rice-22 pear-23)
(eats pear-23 wurst-28)
(eats pear-23 papaya)
(eats pear-23 cherry)
(eats flounder-24 chicken)
(eats flounder-24 pear-23)
(eats flounder-24 lamb-27)
(eats okra-25 apple)
(eats okra-25 bacon)
(eats pork-26 turkey)
(eats lamb-27 orange)
(eats lamb-27 bacon)
(eats lamb-27 flounder-24)
(eats wurst-28 bacon)
(eats wurst-28 flounder-24)
(eats shrimp-29 bacon)
(eats shrimp-29 okra-25)
(eats shrimp-29 cherry)
(craves abrasion apple)
(craves abrasion-14 bacon)
(craves abrasion-14 lamb-27)
(craves achievement pork-26)
(craves anger turkey)
(craves anger-16 pear-23)
(craves angina pear-23)
(craves angina-17 flounder-24)
(craves anxiety rice-22)
(craves anxiety-15 turkey)
(craves boils papaya)
(craves boils-18 pepper)
(craves boils-18 turkey)
(craves curiosity pear-23)
(craves depression papaya)
(craves depression-13 okra-25)
(craves dread cherry)
(craves dread pepper)
(craves grief wurst-28)
(craves grief-19 orange)
(craves hangover apple)
(craves hangover pear-23)
(craves hangover-12 shrimp-29)
(craves jealousy flounder-24)
(craves jealousy rice-22)
(craves loneliness papaya)
(craves rest pear-23)
(craves satiety lamb-27)
(craves satiety pork-26)
(craves satiety shrimp-29)
(craves satiety wurst-28)
(craves satisfaction lamb-27)
(craves sciatica cherry)
(craves sciatica pepper))
   (:goal (and (craves grief pork-26))))
