(define (problem mprime-x-14)
   (:domain mystery-prime-typed)
   (:objects okra pork lamb wurst shrimp muffin broccoli potato lettuce melon tofu orange - food
             curiosity achievement satisfaction - pleasure
             loneliness dread jealousy sciatica hangover-12 depression-13 abrasion-14 anxiety-15 anger-16 angina-17 boils-18 grief-19 loneliness-20 dread-21 jealousy-22 sciatica-23 hangover-24 - pain
)
   (:init
(= (locale okra) 9)
(= (locale pork) 6)
(= (locale lamb) 5)
(= (locale wurst) 7)
(= (locale shrimp) 3)
(= (locale muffin) 1)
(= (locale broccoli) 2)
(= (locale potato) 5)
(= (locale lettuce) 7)
(= (locale melon) 7)
(= (locale tofu) 7)
(= (locale orange) 5)
(= (harmony curiosity) 2)
(= (harmony achievement) 1)
(= (harmony satisfaction) 3)
(eats okra muffin)
(eats okra broccoli)
(eats pork pork)
(eats lamb potato)
(eats lamb shrimp)
(eats lamb okra)
(eats wurst muffin)
(eats wurst lettuce)
(eats shrimp melon)
(eats shrimp tofu)
(eats shrimp wurst)
(eats muffin okra)
(eats broccoli lamb)
(eats potato potato)
(eats potato tofu)
(eats potato lamb)
(eats lettuce orange)
(eats lettuce tofu)
(eats lettuce shrimp)
(eats melon melon)
(eats melon okra)
(eats melon orange)
(eats tofu melon)
(eats tofu okra)
(eats tofu wurst)
(eats orange lamb)
(eats orange pork)
(craves abrasion-14 melon)
(craves achievement okra)
(craves achievement shrimp)
(craves achievement wurst)
(craves anger-16 okra)
(craves anger-16 tofu)
(craves angina-17 wurst)
(craves anxiety-15 tofu)
(craves boils-18 melon)
(craves curiosity melon)
(craves depression-13 broccoli)
(craves dread lettuce)
(craves dread wurst)
(craves dread-21 orange)
(craves grief-19 okra)
(craves hangover-12 broccoli)
(craves hangover-12 pork)
(craves hangover-24 muffin)
(craves jealousy shrimp)
(craves jealousy-22 okra)
(craves loneliness tofu)
(craves loneliness-20 broccoli)
(craves loneliness-20 okra)
(craves satisfaction broccoli)
(craves satisfaction potato)
(craves satisfaction shrimp)
(craves sciatica okra)
(craves sciatica orange)
(craves sciatica-23 lamb)
(craves sciatica-23 muffin))
   (:goal (and (craves grief-19 wurst) (craves loneliness-20 potato))))
