(define (problem mprime-x-19)
   (:domain mystery-prime-typed)
   (:objects cherry chicken apple pepper bacon turkey papaya rice-22 pear-23 flounder-24 okra-25 pork-26 lamb-27 wurst-28 - food
             rest satiety curiosity achievement - pleasure
             jealousy sciatica hangover-12 depression-13 abrasion-14 anxiety-15 anger-16 angina-17 boils-18 grief-19 loneliness-20 dread-21 jealousy-22 sciatica-23 hangover-24 - pain
)
   (:init
(= (locale cherry) 8)
(= (locale chicken) 3)
(= (locale apple) 5)
(= (locale pepper) 5)
(= (locale bacon) 7)
(= (locale turkey) 11)
(= (locale papaya) 3)
(= (locale rice-22) 10)
(= (locale pear-23) 4)
(= (locale flounder-24) 1)
(= (locale okra-25) 7)
(= (locale pork-26) 4)
(= (locale lamb-27) 3)
(= (locale wurst-28) 4)
(= (harmony rest) 3)
(= (harmony satiety) 3)
(= (harmony curiosity) 2)
(= (harmony achievement) 3)
(eats cherry rice-22)
(eats cherry chicken)
(eats chicken chicken)
(eats chicken cherry)
(eats apple okra-25)
(eats apple pepper)
(eats apple lamb-27)
(eats pepper rice-22)
(eats bacon cherry)
(eats bacon okra-25)
(eats bacon turkey)
(eats turkey chicken)
(eats turkey flounder-24)
(eats turkey pepper)
(eats papaya apple)
(eats papaya pork-26)
(eats rice-22 papaya)
(eats rice-22 wurst-28)
(eats pear-23 chicken)
(eats pear-23 papaya)
(eats pear-23 okra-25)
(eats flounder-24 pear-23)
(eats okra-25 bacon)
(eats okra-25 papaya)
(eats pork-26 chicken)
(eats pork-26 pork-26)
(eats pork-26 flounder-24)
(eats lamb-27 turkey)
(eats lamb-27 wurst-28)
(eats lamb-27 pepper)
(eats wurst-28 wurst-28)
(craves abrasion-14 okra-25)
(craves achievement flounder-24)
(craves achievement pork-26)
(craves achievement turkey)
(craves anger-16 pork-26)
(craves angina-17 turkey)
(craves angina-17 wurst-28)
(craves anxiety-15 wurst-28)
(craves boils-18 lamb-27)
(craves curiosity bacon)
(craves curiosity cherry)
(craves curiosity pepper)
(craves curiosity rice-22)
(craves depression-13 turkey)
(craves dread-21 pepper)
(craves grief-19 chicken)
(craves grief-19 pepper)
(craves hangover-12 lamb-27)
(craves hangover-12 rice-22)
(craves hangover-24 flounder-24)
(craves hangover-24 wurst-28)
(craves jealousy wurst-28)
(craves jealousy-22 okra-25)
(craves loneliness-20 bacon)
(craves loneliness-20 pepper)
(craves rest cherry)
(craves rest chicken)
(craves rest flounder-24)
(craves rest wurst-28)
(craves satiety cherry)
(craves satiety papaya)
(craves sciatica papaya)
(craves sciatica-23 lamb-27)
(craves sciatica-23 pepper))
   (:goal (and (craves dread-21 cherry) (craves hangover-24 chicken) (craves anger-16 flounder-24))))
