(define (problem mprime-x-4)
   (:domain mystery-prime-typed)
   (:objects broccoli potato lettuce melon tofu - food
             achievement satisfaction - pleasure
             sciatica hangover-12 depression-13 abrasion-14 - pain
)
   (:init
(= (locale broccoli) 3)
(= (locale potato) 1)
(= (locale lettuce) 0)
(= (locale melon) 1)
(= (locale tofu) 3)
(= (harmony achievement) 2)
(= (harmony satisfaction) 3)
(eats broccoli tofu)
(eats broccoli potato)
(eats potato melon)
(eats lettuce potato)
(eats melon broccoli)
(eats melon potato)
(eats melon tofu)
(eats tofu melon)
(eats tofu potato)
(craves achievement broccoli)
(craves achievement potato)
(craves satisfaction potato)
(craves satisfaction tofu)
(craves sciatica potato)
(craves hangover-12 tofu)
(craves hangover-12 melon)
(craves depression-13 lettuce)
(craves depression-13 tofu)
(craves abrasion-14 melon)
(craves abrasion-14 tofu))
   (:goal (and (craves hangover-12 tofu))))
