(define (problem mprime-x-10)
   (:domain mystery-prime-typed)
   (:objects turkey papaya rice-22 pear-23 flounder-24 - food
             rest - pleasure
             hangover depression abrasion anxiety - pain
)
   (:init
(= (locale turkey) 0)
(= (locale papaya) 4)
(= (locale rice-22) 4)
(= (locale pear-23) 2)
(= (locale flounder-24) 5)
(= (harmony rest) 1)
(eats turkey turkey)
(eats turkey flounder-24)
(eats turkey rice-22)
(eats papaya papaya)
(eats papaya pear-23)
(eats papaya rice-22)
(eats rice-22 turkey)
(eats rice-22 flounder-24)
(eats rice-22 papaya)
(eats pear-23 flounder-24)
(eats flounder-24 pear-23)
(craves rest rice-22)
(craves hangover turkey)
(craves depression turkey)
(craves depression pear-23)
(craves abrasion rice-22)
(craves anxiety turkey)
(craves anxiety flounder-24))
   (:goal (and (craves anxiety turkey))))
