(define (problem mprime-x-3)
   (:domain mystery-prime-typed)
   (:objects apple pepper bacon turkey papaya - food
             satiety curiosity - pleasure
             boils grief - pain
)
   (:init
(= (locale apple) 0)
(= (locale pepper) 5)
(= (locale bacon) 4)
(= (locale turkey) 1)
(= (locale papaya) 5)
(= (harmony satiety) 3)
(= (harmony curiosity) 1)
(eats apple apple)
(eats apple papaya)
(eats apple pepper)
(eats pepper pepper)
(eats pepper apple)
(eats pepper turkey)
(eats bacon turkey)
(eats bacon papaya)
(eats turkey turkey)
(eats papaya apple)
(eats papaya turkey)
(eats papaya papaya)
(craves satiety papaya)
(craves curiosity bacon)
(craves boils pepper)
(craves boils bacon)
(craves grief papaya)
(craves grief pepper))
   (:goal (and (craves satiety papaya))))
