(define (problem mprime-x-9)
   (:domain mystery-prime-typed)
   (:objects bacon turkey papaya rice-22 pear-23 - food
             satiety curiosity - pleasure
             anxiety anger angina boils grief - pain
)
   (:init
(= (locale bacon) 1)
(= (locale turkey) 1)
(= (locale papaya) 5)
(= (locale rice-22) 2)
(= (locale pear-23) 2)
(= (harmony satiety) 2)
(= (harmony curiosity) 1)
(eats bacon bacon)
(eats turkey bacon)
(eats turkey pear-23)
(eats papaya pear-23)
(eats rice-22 turkey)
(eats rice-22 rice-22)
(eats rice-22 pear-23)
(eats pear-23 rice-22)
(eats pear-23 turkey)
(eats pear-23 papaya)
(craves satiety papaya)
(craves satiety pear-23)
(craves curiosity bacon)
(craves anxiety rice-22)
(craves anger rice-22)
(craves angina papaya)
(craves angina pear-23)
(craves boils turkey)
(craves boils papaya)
(craves grief papaya))
   (:goal (and (craves boils papaya) (craves boils turkey) (craves satiety pear-23))))
