(define (problem mprime-x-7)
   (:domain mystery-prime-typed)
   (:objects broccoli potato lettuce melon tofu - food
             entertainment rest-6 - pleasure
             abrasion anxiety anger angina - pain
)
   (:init
(= (locale broccoli) 3)
(= (locale potato) 1)
(= (locale lettuce) 3)
(= (locale melon) 3)
(= (locale tofu) 0)
(= (harmony entertainment) 3)
(= (harmony rest-6) 3)
(eats broccoli broccoli)
(eats broccoli tofu)
(eats broccoli lettuce)
(eats potato tofu)
(eats potato melon)
(eats potato lettuce)
(eats lettuce broccoli)
(eats melon melon)
(eats melon lettuce)
(eats tofu potato)
(eats tofu broccoli)
(craves entertainment broccoli)
(craves rest-6 lettuce)
(craves rest-6 melon)
(craves abrasion potato)
(craves abrasion tofu)
(craves anxiety potato)
(craves anxiety lettuce)
(craves anger melon)
(craves angina broccoli))
   (:goal (and (craves anxiety potato) (craves rest-6 melon))))
