(define (problem mprime-x-6)
   (:domain mystery-prime-typed)
   (:objects potato lettuce melon tofu orange cherry - food
             entertainment rest-6 - pleasure
             anxiety anger - pain
)
   (:init
(= (locale potato) 2)
(= (locale lettuce) 5)
(= (locale melon) 1)
(= (locale tofu) 4)
(= (locale orange) 5)
(= (locale cherry) 4)
(= (harmony entertainment) 3)
(= (harmony rest-6) 1)
(eats potato cherry)
(eats potato potato)
(eats lettuce melon)
(eats lettuce lettuce)
(eats lettuce orange)
(eats melon melon)
(eats melon lettuce)
(eats melon cherry)
(eats tofu orange)
(eats orange melon)
(eats orange lettuce)
(eats orange tofu)
(eats cherry orange)
(eats cherry lettuce)
(craves entertainment tofu)
(craves entertainment potato)
(craves rest-6 melon)
(craves rest-6 cherry)
(craves anxiety orange)
(craves anxiety tofu)
(craves anger potato)
(craves anger tofu))
   (:goal (and (craves entertainment potato) (craves rest-6 cherry))))
