(define (problem mprime-x-1)
   (:domain mystery-prime-typed)
   (:objects muffin broccoli potato lettuce - food
             satisfaction - pleasure
             hangover depression abrasion anxiety anger angina - pain
)
   (:init
(= (locale muffin) 4)
(= (locale broccoli) 2)
(= (locale potato) 3)
(= (locale lettuce) 3)
(= (harmony satisfaction) 1)
(eats muffin broccoli)
(eats muffin potato)
(eats broccoli lettuce)
(eats broccoli broccoli)
(eats broccoli muffin)
(eats potato muffin)
(eats lettuce broccoli)
(eats lettuce lettuce)
(eats lettuce potato)
(craves satisfaction broccoli)
(craves satisfaction muffin)
(craves hangover lettuce)
(craves depression muffin)
(craves depression broccoli)
(craves abrasion lettuce)
(craves anxiety lettuce)
(craves anxiety muffin)
(craves anger potato)
(craves angina lettuce)
(craves angina potato))
   (:goal (and (craves satisfaction muffin) (craves abrasion lettuce))))
