(define (problem mprime-x-2)
   (:domain mystery-prime-typed)
   (:objects potato lettuce melon tofu orange cherry - food
             satisfaction - pleasure
             anxiety anger angina boils grief loneliness - pain
)
   (:init
(= (locale potato) 1)
(= (locale lettuce) 5)
(= (locale melon) 3)
(= (locale tofu) 1)
(= (locale orange) 0)
(= (locale cherry) 3)
(= (harmony satisfaction) 1)
(eats potato orange)
(eats lettuce orange)
(eats lettuce lettuce)
(eats lettuce potato)
(eats melon melon)
(eats melon lettuce)
(eats melon cherry)
(eats tofu cherry)
(eats tofu melon)
(eats tofu orange)
(eats orange cherry)
(eats orange potato)
(eats orange orange)
(eats cherry cherry)
(craves satisfaction cherry)
(craves satisfaction melon)
(craves anxiety potato)
(craves anxiety melon)
(craves anger tofu)
(craves anger potato)
(craves angina potato)
(craves boils melon)
(craves grief potato)
(craves grief orange)
(craves loneliness lettuce))
   (:goal (and (craves boils melon) (craves satisfaction melon))))
