(define (problem mprime-x-8)
   (:domain mystery-prime-typed)
   (:objects chicken apple pepper bacon turkey - food
             achievement - pleasure
             depression abrasion anxiety anger angina boils - pain
)
   (:init
(= (locale chicken) 1)
(= (locale apple) 1)
(= (locale pepper) 5)
(= (locale bacon) 1)
(= (locale turkey) 0)
(= (harmony achievement) 3)
(eats chicken turkey)
(eats chicken apple)
(eats chicken chicken)
(eats apple turkey)
(eats apple apple)
(eats apple bacon)
(eats pepper apple)
(eats bacon chicken)
(eats bacon turkey)
(eats turkey turkey)
(eats turkey apple)
(craves achievement pepper)
(craves achievement apple)
(craves depression chicken)
(craves abrasion turkey)
(craves abrasion pepper)
(craves anxiety bacon)
(craves anger pepper)
(craves anger apple)
(craves angina bacon)
(craves angina apple)
(craves boils chicken)
(craves boils apple))
   (:goal (and (craves anger pepper) (craves angina apple))))
