(define (problem mprime-x-8)
   (:domain mystery-prime-typed)
   (:objects bacon turkey papaya rice-22 pear-23 flounder-24 okra-25 - food
             entertainment rest-6 - pleasure
             loneliness dread jealousy - pain
)
   (:init
(= (locale bacon) 7)
(= (locale turkey) 0)
(= (locale papaya) 6)
(= (locale rice-22) 6)
(= (locale pear-23) 4)
(= (locale flounder-24) 5)
(= (locale okra-25) 3)
(= (harmony entertainment) 2)
(= (harmony rest-6) 2)
(eats bacon pear-23)
(eats turkey flounder-24)
(eats turkey rice-22)
(eats papaya papaya)
(eats rice-22 okra-25)
(eats pear-23 rice-22)
(eats flounder-24 papaya)
(eats flounder-24 bacon)
(eats okra-25 papaya)
(eats okra-25 bacon)
(craves entertainment turkey)
(craves entertainment rice-22)
(craves rest-6 okra-25)
(craves rest-6 bacon)
(craves loneliness turkey)
(craves dread okra-25)
(craves dread papaya)
(craves jealousy bacon))
   (:goal (and (craves jealousy bacon) (craves entertainment rice-22))))
