(define (problem mprime-x-7)
   (:domain mystery-prime-typed)
   (:objects bacon turkey papaya rice-22 pear-23 flounder-24 - food
             achievement satisfaction - pleasure
             depression abrasion - pain
)
   (:init
(= (locale bacon) 7)
(= (locale turkey) 6)
(= (locale papaya) 3)
(= (locale rice-22) 2)
(= (locale pear-23) 1)
(= (locale flounder-24) 3)
(= (harmony achievement) 3)
(= (harmony satisfaction) 3)
(eats bacon pear-23)
(eats turkey turkey)
(eats papaya pear-23)
(eats papaya flounder-24)
(eats rice-22 flounder-24)
(eats rice-22 pear-23)
(eats rice-22 bacon)
(eats pear-23 papaya)
(eats pear-23 turkey)
(eats flounder-24 pear-23)
(eats flounder-24 turkey)
(craves achievement pear-23)
(craves achievement turkey)
(craves satisfaction rice-22)
(craves satisfaction bacon)
(craves depression rice-22)
(craves abrasion papaya)
(craves abrasion turkey))
   (:goal (and (craves abrasion papaya))))
