(define (problem mprime-x-1)
   (:domain mystery-prime-typed)
   (:objects okra pork lamb wurst shrimp muffin broccoli - food
             satiety curiosity - pleasure
             loneliness dread jealousy sciatica hangover-12 depression-13 - pain
)
   (:init
(= (locale okra) 1)
(= (locale pork) 1)
(= (locale lamb) 5)
(= (locale wurst) 1)
(= (locale shrimp) 2)
(= (locale muffin) 3)
(= (locale broccoli) 2)
(= (harmony satiety) 3)
(= (harmony curiosity) 1)
(eats okra shrimp)
(eats pork wurst)
(eats pork okra)
(eats lamb wurst)
(eats lamb shrimp)
(eats lamb okra)
(eats wurst muffin)
(eats wurst wurst)
(eats wurst broccoli)
(eats shrimp wurst)
(eats shrimp lamb)
(eats shrimp pork)
(eats muffin okra)
(eats broccoli broccoli)
(eats broccoli shrimp)
(eats broccoli wurst)
(craves satiety lamb)
(craves satiety pork)
(craves curiosity okra)
(craves loneliness lamb)
(craves dread lamb)
(craves jealousy okra)
(craves sciatica okra)
(craves sciatica broccoli)
(craves hangover-12 lamb)
(craves hangover-12 muffin)
(craves depression-13 broccoli)
(craves depression-13 lamb))
   (:goal (and (craves hangover-12 lamb) (craves dread lamb))))
