(define (problem mprime-x-10)
   (:domain mystery-prime-typed)
   (:objects potato lettuce melon tofu orange cherry chicken - food
             rest satiety - pleasure
             sciatica hangover-12 depression-13 abrasion-14 anxiety-15 anger-16 - pain
)
   (:init
(= (locale potato) 4)
(= (locale lettuce) 5)
(= (locale melon) 3)
(= (locale tofu) 3)
(= (locale orange) 0)
(= (locale cherry) 2)
(= (locale chicken) 6)
(= (harmony rest) 2)
(= (harmony satiety) 1)
(eats potato cherry)
(eats potato chicken)
(eats potato potato)
(eats lettuce potato)
(eats lettuce cherry)
(eats lettuce lettuce)
(eats melon lettuce)
(eats tofu cherry)
(eats tofu chicken)
(eats tofu lettuce)
(eats orange chicken)
(eats cherry potato)
(eats chicken melon)
(eats chicken cherry)
(craves rest chicken)
(craves rest potato)
(craves satiety tofu)
(craves sciatica tofu)
(craves hangover-12 tofu)
(craves hangover-12 melon)
(craves depression-13 potato)
(craves depression-13 lettuce)
(craves abrasion-14 lettuce)
(craves anxiety-15 chicken)
(craves anxiety-15 melon)
(craves anger-16 tofu))
   (:goal (and (craves depression-13 potato))))
