(define (problem mprime-x-2)
   (:domain mystery-prime-typed)
   (:objects bacon turkey papaya rice-22 pear-23 flounder-24 okra-25 - food
             satiety curiosity achievement - pleasure
             sciatica hangover-12 - pain
)
   (:init
(= (locale bacon) 5)
(= (locale turkey) 1)
(= (locale papaya) 6)
(= (locale rice-22) 5)
(= (locale pear-23) 7)
(= (locale flounder-24) 1)
(= (locale okra-25) 4)
(= (harmony satiety) 3)
(= (harmony curiosity) 3)
(= (harmony achievement) 1)
(eats bacon papaya)
(eats turkey flounder-24)
(eats turkey rice-22)
(eats turkey turkey)
(eats papaya pear-23)
(eats papaya okra-25)
(eats rice-22 pear-23)
(eats rice-22 rice-22)
(eats rice-22 papaya)
(eats pear-23 pear-23)
(eats pear-23 papaya)
(eats flounder-24 pear-23)
(eats flounder-24 rice-22)
(eats flounder-24 turkey)
(eats okra-25 okra-25)
(craves satiety okra-25)
(craves satiety pear-23)
(craves curiosity papaya)
(craves achievement rice-22)
(craves sciatica pear-23)
(craves sciatica rice-22)
(craves hangover-12 bacon))
   (:goal (and (craves achievement rice-22))))
