(define (problem mprime-x-9)
   (:domain mystery-prime-typed)
   (:objects cherry chicken apple pepper bacon turkey papaya - food
             curiosity achievement satisfaction - pleasure
             abrasion anxiety anger angina boils grief loneliness - pain
)
   (:init
(= (locale cherry) 6)
(= (locale chicken) 4)
(= (locale apple) 0)
(= (locale pepper) 3)
(= (locale bacon) 6)
(= (locale turkey) 7)
(= (locale papaya) 2)
(= (harmony curiosity) 3)
(= (harmony achievement) 2)
(= (harmony satisfaction) 1)
(eats cherry apple)
(eats chicken bacon)
(eats chicken apple)
(eats chicken turkey)
(eats apple chicken)
(eats apple cherry)
(eats apple papaya)
(eats pepper chicken)
(eats bacon bacon)
(eats turkey papaya)
(eats turkey turkey)
(eats turkey apple)
(eats papaya chicken)
(craves curiosity apple)
(craves curiosity chicken)
(craves achievement apple)
(craves achievement bacon)
(craves satisfaction bacon)
(craves abrasion chicken)
(craves abrasion bacon)
(craves anxiety cherry)
(craves anxiety apple)
(craves anger chicken)
(craves angina bacon)
(craves boils bacon)
(craves grief papaya)
(craves loneliness cherry))
   (:goal (and (craves angina bacon) (craves achievement bacon) (craves abrasion bacon))))
