(define (problem mprime-x-3)
   (:domain mystery-prime-typed)
   (:objects flounder okra pork lamb wurst shrimp muffin - food
             entertainment rest-6 - pleasure
             angina boils grief loneliness dread jealousy sciatica - pain
)
   (:init
(= (locale flounder) 0)
(= (locale okra) 3)
(= (locale pork) 6)
(= (locale lamb) 0)
(= (locale wurst) 6)
(= (locale shrimp) 2)
(= (locale muffin) 2)
(= (harmony entertainment) 2)
(= (harmony rest-6) 2)
(eats flounder muffin)
(eats okra pork)
(eats okra lamb)
(eats okra shrimp)
(eats pork okra)
(eats pork shrimp)
(eats lamb flounder)
(eats lamb pork)
(eats wurst lamb)
(eats shrimp okra)
(eats shrimp wurst)
(eats shrimp flounder)
(eats muffin flounder)
(eats muffin muffin)
(eats muffin okra)
(craves entertainment okra)
(craves rest-6 okra)
(craves angina shrimp)
(craves boils wurst)
(craves boils flounder)
(craves grief flounder)
(craves grief okra)
(craves loneliness shrimp)
(craves dread lamb)
(craves jealousy pork)
(craves jealousy flounder)
(craves sciatica muffin)
(craves sciatica shrimp))
   (:goal (and (craves rest-6 okra) (craves boils wurst) (craves grief okra))))
