(define (problem mprime-x-4)
   (:domain mystery-prime-typed)
   (:objects melon tofu orange cherry chicken apple pepper - food
             entertainment rest-6 - pleasure
             angina boils grief loneliness dread - pain
)
   (:init
(= (locale melon) 7)
(= (locale tofu) 2)
(= (locale orange) 2)
(= (locale cherry) 2)
(= (locale chicken) 6)
(= (locale apple) 0)
(= (locale pepper) 7)
(= (harmony entertainment) 3)
(= (harmony rest-6) 3)
(eats melon tofu)
(eats melon pepper)
(eats tofu melon)
(eats tofu tofu)
(eats orange tofu)
(eats orange cherry)
(eats orange orange)
(eats cherry pepper)
(eats chicken cherry)
(eats chicken pepper)
(eats apple apple)
(eats apple orange)
(eats pepper chicken)
(craves entertainment tofu)
(craves entertainment apple)
(craves rest-6 cherry)
(craves rest-6 pepper)
(craves angina cherry)
(craves angina orange)
(craves boils orange)
(craves grief pepper)
(craves loneliness tofu)
(craves loneliness melon)
(craves dread melon))
   (:goal (and (craves loneliness melon) (craves boils orange) (craves entertainment tofu))))
