(define (problem mprime-x-6)
   (:domain mystery-prime-typed)
   (:objects potato lettuce melon tofu orange cherry - food
             satisfaction entertainment rest-6 - pleasure
             sciatica hangover-12 depression-13 abrasion-14 - pain
)
   (:init
(= (locale potato) 5)
(= (locale lettuce) 4)
(= (locale melon) 6)
(= (locale tofu) 0)
(= (locale orange) 0)
(= (locale cherry) 5)
(= (harmony satisfaction) 2)
(= (harmony entertainment) 2)
(= (harmony rest-6) 2)
(eats potato melon)
(eats potato cherry)
(eats potato lettuce)
(eats lettuce orange)
(eats lettuce lettuce)
(eats melon lettuce)
(eats melon cherry)
(eats tofu cherry)
(eats tofu orange)
(eats orange lettuce)
(eats cherry tofu)
(craves satisfaction orange)
(craves entertainment tofu)
(craves rest-6 melon)
(craves rest-6 orange)
(craves sciatica melon)
(craves sciatica tofu)
(craves hangover-12 cherry)
(craves hangover-12 potato)
(craves depression-13 orange)
(craves abrasion-14 tofu)
(craves abrasion-14 melon))
   (:goal (and (craves hangover-12 potato) (craves rest-6 orange) (craves depression-13 orange))))
