(define (problem mprime-x-5)
   (:domain mystery-prime-typed)
   (:objects melon tofu orange cherry chicken apple pepper - food
             satisfaction entertainment rest-6 - pleasure
             anxiety anger angina - pain
)
   (:init
(= (locale melon) 3)
(= (locale tofu) 7)
(= (locale orange) 0)
(= (locale cherry) 3)
(= (locale chicken) 0)
(= (locale apple) 6)
(= (locale pepper) 5)
(= (harmony satisfaction) 2)
(= (harmony entertainment) 3)
(= (harmony rest-6) 1)
(eats melon orange)
(eats tofu chicken)
(eats tofu cherry)
(eats tofu melon)
(eats orange pepper)
(eats orange orange)
(eats cherry apple)
(eats cherry cherry)
(eats chicken tofu)
(eats chicken cherry)
(eats chicken chicken)
(eats apple cherry)
(eats apple apple)
(eats apple chicken)
(eats pepper tofu)
(eats pepper melon)
(eats pepper orange)
(craves satisfaction chicken)
(craves entertainment cherry)
(craves entertainment chicken)
(craves rest-6 cherry)
(craves anxiety cherry)
(craves anger melon)
(craves anger orange)
(craves angina cherry)
(craves angina orange))
   (:goal (and (craves angina orange) (craves anger orange) (craves anxiety cherry))))
