(define (problem roverprob-3) (:domain rover)
(:objects
    general - lander
    colour high_res low_res - mode
    rover0 - rover
    rover0store - store
    waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 - waypoint
    camera0 camera1 - camera
    objective0 - objective
)
(:init
    (visible waypoint0 waypoint1)
    (visible waypoint0 waypoint2)
    (visible waypoint0 waypoint3)
    (visible waypoint0 waypoint4)
    (visible waypoint1 waypoint0)
    (visible waypoint1 waypoint4)
    (visible waypoint2 waypoint0)
    (visible waypoint2 waypoint4)
    (visible waypoint3 waypoint0)
    (visible waypoint4 waypoint0)
    (visible waypoint4 waypoint1)
    (visible waypoint4 waypoint2)
    (at_soil_sample waypoint3)
    (at_soil_sample waypoint2)
    (at_soil_sample waypoint0)
    (at_soil_sample waypoint1)
    (at_soil_sample waypoint4)
    (at_rock_sample waypoint3)
    (at_rock_sample waypoint1)
    (in_sun waypoint2)
    (in_sun waypoint3)
    (in_sun waypoint0)
    (in_sun waypoint1)
    (at_lander general waypoint1)
    (channel_free general)
    (in rover0 waypoint0)
    (available rover0)
    (store_of rover0store rover0)
    (empty rover0store)
    (equipped_for_soil_analysis rover0)
    (equipped_for_rock_analysis rover0)
    (equipped_for_imaging rover0)
    (can_traverse rover0 waypoint0 waypoint1)
    (can_traverse rover0 waypoint0 waypoint3)
    (can_traverse rover0 waypoint0 waypoint4)
    (can_traverse rover0 waypoint1 waypoint0)
    (can_traverse rover0 waypoint1 waypoint4)
    (can_traverse rover0 waypoint2 waypoint0)
    (can_traverse rover0 waypoint2 waypoint4)
    (can_traverse rover0 waypoint3 waypoint0)
    (can_traverse rover0 waypoint4 waypoint1)
    (can_traverse rover0 waypoint4 waypoint2)
    (on_board camera0 rover0)
    (calibration_target camera0 objective0)
    (supports camera0 colour)
    (on_board camera1 rover0)
    (calibration_target camera1 objective0)
    (supports camera1 colour)
    (supports camera1 high_res)
    (visible_from objective0 waypoint2)
    (visible_from objective0 waypoint1)
    (visible_from objective0 waypoint3)
    (= (recharges) 0)
    (= (energy rover0) 34)
)

(:goal (and
    (communicated_soil_data waypoint3)
    (communicated_rock_data waypoint3)
    (communicated_image_data objective0 high_res)
))

(:metric minimize (recharges))
)
