(define (problem roverprob-1) (:domain rover)
(:objects
    general - lander
    colour high_res low_res - mode
    rover0 rover1 rover2 rover3 rover4 - rover
    rover0store rover1store rover2store rover3store rover4store - store
    waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 waypoint7 waypoint8 waypoint9 waypoint10 waypoint11 waypoint12 waypoint13 waypoint14 waypoint15 waypoint16 waypoint17 waypoint18 - waypoint
    camera0 camera1 camera2 camera3 camera4 camera5 camera6 - camera
    objective0 objective1 objective2 objective3 objective4 objective5 objective6 - objective
)
(:init
    (visible waypoint0 waypoint7)
    (visible waypoint0 waypoint9)
    (visible waypoint0 waypoint11)
    (visible waypoint0 waypoint12)
    (visible waypoint1 waypoint4)
    (visible waypoint1 waypoint10)
    (visible waypoint1 waypoint15)
    (visible waypoint1 waypoint16)
    (visible waypoint2 waypoint3)
    (visible waypoint2 waypoint13)
    (visible waypoint3 waypoint2)
    (visible waypoint3 waypoint10)
    (visible waypoint4 waypoint1)
    (visible waypoint4 waypoint5)
    (visible waypoint4 waypoint14)
    (visible waypoint5 waypoint4)
    (visible waypoint5 waypoint11)
    (visible waypoint5 waypoint13)
    (visible waypoint6 waypoint9)
    (visible waypoint6 waypoint15)
    (visible waypoint6 waypoint16)
    (visible waypoint6 waypoint17)
    (visible waypoint7 waypoint0)
    (visible waypoint7 waypoint9)
    (visible waypoint7 waypoint12)
    (visible waypoint7 waypoint18)
    (visible waypoint8 waypoint12)
    (visible waypoint8 waypoint13)
    (visible waypoint9 waypoint0)
    (visible waypoint9 waypoint6)
    (visible waypoint9 waypoint7)
    (visible waypoint9 waypoint11)
    (visible waypoint9 waypoint13)
    (visible waypoint9 waypoint17)
    (visible waypoint9 waypoint18)
    (visible waypoint10 waypoint1)
    (visible waypoint10 waypoint3)
    (visible waypoint10 waypoint11)
    (visible waypoint11 waypoint5)
    (visible waypoint11 waypoint9)
    (visible waypoint11 waypoint10)
    (visible waypoint12 waypoint0)
    (visible waypoint12 waypoint7)
    (visible waypoint12 waypoint8)
    (visible waypoint12 waypoint14)
    (visible waypoint12 waypoint15)
    (visible waypoint13 waypoint2)
    (visible waypoint13 waypoint5)
    (visible waypoint13 waypoint8)
    (visible waypoint13 waypoint9)
    (visible waypoint14 waypoint4)
    (visible waypoint14 waypoint12)
    (visible waypoint14 waypoint18)
    (visible waypoint15 waypoint1)
    (visible waypoint15 waypoint6)
    (visible waypoint15 waypoint12)
    (visible waypoint16 waypoint1)
    (visible waypoint16 waypoint6)
    (visible waypoint16 waypoint18)
    (visible waypoint17 waypoint6)
    (visible waypoint17 waypoint9)
    (visible waypoint18 waypoint7)
    (visible waypoint18 waypoint9)
    (visible waypoint18 waypoint14)
    (visible waypoint18 waypoint16)
    (at_soil_sample waypoint13)
    (at_soil_sample waypoint1)
    (at_soil_sample waypoint12)
    (at_soil_sample waypoint7)
    (at_soil_sample waypoint15)
    (at_soil_sample waypoint17)
    (at_soil_sample waypoint8)
    (at_soil_sample waypoint11)
    (at_soil_sample waypoint0)
    (at_soil_sample waypoint9)
    (at_soil_sample waypoint5)
    (at_rock_sample waypoint9)
    (at_rock_sample waypoint16)
    (at_rock_sample waypoint3)
    (at_rock_sample waypoint4)
    (in_sun waypoint14)
    (in_sun waypoint5)
    (in_sun waypoint15)
    (in_sun waypoint16)
    (in_sun waypoint6)
    (at_lander general waypoint9)
    (channel_free general)
    (in rover0 waypoint9)
    (available rover0)
    (store_of rover0store rover0)
    (empty rover0store)
    (equipped_for_soil_analysis rover0)
    (equipped_for_rock_analysis rover0)
    (equipped_for_imaging rover0)
    (in rover1 waypoint4)
    (available rover1)
    (store_of rover1store rover1)
    (empty rover1store)
    (equipped_for_soil_analysis rover1)
    (equipped_for_rock_analysis rover1)
    (equipped_for_imaging rover1)
    (in rover2 waypoint14)
    (available rover2)
    (store_of rover2store rover2)
    (empty rover2store)
    (equipped_for_soil_analysis rover2)
    (equipped_for_rock_analysis rover2)
    (equipped_for_imaging rover2)
    (in rover3 waypoint1)
    (available rover3)
    (store_of rover3store rover3)
    (empty rover3store)
    (equipped_for_soil_analysis rover3)
    (equipped_for_rock_analysis rover3)
    (equipped_for_imaging rover3)
    (in rover4 waypoint18)
    (available rover4)
    (store_of rover4store rover4)
    (empty rover4store)
    (equipped_for_rock_analysis rover4)
    (can_traverse rover0 waypoint0 waypoint7)
    (can_traverse rover0 waypoint0 waypoint9)
    (can_traverse rover0 waypoint0 waypoint11)
    (can_traverse rover0 waypoint0 waypoint12)
    (can_traverse rover0 waypoint1 waypoint10)
    (can_traverse rover0 waypoint1 waypoint15)
    (can_traverse rover0 waypoint1 waypoint16)
    (can_traverse rover0 waypoint2 waypoint3)
    (can_traverse rover0 waypoint2 waypoint13)
    (can_traverse rover0 waypoint3 waypoint10)
    (can_traverse rover0 waypoint4 waypoint5)
    (can_traverse rover0 waypoint4 waypoint14)
    (can_traverse rover0 waypoint5 waypoint11)
    (can_traverse rover0 waypoint6 waypoint9)
    (can_traverse rover0 waypoint6 waypoint15)
    (can_traverse rover0 waypoint6 waypoint17)
    (can_traverse rover0 waypoint7 waypoint0)
    (can_traverse rover0 waypoint7 waypoint18)
    (can_traverse rover0 waypoint8 waypoint12)
    (can_traverse rover0 waypoint9 waypoint0)
    (can_traverse rover0 waypoint9 waypoint7)
    (can_traverse rover0 waypoint9 waypoint11)
    (can_traverse rover0 waypoint9 waypoint13)
    (can_traverse rover0 waypoint9 waypoint17)
    (can_traverse rover0 waypoint10 waypoint3)
    (can_traverse rover0 waypoint10 waypoint11)
    (can_traverse rover0 waypoint11 waypoint0)
    (can_traverse rover0 waypoint11 waypoint5)
    (can_traverse rover0 waypoint11 waypoint10)
    (can_traverse rover0 waypoint12 waypoint0)
    (can_traverse rover0 waypoint12 waypoint8)
    (can_traverse rover0 waypoint12 waypoint14)
    (can_traverse rover0 waypoint12 waypoint15)
    (can_traverse rover0 waypoint13 waypoint2)
    (can_traverse rover0 waypoint13 waypoint9)
    (can_traverse rover0 waypoint14 waypoint4)
    (can_traverse rover0 waypoint14 waypoint12)
    (can_traverse rover0 waypoint15 waypoint1)
    (can_traverse rover0 waypoint15 waypoint6)
    (can_traverse rover0 waypoint15 waypoint12)
    (can_traverse rover0 waypoint16 waypoint1)
    (can_traverse rover0 waypoint17 waypoint6)
    (can_traverse rover0 waypoint17 waypoint9)
    (can_traverse rover0 waypoint18 waypoint7)
    (can_traverse rover0 waypoint18 waypoint9)
    (can_traverse rover0 waypoint18 waypoint16)
    (can_traverse rover1 waypoint0 waypoint7)
    (can_traverse rover1 waypoint0 waypoint9)
    (can_traverse rover1 waypoint0 waypoint11)
    (can_traverse rover1 waypoint1 waypoint4)
    (can_traverse rover1 waypoint1 waypoint10)
    (can_traverse rover1 waypoint1 waypoint15)
    (can_traverse rover1 waypoint1 waypoint16)
    (can_traverse rover1 waypoint2 waypoint3)
    (can_traverse rover1 waypoint2 waypoint13)
    (can_traverse rover1 waypoint3 waypoint2)
    (can_traverse rover1 waypoint4 waypoint1)
    (can_traverse rover1 waypoint4 waypoint5)
    (can_traverse rover1 waypoint5 waypoint13)
    (can_traverse rover1 waypoint6 waypoint9)
    (can_traverse rover1 waypoint6 waypoint16)
    (can_traverse rover1 waypoint6 waypoint17)
    (can_traverse rover1 waypoint7 waypoint0)
    (can_traverse rover1 waypoint7 waypoint9)
    (can_traverse rover1 waypoint7 waypoint12)
    (can_traverse rover1 waypoint7 waypoint18)
    (can_traverse rover1 waypoint8 waypoint13)
    (can_traverse rover1 waypoint9 waypoint13)
    (can_traverse rover1 waypoint9 waypoint17)
    (can_traverse rover1 waypoint9 waypoint18)
    (can_traverse rover1 waypoint10 waypoint1)
    (can_traverse rover1 waypoint10 waypoint11)
    (can_traverse rover1 waypoint11 waypoint0)
    (can_traverse rover1 waypoint12 waypoint7)
    (can_traverse rover1 waypoint12 waypoint15)
    (can_traverse rover1 waypoint13 waypoint2)
    (can_traverse rover1 waypoint13 waypoint5)
    (can_traverse rover1 waypoint13 waypoint8)
    (can_traverse rover1 waypoint13 waypoint9)
    (can_traverse rover1 waypoint14 waypoint18)
    (can_traverse rover1 waypoint15 waypoint1)
    (can_traverse rover1 waypoint16 waypoint1)
    (can_traverse rover1 waypoint16 waypoint6)
    (can_traverse rover1 waypoint16 waypoint18)
    (can_traverse rover1 waypoint17 waypoint6)
    (can_traverse rover1 waypoint17 waypoint9)
    (can_traverse rover1 waypoint18 waypoint7)
    (can_traverse rover1 waypoint18 waypoint9)
    (can_traverse rover1 waypoint18 waypoint14)
    (can_traverse rover1 waypoint18 waypoint16)
    (can_traverse rover2 waypoint0 waypoint7)
    (can_traverse rover2 waypoint0 waypoint9)
    (can_traverse rover2 waypoint0 waypoint11)
    (can_traverse rover2 waypoint0 waypoint12)
    (can_traverse rover2 waypoint1 waypoint4)
    (can_traverse rover2 waypoint1 waypoint10)
    (can_traverse rover2 waypoint1 waypoint15)
    (can_traverse rover2 waypoint2 waypoint3)
    (can_traverse rover2 waypoint2 waypoint13)
    (can_traverse rover2 waypoint3 waypoint2)
    (can_traverse rover2 waypoint3 waypoint10)
    (can_traverse rover2 waypoint4 waypoint1)
    (can_traverse rover2 waypoint4 waypoint5)
    (can_traverse rover2 waypoint4 waypoint14)
    (can_traverse rover2 waypoint5 waypoint4)
    (can_traverse rover2 waypoint6 waypoint16)
    (can_traverse rover2 waypoint6 waypoint17)
    (can_traverse rover2 waypoint7 waypoint9)
    (can_traverse rover2 waypoint7 waypoint12)
    (can_traverse rover2 waypoint7 waypoint18)
    (can_traverse rover2 waypoint8 waypoint12)
    (can_traverse rover2 waypoint9 waypoint0)
    (can_traverse rover2 waypoint9 waypoint7)
    (can_traverse rover2 waypoint9 waypoint13)
    (can_traverse rover2 waypoint9 waypoint17)
    (can_traverse rover2 waypoint9 waypoint18)
    (can_traverse rover2 waypoint10 waypoint1)
    (can_traverse rover2 waypoint10 waypoint3)
    (can_traverse rover2 waypoint10 waypoint11)
    (can_traverse rover2 waypoint11 waypoint0)
    (can_traverse rover2 waypoint11 waypoint9)
    (can_traverse rover2 waypoint11 waypoint10)
    (can_traverse rover2 waypoint12 waypoint0)
    (can_traverse rover2 waypoint12 waypoint7)
    (can_traverse rover2 waypoint12 waypoint8)
    (can_traverse rover2 waypoint13 waypoint8)
    (can_traverse rover2 waypoint13 waypoint9)
    (can_traverse rover2 waypoint14 waypoint18)
    (can_traverse rover2 waypoint15 waypoint1)
    (can_traverse rover2 waypoint16 waypoint1)
    (can_traverse rover2 waypoint16 waypoint6)
    (can_traverse rover2 waypoint16 waypoint18)
    (can_traverse rover2 waypoint17 waypoint6)
    (can_traverse rover2 waypoint18 waypoint7)
    (can_traverse rover2 waypoint18 waypoint9)
    (can_traverse rover2 waypoint18 waypoint14)
    (can_traverse rover2 waypoint18 waypoint16)
    (can_traverse rover3 waypoint0 waypoint7)
    (can_traverse rover3 waypoint0 waypoint9)
    (can_traverse rover3 waypoint0 waypoint11)
    (can_traverse rover3 waypoint1 waypoint10)
    (can_traverse rover3 waypoint1 waypoint15)
    (can_traverse rover3 waypoint2 waypoint13)
    (can_traverse rover3 waypoint3 waypoint2)
    (can_traverse rover3 waypoint3 waypoint10)
    (can_traverse rover3 waypoint4 waypoint1)
    (can_traverse rover3 waypoint4 waypoint5)
    (can_traverse rover3 waypoint4 waypoint14)
    (can_traverse rover3 waypoint5 waypoint4)
    (can_traverse rover3 waypoint5 waypoint11)
    (can_traverse rover3 waypoint5 waypoint13)
    (can_traverse rover3 waypoint6 waypoint9)
    (can_traverse rover3 waypoint6 waypoint15)
    (can_traverse rover3 waypoint6 waypoint16)
    (can_traverse rover3 waypoint6 waypoint17)
    (can_traverse rover3 waypoint7 waypoint0)
    (can_traverse rover3 waypoint7 waypoint9)
    (can_traverse rover3 waypoint7 waypoint12)
    (can_traverse rover3 waypoint7 waypoint18)
    (can_traverse rover3 waypoint8 waypoint12)
    (can_traverse rover3 waypoint9 waypoint0)
    (can_traverse rover3 waypoint9 waypoint6)
    (can_traverse rover3 waypoint9 waypoint18)
    (can_traverse rover3 waypoint10 waypoint1)
    (can_traverse rover3 waypoint10 waypoint3)
    (can_traverse rover3 waypoint10 waypoint11)
    (can_traverse rover3 waypoint11 waypoint0)
    (can_traverse rover3 waypoint11 waypoint9)
    (can_traverse rover3 waypoint11 waypoint10)
    (can_traverse rover3 waypoint12 waypoint0)
    (can_traverse rover3 waypoint12 waypoint7)
    (can_traverse rover3 waypoint12 waypoint8)
    (can_traverse rover3 waypoint12 waypoint15)
    (can_traverse rover3 waypoint13 waypoint2)
    (can_traverse rover3 waypoint13 waypoint5)
    (can_traverse rover3 waypoint14 waypoint4)
    (can_traverse rover3 waypoint14 waypoint18)
    (can_traverse rover3 waypoint15 waypoint1)
    (can_traverse rover3 waypoint15 waypoint12)
    (can_traverse rover3 waypoint16 waypoint1)
    (can_traverse rover3 waypoint16 waypoint6)
    (can_traverse rover3 waypoint17 waypoint6)
    (can_traverse rover3 waypoint18 waypoint7)
    (can_traverse rover3 waypoint18 waypoint9)
    (can_traverse rover3 waypoint18 waypoint14)
    (can_traverse rover4 waypoint0 waypoint9)
    (can_traverse rover4 waypoint0 waypoint11)
    (can_traverse rover4 waypoint0 waypoint12)
    (can_traverse rover4 waypoint1 waypoint10)
    (can_traverse rover4 waypoint1 waypoint16)
    (can_traverse rover4 waypoint2 waypoint3)
    (can_traverse rover4 waypoint2 waypoint13)
    (can_traverse rover4 waypoint3 waypoint10)
    (can_traverse rover4 waypoint4 waypoint1)
    (can_traverse rover4 waypoint4 waypoint14)
    (can_traverse rover4 waypoint5 waypoint4)
    (can_traverse rover4 waypoint5 waypoint11)
    (can_traverse rover4 waypoint5 waypoint13)
    (can_traverse rover4 waypoint6 waypoint15)
    (can_traverse rover4 waypoint6 waypoint16)
    (can_traverse rover4 waypoint7 waypoint9)
    (can_traverse rover4 waypoint8 waypoint12)
    (can_traverse rover4 waypoint9 waypoint0)
    (can_traverse rover4 waypoint9 waypoint6)
    (can_traverse rover4 waypoint9 waypoint7)
    (can_traverse rover4 waypoint9 waypoint11)
    (can_traverse rover4 waypoint9 waypoint13)
    (can_traverse rover4 waypoint9 waypoint17)
    (can_traverse rover4 waypoint9 waypoint18)
    (can_traverse rover4 waypoint10 waypoint1)
    (can_traverse rover4 waypoint10 waypoint3)
    (can_traverse rover4 waypoint10 waypoint11)
    (can_traverse rover4 waypoint11 waypoint0)
    (can_traverse rover4 waypoint11 waypoint5)
    (can_traverse rover4 waypoint11 waypoint10)
    (can_traverse rover4 waypoint12 waypoint0)
    (can_traverse rover4 waypoint12 waypoint7)
    (can_traverse rover4 waypoint12 waypoint8)
    (can_traverse rover4 waypoint12 waypoint14)
    (can_traverse rover4 waypoint12 waypoint15)
    (can_traverse rover4 waypoint13 waypoint2)
    (can_traverse rover4 waypoint13 waypoint5)
    (can_traverse rover4 waypoint13 waypoint8)
    (can_traverse rover4 waypoint13 waypoint9)
    (can_traverse rover4 waypoint14 waypoint4)
    (can_traverse rover4 waypoint14 waypoint12)
    (can_traverse rover4 waypoint15 waypoint6)
    (can_traverse rover4 waypoint15 waypoint12)
    (can_traverse rover4 waypoint16 waypoint1)
    (can_traverse rover4 waypoint16 waypoint6)
    (can_traverse rover4 waypoint16 waypoint18)
    (can_traverse rover4 waypoint17 waypoint9)
    (can_traverse rover4 waypoint18 waypoint9)
    (can_traverse rover4 waypoint18 waypoint16)
    (on_board camera0 rover1)
    (calibration_target camera0 objective3)
    (supports camera0 low_res)
    (on_board camera1 rover2)
    (calibration_target camera1 objective2)
    (supports camera1 low_res)
    (on_board camera2 rover3)
    (calibration_target camera2 objective1)
    (supports camera2 high_res)
    (supports camera2 low_res)
    (on_board camera3 rover2)
    (calibration_target camera3 objective6)
    (supports camera3 colour)
    (on_board camera4 rover3)
    (calibration_target camera4 objective2)
    (supports camera4 colour)
    (supports camera4 high_res)
    (supports camera4 low_res)
    (on_board camera5 rover0)
    (calibration_target camera5 objective4)
    (supports camera5 high_res)
    (supports camera5 low_res)
    (on_board camera6 rover3)
    (calibration_target camera6 objective6)
    (supports camera6 colour)
    (visible_from objective0 waypoint5)
    (visible_from objective0 waypoint8)
    (visible_from objective1 waypoint1)
    (visible_from objective2 waypoint13)
    (visible_from objective2 waypoint18)
    (visible_from objective2 waypoint8)
    (visible_from objective3 waypoint8)
    (visible_from objective4 waypoint16)
    (visible_from objective4 waypoint13)
    (visible_from objective4 waypoint6)
    (visible_from objective5 waypoint13)
    (visible_from objective5 waypoint9)
    (visible_from objective5 waypoint3)
    (visible_from objective6 waypoint0)
    (visible_from objective6 waypoint15)
    (= (recharges) 0)
    (= (energy rover0) 115)
    (= (energy rover1) 85)
    (= (energy rover2) 98)
    (= (energy rover3) 109)
    (= (energy rover4) 78)
)

(:goal (and
    (communicated_soil_data waypoint11)
    (communicated_soil_data waypoint9)
    (communicated_soil_data waypoint0)
    (communicated_soil_data waypoint1)
    (communicated_soil_data waypoint13)
    (communicated_soil_data waypoint7)
    (communicated_soil_data waypoint12)
    (communicated_rock_data waypoint9)
    (communicated_rock_data waypoint3)
    (communicated_rock_data waypoint16)
    (communicated_rock_data waypoint4)
    (communicated_image_data objective1 high_res)
))

(:metric minimize (recharges))
)
