(define (problem roverprob-6) (:domain rover)
(:objects
    general - lander
    colour high_res low_res - mode
    rover0 rover1 rover2 - rover
    rover0store rover1store rover2store - store
    waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 waypoint7 waypoint8 waypoint9 waypoint10 waypoint11 waypoint12 waypoint13 waypoint14 waypoint15 waypoint16 waypoint17 - waypoint
    camera0 camera1 camera2 camera3 camera4 camera5 - camera
    objective0 objective1 objective2 objective3 objective4 objective5 objective6 objective7 - objective
)
(:init
    (visible waypoint0 waypoint1)
    (visible waypoint0 waypoint4)
    (visible waypoint1 waypoint0)
    (visible waypoint1 waypoint2)
    (visible waypoint1 waypoint6)
    (visible waypoint1 waypoint10)
    (visible waypoint1 waypoint12)
    (visible waypoint2 waypoint1)
    (visible waypoint2 waypoint3)
    (visible waypoint2 waypoint4)
    (visible waypoint2 waypoint17)
    (visible waypoint3 waypoint2)
    (visible waypoint3 waypoint7)
    (visible waypoint3 waypoint8)
    (visible waypoint3 waypoint15)
    (visible waypoint4 waypoint0)
    (visible waypoint4 waypoint2)
    (visible waypoint4 waypoint9)
    (visible waypoint4 waypoint13)
    (visible waypoint5 waypoint4)
    (visible waypoint5 waypoint7)
    (visible waypoint5 waypoint17)
    (visible waypoint6 waypoint1)
    (visible waypoint6 waypoint7)
    (visible waypoint6 waypoint9)
    (visible waypoint6 waypoint15)
    (visible waypoint6 waypoint16)
    (visible waypoint7 waypoint3)
    (visible waypoint7 waypoint5)
    (visible waypoint7 waypoint6)
    (visible waypoint7 waypoint13)
    (visible waypoint8 waypoint3)
    (visible waypoint8 waypoint12)
    (visible waypoint8 waypoint17)
    (visible waypoint9 waypoint4)
    (visible waypoint9 waypoint6)
    (visible waypoint9 waypoint11)
    (visible waypoint10 waypoint1)
    (visible waypoint10 waypoint13)
    (visible waypoint10 waypoint17)
    (visible waypoint11 waypoint9)
    (visible waypoint12 waypoint1)
    (visible waypoint12 waypoint8)
    (visible waypoint12 waypoint16)
    (visible waypoint13 waypoint4)
    (visible waypoint13 waypoint7)
    (visible waypoint13 waypoint10)
    (visible waypoint14 waypoint15)
    (visible waypoint14 waypoint17)
    (visible waypoint15 waypoint6)
    (visible waypoint15 waypoint8)
    (visible waypoint15 waypoint14)
    (visible waypoint16 waypoint6)
    (visible waypoint16 waypoint12)
    (visible waypoint17 waypoint2)
    (visible waypoint17 waypoint5)
    (visible waypoint17 waypoint8)
    (visible waypoint17 waypoint10)
    (visible waypoint17 waypoint14)
    (at_soil_sample waypoint8)
    (at_soil_sample waypoint14)
    (at_soil_sample waypoint13)
    (at_soil_sample waypoint12)
    (at_rock_sample waypoint8)
    (at_rock_sample waypoint13)
    (at_rock_sample waypoint7)
    (at_rock_sample waypoint12)
    (at_rock_sample waypoint6)
    (at_rock_sample waypoint14)
    (at_rock_sample waypoint15)
    (at_rock_sample waypoint9)
    (at_rock_sample waypoint16)
    (at_rock_sample waypoint4)
    (at_rock_sample waypoint5)
    (at_rock_sample waypoint11)
    (in_sun waypoint9)
    (in_sun waypoint3)
    (in_sun waypoint6)
    (in_sun waypoint5)
    (in_sun waypoint4)
    (in_sun waypoint13)
    (in_sun waypoint8)
    (in_sun waypoint2)
    (in_sun waypoint0)
    (at_lander general waypoint4)
    (channel_free general)
    (in rover0 waypoint0)
    (available rover0)
    (store_of rover0store rover0)
    (empty rover0store)
    (equipped_for_soil_analysis rover0)
    (equipped_for_imaging rover0)
    (in rover1 waypoint8)
    (available rover1)
    (store_of rover1store rover1)
    (empty rover1store)
    (equipped_for_soil_analysis rover1)
    (equipped_for_rock_analysis rover1)
    (equipped_for_imaging rover1)
    (in rover2 waypoint9)
    (available rover2)
    (store_of rover2store rover2)
    (empty rover2store)
    (equipped_for_soil_analysis rover2)
    (equipped_for_rock_analysis rover2)
    (can_traverse rover0 waypoint0 waypoint4)
    (can_traverse rover0 waypoint1 waypoint2)
    (can_traverse rover0 waypoint1 waypoint6)
    (can_traverse rover0 waypoint1 waypoint10)
    (can_traverse rover0 waypoint1 waypoint12)
    (can_traverse rover0 waypoint2 waypoint1)
    (can_traverse rover0 waypoint2 waypoint17)
    (can_traverse rover0 waypoint3 waypoint7)
    (can_traverse rover0 waypoint3 waypoint15)
    (can_traverse rover0 waypoint4 waypoint0)
    (can_traverse rover0 waypoint4 waypoint5)
    (can_traverse rover0 waypoint4 waypoint9)
    (can_traverse rover0 waypoint5 waypoint4)
    (can_traverse rover0 waypoint5 waypoint7)
    (can_traverse rover0 waypoint5 waypoint17)
    (can_traverse rover0 waypoint6 waypoint7)
    (can_traverse rover0 waypoint6 waypoint9)
    (can_traverse rover0 waypoint6 waypoint16)
    (can_traverse rover0 waypoint7 waypoint3)
    (can_traverse rover0 waypoint7 waypoint5)
    (can_traverse rover0 waypoint7 waypoint6)
    (can_traverse rover0 waypoint8 waypoint15)
    (can_traverse rover0 waypoint9 waypoint4)
    (can_traverse rover0 waypoint9 waypoint11)
    (can_traverse rover0 waypoint10 waypoint1)
    (can_traverse rover0 waypoint10 waypoint13)
    (can_traverse rover0 waypoint10 waypoint17)
    (can_traverse rover0 waypoint11 waypoint9)
    (can_traverse rover0 waypoint12 waypoint1)
    (can_traverse rover0 waypoint13 waypoint7)
    (can_traverse rover0 waypoint13 waypoint10)
    (can_traverse rover0 waypoint14 waypoint15)
    (can_traverse rover0 waypoint14 waypoint17)
    (can_traverse rover0 waypoint15 waypoint8)
    (can_traverse rover0 waypoint15 waypoint14)
    (can_traverse rover0 waypoint16 waypoint6)
    (can_traverse rover0 waypoint16 waypoint12)
    (can_traverse rover0 waypoint17 waypoint2)
    (can_traverse rover0 waypoint17 waypoint5)
    (can_traverse rover0 waypoint17 waypoint8)
    (can_traverse rover0 waypoint17 waypoint10)
    (can_traverse rover0 waypoint17 waypoint14)
    (can_traverse rover1 waypoint0 waypoint1)
    (can_traverse rover1 waypoint0 waypoint4)
    (can_traverse rover1 waypoint1 waypoint0)
    (can_traverse rover1 waypoint1 waypoint2)
    (can_traverse rover1 waypoint1 waypoint6)
    (can_traverse rover1 waypoint2 waypoint1)
    (can_traverse rover1 waypoint2 waypoint17)
    (can_traverse rover1 waypoint3 waypoint2)
    (can_traverse rover1 waypoint3 waypoint7)
    (can_traverse rover1 waypoint3 waypoint8)
    (can_traverse rover1 waypoint3 waypoint15)
    (can_traverse rover1 waypoint4 waypoint0)
    (can_traverse rover1 waypoint4 waypoint2)
    (can_traverse rover1 waypoint4 waypoint9)
    (can_traverse rover1 waypoint5 waypoint7)
    (can_traverse rover1 waypoint5 waypoint17)
    (can_traverse rover1 waypoint6 waypoint1)
    (can_traverse rover1 waypoint6 waypoint16)
    (can_traverse rover1 waypoint7 waypoint3)
    (can_traverse rover1 waypoint7 waypoint5)
    (can_traverse rover1 waypoint7 waypoint13)
    (can_traverse rover1 waypoint8 waypoint12)
    (can_traverse rover1 waypoint8 waypoint17)
    (can_traverse rover1 waypoint9 waypoint4)
    (can_traverse rover1 waypoint9 waypoint6)
    (can_traverse rover1 waypoint9 waypoint11)
    (can_traverse rover1 waypoint10 waypoint13)
    (can_traverse rover1 waypoint10 waypoint17)
    (can_traverse rover1 waypoint11 waypoint9)
    (can_traverse rover1 waypoint12 waypoint8)
    (can_traverse rover1 waypoint12 waypoint16)
    (can_traverse rover1 waypoint13 waypoint7)
    (can_traverse rover1 waypoint13 waypoint10)
    (can_traverse rover1 waypoint14 waypoint17)
    (can_traverse rover1 waypoint15 waypoint3)
    (can_traverse rover1 waypoint15 waypoint6)
    (can_traverse rover1 waypoint16 waypoint6)
    (can_traverse rover1 waypoint17 waypoint2)
    (can_traverse rover1 waypoint17 waypoint5)
    (can_traverse rover1 waypoint17 waypoint8)
    (can_traverse rover1 waypoint17 waypoint10)
    (can_traverse rover1 waypoint17 waypoint14)
    (can_traverse rover2 waypoint0 waypoint4)
    (can_traverse rover2 waypoint1 waypoint12)
    (can_traverse rover2 waypoint2 waypoint3)
    (can_traverse rover2 waypoint2 waypoint4)
    (can_traverse rover2 waypoint2 waypoint17)
    (can_traverse rover2 waypoint3 waypoint2)
    (can_traverse rover2 waypoint3 waypoint7)
    (can_traverse rover2 waypoint4 waypoint0)
    (can_traverse rover2 waypoint4 waypoint5)
    (can_traverse rover2 waypoint4 waypoint9)
    (can_traverse rover2 waypoint5 waypoint4)
    (can_traverse rover2 waypoint5 waypoint7)
    (can_traverse rover2 waypoint6 waypoint7)
    (can_traverse rover2 waypoint6 waypoint9)
    (can_traverse rover2 waypoint6 waypoint15)
    (can_traverse rover2 waypoint6 waypoint16)
    (can_traverse rover2 waypoint7 waypoint3)
    (can_traverse rover2 waypoint7 waypoint5)
    (can_traverse rover2 waypoint7 waypoint6)
    (can_traverse rover2 waypoint7 waypoint13)
    (can_traverse rover2 waypoint8 waypoint3)
    (can_traverse rover2 waypoint8 waypoint12)
    (can_traverse rover2 waypoint9 waypoint4)
    (can_traverse rover2 waypoint9 waypoint6)
    (can_traverse rover2 waypoint9 waypoint11)
    (can_traverse rover2 waypoint10 waypoint1)
    (can_traverse rover2 waypoint10 waypoint13)
    (can_traverse rover2 waypoint11 waypoint9)
    (can_traverse rover2 waypoint12 waypoint1)
    (can_traverse rover2 waypoint12 waypoint8)
    (can_traverse rover2 waypoint12 waypoint16)
    (can_traverse rover2 waypoint13 waypoint4)
    (can_traverse rover2 waypoint13 waypoint7)
    (can_traverse rover2 waypoint13 waypoint10)
    (can_traverse rover2 waypoint14 waypoint15)
    (can_traverse rover2 waypoint14 waypoint17)
    (can_traverse rover2 waypoint15 waypoint6)
    (can_traverse rover2 waypoint15 waypoint14)
    (can_traverse rover2 waypoint16 waypoint6)
    (can_traverse rover2 waypoint16 waypoint12)
    (can_traverse rover2 waypoint17 waypoint2)
    (on_board camera0 rover0)
    (calibration_target camera0 objective5)
    (supports camera0 colour)
    (supports camera0 high_res)
    (supports camera0 low_res)
    (on_board camera1 rover0)
    (calibration_target camera1 objective2)
    (supports camera1 low_res)
    (on_board camera2 rover0)
    (calibration_target camera2 objective7)
    (supports camera2 colour)
    (supports camera2 high_res)
    (on_board camera3 rover0)
    (calibration_target camera3 objective3)
    (supports camera3 colour)
    (supports camera3 high_res)
    (supports camera3 low_res)
    (on_board camera4 rover1)
    (calibration_target camera4 objective1)
    (supports camera4 colour)
    (on_board camera5 rover0)
    (calibration_target camera5 objective1)
    (supports camera5 high_res)
    (visible_from objective0 waypoint12)
    (visible_from objective0 waypoint15)
    (visible_from objective0 waypoint16)
    (visible_from objective1 waypoint10)
    (visible_from objective1 waypoint13)
    (visible_from objective2 waypoint2)
    (visible_from objective2 waypoint11)
    (visible_from objective3 waypoint1)
    (visible_from objective3 waypoint8)
    (visible_from objective3 waypoint0)
    (visible_from objective4 waypoint14)
    (visible_from objective5 waypoint0)
    (visible_from objective5 waypoint17)
    (visible_from objective5 waypoint11)
    (visible_from objective6 waypoint10)
    (visible_from objective6 waypoint3)
    (visible_from objective7 waypoint5)
    (visible_from objective7 waypoint10)
    (visible_from objective7 waypoint15)
    (= (recharges) 0)
    (= (energy rover0) 82)
    (= (energy rover1) 93)
    (= (energy rover2) 85)
)

(:goal (and
    (communicated_soil_data waypoint8)
    (communicated_soil_data waypoint12)
    (communicated_soil_data waypoint14)
    (communicated_soil_data waypoint13)
    (communicated_rock_data waypoint4)
    (communicated_rock_data waypoint9)
    (communicated_rock_data waypoint13)
    (communicated_rock_data waypoint14)
    (communicated_rock_data waypoint12)
    (communicated_rock_data waypoint5)
    (communicated_rock_data waypoint16)
    (communicated_image_data objective1 high_res)
))

(:metric minimize (recharges))
)
