(define (problem roverprob-3) (:domain rover)
(:objects
    general - lander
    colour high_res low_res - mode
    rover0 rover1 rover2 rover3 - rover
    rover0store rover1store rover2store rover3store - store
    waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 waypoint7 waypoint8 waypoint9 waypoint10 - waypoint
    camera0 camera1 camera2 - camera
    objective0 objective1 objective2 objective3 objective4 objective5 objective6 objective7 - objective
)
(:init
    (visible waypoint0 waypoint8)
    (visible waypoint1 waypoint6)
    (visible waypoint1 waypoint10)
    (visible waypoint2 waypoint5)
    (visible waypoint2 waypoint6)
    (visible waypoint2 waypoint10)
    (visible waypoint3 waypoint6)
    (visible waypoint4 waypoint5)
    (visible waypoint4 waypoint7)
    (visible waypoint4 waypoint10)
    (visible waypoint5 waypoint2)
    (visible waypoint5 waypoint4)
    (visible waypoint5 waypoint6)
    (visible waypoint5 waypoint8)
    (visible waypoint6 waypoint1)
    (visible waypoint6 waypoint2)
    (visible waypoint6 waypoint3)
    (visible waypoint6 waypoint5)
    (visible waypoint6 waypoint7)
    (visible waypoint6 waypoint9)
    (visible waypoint7 waypoint6)
    (visible waypoint7 waypoint8)
    (visible waypoint7 waypoint10)
    (visible waypoint8 waypoint0)
    (visible waypoint8 waypoint5)
    (visible waypoint8 waypoint7)
    (visible waypoint8 waypoint10)
    (visible waypoint9 waypoint4)
    (visible waypoint9 waypoint6)
    (visible waypoint10 waypoint2)
    (visible waypoint10 waypoint4)
    (visible waypoint10 waypoint7)
    (visible waypoint10 waypoint8)
    (at_soil_sample waypoint3)
    (at_soil_sample waypoint5)
    (at_soil_sample waypoint9)
    (at_soil_sample waypoint1)
    (at_soil_sample waypoint10)
    (at_soil_sample waypoint8)
    (at_soil_sample waypoint6)
    (at_soil_sample waypoint2)
    (at_soil_sample waypoint7)
    (at_soil_sample waypoint0)
    (at_soil_sample waypoint4)
    (at_rock_sample waypoint9)
    (at_rock_sample waypoint8)
    (in_sun waypoint2)
    (in_sun waypoint8)
    (in_sun waypoint0)
    (in_sun waypoint6)
    (in_sun waypoint7)
    (in_sun waypoint9)
    (in_sun waypoint10)
    (in_sun waypoint4)
    (in_sun waypoint3)
    (in_sun waypoint5)
    (at_lander general waypoint1)
    (channel_free general)
    (in rover0 waypoint0)
    (available rover0)
    (store_of rover0store rover0)
    (empty rover0store)
    (equipped_for_soil_analysis rover0)
    (equipped_for_rock_analysis rover0)
    (in rover1 waypoint10)
    (available rover1)
    (store_of rover1store rover1)
    (empty rover1store)
    (equipped_for_soil_analysis rover1)
    (in rover2 waypoint8)
    (available rover2)
    (store_of rover2store rover2)
    (empty rover2store)
    (equipped_for_soil_analysis rover2)
    (equipped_for_rock_analysis rover2)
    (equipped_for_imaging rover2)
    (in rover3 waypoint2)
    (available rover3)
    (store_of rover3store rover3)
    (empty rover3store)
    (equipped_for_soil_analysis rover3)
    (equipped_for_imaging rover3)
    (can_traverse rover0 waypoint0 waypoint8)
    (can_traverse rover0 waypoint1 waypoint10)
    (can_traverse rover0 waypoint2 waypoint5)
    (can_traverse rover0 waypoint2 waypoint6)
    (can_traverse rover0 waypoint3 waypoint6)
    (can_traverse rover0 waypoint4 waypoint7)
    (can_traverse rover0 waypoint5 waypoint2)
    (can_traverse rover0 waypoint5 waypoint4)
    (can_traverse rover0 waypoint5 waypoint6)
    (can_traverse rover0 waypoint5 waypoint8)
    (can_traverse rover0 waypoint6 waypoint3)
    (can_traverse rover0 waypoint6 waypoint7)
    (can_traverse rover0 waypoint6 waypoint9)
    (can_traverse rover0 waypoint7 waypoint4)
    (can_traverse rover0 waypoint7 waypoint6)
    (can_traverse rover0 waypoint7 waypoint8)
    (can_traverse rover0 waypoint7 waypoint10)
    (can_traverse rover0 waypoint8 waypoint0)
    (can_traverse rover0 waypoint8 waypoint5)
    (can_traverse rover0 waypoint8 waypoint7)
    (can_traverse rover0 waypoint8 waypoint10)
    (can_traverse rover0 waypoint9 waypoint6)
    (can_traverse rover0 waypoint10 waypoint1)
    (can_traverse rover0 waypoint10 waypoint7)
    (can_traverse rover1 waypoint0 waypoint8)
    (can_traverse rover1 waypoint1 waypoint6)
    (can_traverse rover1 waypoint1 waypoint10)
    (can_traverse rover1 waypoint2 waypoint6)
    (can_traverse rover1 waypoint3 waypoint6)
    (can_traverse rover1 waypoint4 waypoint5)
    (can_traverse rover1 waypoint5 waypoint2)
    (can_traverse rover1 waypoint5 waypoint4)
    (can_traverse rover1 waypoint5 waypoint6)
    (can_traverse rover1 waypoint5 waypoint8)
    (can_traverse rover1 waypoint6 waypoint1)
    (can_traverse rover1 waypoint6 waypoint2)
    (can_traverse rover1 waypoint6 waypoint3)
    (can_traverse rover1 waypoint6 waypoint5)
    (can_traverse rover1 waypoint6 waypoint7)
    (can_traverse rover1 waypoint6 waypoint9)
    (can_traverse rover1 waypoint7 waypoint6)
    (can_traverse rover1 waypoint7 waypoint8)
    (can_traverse rover1 waypoint7 waypoint10)
    (can_traverse rover1 waypoint8 waypoint0)
    (can_traverse rover1 waypoint8 waypoint10)
    (can_traverse rover1 waypoint9 waypoint6)
    (can_traverse rover1 waypoint10 waypoint1)
    (can_traverse rover1 waypoint10 waypoint8)
    (can_traverse rover2 waypoint0 waypoint8)
    (can_traverse rover2 waypoint1 waypoint10)
    (can_traverse rover2 waypoint2 waypoint6)
    (can_traverse rover2 waypoint2 waypoint10)
    (can_traverse rover2 waypoint3 waypoint6)
    (can_traverse rover2 waypoint4 waypoint7)
    (can_traverse rover2 waypoint4 waypoint10)
    (can_traverse rover2 waypoint5 waypoint8)
    (can_traverse rover2 waypoint6 waypoint1)
    (can_traverse rover2 waypoint6 waypoint2)
    (can_traverse rover2 waypoint6 waypoint3)
    (can_traverse rover2 waypoint6 waypoint7)
    (can_traverse rover2 waypoint6 waypoint9)
    (can_traverse rover2 waypoint7 waypoint4)
    (can_traverse rover2 waypoint7 waypoint8)
    (can_traverse rover2 waypoint7 waypoint10)
    (can_traverse rover2 waypoint8 waypoint0)
    (can_traverse rover2 waypoint8 waypoint5)
    (can_traverse rover2 waypoint8 waypoint7)
    (can_traverse rover2 waypoint8 waypoint10)
    (can_traverse rover2 waypoint9 waypoint6)
    (can_traverse rover2 waypoint10 waypoint1)
    (can_traverse rover2 waypoint10 waypoint2)
    (can_traverse rover2 waypoint10 waypoint4)
    (can_traverse rover2 waypoint10 waypoint8)
    (can_traverse rover3 waypoint0 waypoint8)
    (can_traverse rover3 waypoint1 waypoint10)
    (can_traverse rover3 waypoint2 waypoint5)
    (can_traverse rover3 waypoint2 waypoint6)
    (can_traverse rover3 waypoint2 waypoint10)
    (can_traverse rover3 waypoint3 waypoint6)
    (can_traverse rover3 waypoint4 waypoint9)
    (can_traverse rover3 waypoint4 waypoint10)
    (can_traverse rover3 waypoint5 waypoint2)
    (can_traverse rover3 waypoint5 waypoint8)
    (can_traverse rover3 waypoint6 waypoint2)
    (can_traverse rover3 waypoint6 waypoint3)
    (can_traverse rover3 waypoint6 waypoint5)
    (can_traverse rover3 waypoint6 waypoint7)
    (can_traverse rover3 waypoint6 waypoint9)
    (can_traverse rover3 waypoint7 waypoint6)
    (can_traverse rover3 waypoint7 waypoint10)
    (can_traverse rover3 waypoint8 waypoint0)
    (can_traverse rover3 waypoint8 waypoint5)
    (can_traverse rover3 waypoint8 waypoint10)
    (can_traverse rover3 waypoint9 waypoint4)
    (can_traverse rover3 waypoint9 waypoint6)
    (can_traverse rover3 waypoint10 waypoint1)
    (can_traverse rover3 waypoint10 waypoint2)
    (can_traverse rover3 waypoint10 waypoint4)
    (can_traverse rover3 waypoint10 waypoint7)
    (can_traverse rover3 waypoint10 waypoint8)
    (on_board camera0 rover3)
    (calibration_target camera0 objective2)
    (supports camera0 high_res)
    (supports camera0 low_res)
    (on_board camera1 rover2)
    (calibration_target camera1 objective7)
    (supports camera1 high_res)
    (supports camera1 low_res)
    (on_board camera2 rover2)
    (calibration_target camera2 objective3)
    (supports camera2 colour)
    (supports camera2 high_res)
    (supports camera2 low_res)
    (visible_from objective0 waypoint6)
    (visible_from objective1 waypoint4)
    (visible_from objective1 waypoint9)
    (visible_from objective2 waypoint6)
    (visible_from objective2 waypoint0)
    (visible_from objective3 waypoint7)
    (visible_from objective3 waypoint8)
    (visible_from objective4 waypoint4)
    (visible_from objective5 waypoint10)
    (visible_from objective5 waypoint7)
    (visible_from objective5 waypoint4)
    (visible_from objective6 waypoint10)
    (visible_from objective7 waypoint1)
    (= (recharges) 0)
    (= (energy rover0) 105)
    (= (energy rover1) 114)
    (= (energy rover2) 116)
    (= (energy rover3) 104)
)

(:goal (and
    (communicated_soil_data waypoint7)
    (communicated_soil_data waypoint8)
    (communicated_soil_data waypoint4)
    (communicated_soil_data waypoint0)
    (communicated_soil_data waypoint6)
    (communicated_soil_data waypoint1)
    (communicated_soil_data waypoint9)
    (communicated_soil_data waypoint5)
    (communicated_rock_data waypoint9)
    (communicated_rock_data waypoint8)
    (communicated_image_data objective7 high_res)
    (communicated_image_data objective2 high_res)
))

(:metric minimize (recharges))
)
