(define (problem roverprob-7) (:domain rover)
(:objects
    general - lander
    colour high_res low_res - mode
    rover0 rover1 rover2 rover3 - rover
    rover0store rover1store rover2store rover3store - store
    waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 waypoint7 waypoint8 waypoint9 waypoint10 waypoint11 waypoint12 waypoint13 waypoint14 waypoint15 waypoint16 waypoint17 waypoint18 waypoint19 - waypoint
    camera0 camera1 camera2 camera3 camera4 camera5 camera6 camera7 - camera
    objective0 objective1 objective2 objective3 objective4 - objective
)
(:init
    (visible waypoint0 waypoint1)
    (visible waypoint0 waypoint18)
    (visible waypoint1 waypoint0)
    (visible waypoint1 waypoint18)
    (visible waypoint2 waypoint4)
    (visible waypoint2 waypoint6)
    (visible waypoint2 waypoint17)
    (visible waypoint2 waypoint18)
    (visible waypoint3 waypoint10)
    (visible waypoint3 waypoint19)
    (visible waypoint4 waypoint2)
    (visible waypoint4 waypoint7)
    (visible waypoint4 waypoint8)
    (visible waypoint4 waypoint9)
    (visible waypoint4 waypoint12)
    (visible waypoint4 waypoint13)
    (visible waypoint5 waypoint6)
    (visible waypoint5 waypoint17)
    (visible waypoint6 waypoint2)
    (visible waypoint6 waypoint5)
    (visible waypoint6 waypoint7)
    (visible waypoint6 waypoint17)
    (visible waypoint7 waypoint6)
    (visible waypoint7 waypoint8)
    (visible waypoint7 waypoint12)
    (visible waypoint8 waypoint4)
    (visible waypoint8 waypoint7)
    (visible waypoint8 waypoint11)
    (visible waypoint8 waypoint12)
    (visible waypoint9 waypoint4)
    (visible waypoint9 waypoint12)
    (visible waypoint9 waypoint18)
    (visible waypoint10 waypoint3)
    (visible waypoint10 waypoint18)
    (visible waypoint10 waypoint19)
    (visible waypoint11 waypoint8)
    (visible waypoint11 waypoint13)
    (visible waypoint11 waypoint15)
    (visible waypoint11 waypoint19)
    (visible waypoint12 waypoint4)
    (visible waypoint12 waypoint7)
    (visible waypoint12 waypoint8)
    (visible waypoint12 waypoint9)
    (visible waypoint13 waypoint4)
    (visible waypoint13 waypoint11)
    (visible waypoint13 waypoint15)
    (visible waypoint13 waypoint16)
    (visible waypoint14 waypoint15)
    (visible waypoint14 waypoint16)
    (visible waypoint15 waypoint1)
    (visible waypoint15 waypoint11)
    (visible waypoint15 waypoint13)
    (visible waypoint15 waypoint14)
    (visible waypoint15 waypoint18)
    (visible waypoint16 waypoint14)
    (visible waypoint16 waypoint18)
    (visible waypoint17 waypoint2)
    (visible waypoint17 waypoint5)
    (visible waypoint17 waypoint6)
    (visible waypoint18 waypoint0)
    (visible waypoint18 waypoint1)
    (visible waypoint18 waypoint2)
    (visible waypoint18 waypoint9)
    (visible waypoint18 waypoint10)
    (visible waypoint18 waypoint15)
    (visible waypoint18 waypoint16)
    (visible waypoint19 waypoint3)
    (visible waypoint19 waypoint10)
    (visible waypoint19 waypoint11)
    (at_soil_sample waypoint18)
    (at_soil_sample waypoint10)
    (at_soil_sample waypoint14)
    (at_soil_sample waypoint9)
    (at_soil_sample waypoint15)
    (at_soil_sample waypoint7)
    (at_soil_sample waypoint16)
    (at_soil_sample waypoint3)
    (at_soil_sample waypoint13)
    (at_soil_sample waypoint5)
    (at_soil_sample waypoint0)
    (at_rock_sample waypoint16)
    (at_rock_sample waypoint0)
    (at_rock_sample waypoint6)
    (at_rock_sample waypoint2)
    (at_rock_sample waypoint1)
    (at_rock_sample waypoint15)
    (at_rock_sample waypoint19)
    (at_rock_sample waypoint8)
    (at_rock_sample waypoint17)
    (at_rock_sample waypoint13)
    (at_rock_sample waypoint5)
    (at_rock_sample waypoint11)
    (at_rock_sample waypoint18)
    (at_rock_sample waypoint10)
    (at_rock_sample waypoint4)
    (at_rock_sample waypoint7)
    (at_rock_sample waypoint12)
    (at_rock_sample waypoint3)
    (in_sun waypoint12)
    (in_sun waypoint10)
    (in_sun waypoint19)
    (in_sun waypoint13)
    (in_sun waypoint8)
    (in_sun waypoint16)
    (in_sun waypoint14)
    (in_sun waypoint3)
    (in_sun waypoint1)
    (in_sun waypoint18)
    (at_lander general waypoint10)
    (channel_free general)
    (in rover0 waypoint17)
    (available rover0)
    (store_of rover0store rover0)
    (empty rover0store)
    (equipped_for_soil_analysis rover0)
    (equipped_for_rock_analysis rover0)
    (equipped_for_imaging rover0)
    (in rover1 waypoint19)
    (available rover1)
    (store_of rover1store rover1)
    (empty rover1store)
    (equipped_for_rock_analysis rover1)
    (equipped_for_imaging rover1)
    (in rover2 waypoint9)
    (available rover2)
    (store_of rover2store rover2)
    (empty rover2store)
    (equipped_for_rock_analysis rover2)
    (equipped_for_imaging rover2)
    (in rover3 waypoint6)
    (available rover3)
    (store_of rover3store rover3)
    (empty rover3store)
    (equipped_for_soil_analysis rover3)
    (can_traverse rover0 waypoint0 waypoint18)
    (can_traverse rover0 waypoint1 waypoint15)
    (can_traverse rover0 waypoint2 waypoint4)
    (can_traverse rover0 waypoint2 waypoint6)
    (can_traverse rover0 waypoint2 waypoint17)
    (can_traverse rover0 waypoint3 waypoint10)
    (can_traverse rover0 waypoint3 waypoint19)
    (can_traverse rover0 waypoint4 waypoint2)
    (can_traverse rover0 waypoint4 waypoint7)
    (can_traverse rover0 waypoint4 waypoint9)
    (can_traverse rover0 waypoint4 waypoint12)
    (can_traverse rover0 waypoint4 waypoint13)
    (can_traverse rover0 waypoint5 waypoint6)
    (can_traverse rover0 waypoint6 waypoint2)
    (can_traverse rover0 waypoint6 waypoint5)
    (can_traverse rover0 waypoint7 waypoint4)
    (can_traverse rover0 waypoint8 waypoint7)
    (can_traverse rover0 waypoint8 waypoint11)
    (can_traverse rover0 waypoint9 waypoint4)
    (can_traverse rover0 waypoint9 waypoint12)
    (can_traverse rover0 waypoint9 waypoint18)
    (can_traverse rover0 waypoint10 waypoint18)
    (can_traverse rover0 waypoint10 waypoint19)
    (can_traverse rover0 waypoint11 waypoint8)
    (can_traverse rover0 waypoint11 waypoint13)
    (can_traverse rover0 waypoint11 waypoint15)
    (can_traverse rover0 waypoint11 waypoint19)
    (can_traverse rover0 waypoint12 waypoint4)
    (can_traverse rover0 waypoint12 waypoint9)
    (can_traverse rover0 waypoint13 waypoint4)
    (can_traverse rover0 waypoint13 waypoint11)
    (can_traverse rover0 waypoint13 waypoint15)
    (can_traverse rover0 waypoint13 waypoint16)
    (can_traverse rover0 waypoint14 waypoint15)
    (can_traverse rover0 waypoint15 waypoint1)
    (can_traverse rover0 waypoint15 waypoint11)
    (can_traverse rover0 waypoint15 waypoint13)
    (can_traverse rover0 waypoint15 waypoint14)
    (can_traverse rover0 waypoint16 waypoint13)
    (can_traverse rover0 waypoint16 waypoint14)
    (can_traverse rover0 waypoint17 waypoint2)
    (can_traverse rover0 waypoint18 waypoint0)
    (can_traverse rover0 waypoint18 waypoint1)
    (can_traverse rover0 waypoint18 waypoint9)
    (can_traverse rover0 waypoint18 waypoint10)
    (can_traverse rover0 waypoint18 waypoint15)
    (can_traverse rover0 waypoint19 waypoint3)
    (can_traverse rover0 waypoint19 waypoint11)
    (can_traverse rover1 waypoint0 waypoint1)
    (can_traverse rover1 waypoint0 waypoint18)
    (can_traverse rover1 waypoint1 waypoint0)
    (can_traverse rover1 waypoint1 waypoint18)
    (can_traverse rover1 waypoint2 waypoint4)
    (can_traverse rover1 waypoint2 waypoint17)
    (can_traverse rover1 waypoint2 waypoint18)
    (can_traverse rover1 waypoint3 waypoint10)
    (can_traverse rover1 waypoint3 waypoint19)
    (can_traverse rover1 waypoint4 waypoint2)
    (can_traverse rover1 waypoint4 waypoint8)
    (can_traverse rover1 waypoint4 waypoint9)
    (can_traverse rover1 waypoint4 waypoint13)
    (can_traverse rover1 waypoint5 waypoint17)
    (can_traverse rover1 waypoint6 waypoint7)
    (can_traverse rover1 waypoint6 waypoint17)
    (can_traverse rover1 waypoint7 waypoint6)
    (can_traverse rover1 waypoint7 waypoint8)
    (can_traverse rover1 waypoint7 waypoint12)
    (can_traverse rover1 waypoint8 waypoint4)
    (can_traverse rover1 waypoint8 waypoint11)
    (can_traverse rover1 waypoint9 waypoint4)
    (can_traverse rover1 waypoint9 waypoint12)
    (can_traverse rover1 waypoint9 waypoint18)
    (can_traverse rover1 waypoint10 waypoint18)
    (can_traverse rover1 waypoint10 waypoint19)
    (can_traverse rover1 waypoint11 waypoint8)
    (can_traverse rover1 waypoint11 waypoint19)
    (can_traverse rover1 waypoint12 waypoint4)
    (can_traverse rover1 waypoint12 waypoint7)
    (can_traverse rover1 waypoint12 waypoint9)
    (can_traverse rover1 waypoint13 waypoint11)
    (can_traverse rover1 waypoint13 waypoint15)
    (can_traverse rover1 waypoint13 waypoint16)
    (can_traverse rover1 waypoint14 waypoint16)
    (can_traverse rover1 waypoint15 waypoint1)
    (can_traverse rover1 waypoint15 waypoint11)
    (can_traverse rover1 waypoint15 waypoint13)
    (can_traverse rover1 waypoint15 waypoint14)
    (can_traverse rover1 waypoint15 waypoint18)
    (can_traverse rover1 waypoint16 waypoint13)
    (can_traverse rover1 waypoint16 waypoint14)
    (can_traverse rover1 waypoint17 waypoint2)
    (can_traverse rover1 waypoint17 waypoint5)
    (can_traverse rover1 waypoint17 waypoint6)
    (can_traverse rover1 waypoint18 waypoint1)
    (can_traverse rover1 waypoint18 waypoint2)
    (can_traverse rover1 waypoint18 waypoint9)
    (can_traverse rover1 waypoint18 waypoint10)
    (can_traverse rover1 waypoint18 waypoint15)
    (can_traverse rover1 waypoint19 waypoint3)
    (can_traverse rover1 waypoint19 waypoint11)
    (can_traverse rover2 waypoint0 waypoint1)
    (can_traverse rover2 waypoint1 waypoint0)
    (can_traverse rover2 waypoint1 waypoint15)
    (can_traverse rover2 waypoint2 waypoint4)
    (can_traverse rover2 waypoint2 waypoint17)
    (can_traverse rover2 waypoint2 waypoint18)
    (can_traverse rover2 waypoint3 waypoint10)
    (can_traverse rover2 waypoint4 waypoint2)
    (can_traverse rover2 waypoint4 waypoint7)
    (can_traverse rover2 waypoint4 waypoint8)
    (can_traverse rover2 waypoint4 waypoint9)
    (can_traverse rover2 waypoint4 waypoint12)
    (can_traverse rover2 waypoint5 waypoint6)
    (can_traverse rover2 waypoint5 waypoint17)
    (can_traverse rover2 waypoint6 waypoint5)
    (can_traverse rover2 waypoint6 waypoint7)
    (can_traverse rover2 waypoint6 waypoint17)
    (can_traverse rover2 waypoint7 waypoint4)
    (can_traverse rover2 waypoint7 waypoint6)
    (can_traverse rover2 waypoint7 waypoint12)
    (can_traverse rover2 waypoint8 waypoint4)
    (can_traverse rover2 waypoint8 waypoint7)
    (can_traverse rover2 waypoint9 waypoint4)
    (can_traverse rover2 waypoint10 waypoint3)
    (can_traverse rover2 waypoint10 waypoint18)
    (can_traverse rover2 waypoint10 waypoint19)
    (can_traverse rover2 waypoint11 waypoint8)
    (can_traverse rover2 waypoint11 waypoint15)
    (can_traverse rover2 waypoint12 waypoint4)
    (can_traverse rover2 waypoint12 waypoint8)
    (can_traverse rover2 waypoint13 waypoint11)
    (can_traverse rover2 waypoint13 waypoint16)
    (can_traverse rover2 waypoint14 waypoint15)
    (can_traverse rover2 waypoint14 waypoint16)
    (can_traverse rover2 waypoint15 waypoint1)
    (can_traverse rover2 waypoint15 waypoint11)
    (can_traverse rover2 waypoint15 waypoint14)
    (can_traverse rover2 waypoint15 waypoint18)
    (can_traverse rover2 waypoint16 waypoint13)
    (can_traverse rover2 waypoint16 waypoint14)
    (can_traverse rover2 waypoint16 waypoint18)
    (can_traverse rover2 waypoint17 waypoint2)
    (can_traverse rover2 waypoint18 waypoint2)
    (can_traverse rover2 waypoint18 waypoint9)
    (can_traverse rover2 waypoint18 waypoint10)
    (can_traverse rover2 waypoint18 waypoint15)
    (can_traverse rover2 waypoint18 waypoint16)
    (can_traverse rover2 waypoint19 waypoint10)
    (can_traverse rover3 waypoint0 waypoint1)
    (can_traverse rover3 waypoint0 waypoint18)
    (can_traverse rover3 waypoint1 waypoint0)
    (can_traverse rover3 waypoint2 waypoint4)
    (can_traverse rover3 waypoint2 waypoint17)
    (can_traverse rover3 waypoint3 waypoint19)
    (can_traverse rover3 waypoint4 waypoint2)
    (can_traverse rover3 waypoint4 waypoint7)
    (can_traverse rover3 waypoint4 waypoint9)
    (can_traverse rover3 waypoint4 waypoint12)
    (can_traverse rover3 waypoint4 waypoint13)
    (can_traverse rover3 waypoint5 waypoint6)
    (can_traverse rover3 waypoint5 waypoint17)
    (can_traverse rover3 waypoint6 waypoint5)
    (can_traverse rover3 waypoint6 waypoint17)
    (can_traverse rover3 waypoint7 waypoint4)
    (can_traverse rover3 waypoint7 waypoint8)
    (can_traverse rover3 waypoint8 waypoint7)
    (can_traverse rover3 waypoint8 waypoint12)
    (can_traverse rover3 waypoint9 waypoint12)
    (can_traverse rover3 waypoint9 waypoint18)
    (can_traverse rover3 waypoint10 waypoint18)
    (can_traverse rover3 waypoint11 waypoint13)
    (can_traverse rover3 waypoint11 waypoint19)
    (can_traverse rover3 waypoint12 waypoint4)
    (can_traverse rover3 waypoint12 waypoint8)
    (can_traverse rover3 waypoint12 waypoint9)
    (can_traverse rover3 waypoint13 waypoint4)
    (can_traverse rover3 waypoint13 waypoint11)
    (can_traverse rover3 waypoint13 waypoint15)
    (can_traverse rover3 waypoint13 waypoint16)
    (can_traverse rover3 waypoint14 waypoint15)
    (can_traverse rover3 waypoint14 waypoint16)
    (can_traverse rover3 waypoint15 waypoint13)
    (can_traverse rover3 waypoint15 waypoint18)
    (can_traverse rover3 waypoint16 waypoint13)
    (can_traverse rover3 waypoint16 waypoint14)
    (can_traverse rover3 waypoint17 waypoint2)
    (can_traverse rover3 waypoint17 waypoint5)
    (can_traverse rover3 waypoint17 waypoint6)
    (can_traverse rover3 waypoint18 waypoint0)
    (can_traverse rover3 waypoint18 waypoint1)
    (can_traverse rover3 waypoint18 waypoint2)
    (can_traverse rover3 waypoint18 waypoint9)
    (can_traverse rover3 waypoint18 waypoint10)
    (can_traverse rover3 waypoint19 waypoint3)
    (can_traverse rover3 waypoint19 waypoint11)
    (on_board camera0 rover0)
    (calibration_target camera0 objective3)
    (supports camera0 colour)
    (supports camera0 high_res)
    (supports camera0 low_res)
    (on_board camera1 rover2)
    (calibration_target camera1 objective2)
    (supports camera1 colour)
    (supports camera1 low_res)
    (on_board camera2 rover0)
    (calibration_target camera2 objective1)
    (supports camera2 high_res)
    (supports camera2 low_res)
    (on_board camera3 rover2)
    (calibration_target camera3 objective3)
    (supports camera3 colour)
    (supports camera3 high_res)
    (supports camera3 low_res)
    (on_board camera4 rover2)
    (calibration_target camera4 objective4)
    (supports camera4 high_res)
    (supports camera4 low_res)
    (on_board camera5 rover0)
    (calibration_target camera5 objective2)
    (supports camera5 colour)
    (supports camera5 high_res)
    (supports camera5 low_res)
    (on_board camera6 rover2)
    (calibration_target camera6 objective4)
    (supports camera6 colour)
    (supports camera6 low_res)
    (on_board camera7 rover1)
    (calibration_target camera7 objective0)
    (supports camera7 colour)
    (supports camera7 low_res)
    (visible_from objective0 waypoint19)
    (visible_from objective1 waypoint17)
    (visible_from objective1 waypoint12)
    (visible_from objective2 waypoint12)
    (visible_from objective2 waypoint15)
    (visible_from objective3 waypoint2)
    (visible_from objective4 waypoint15)
    (visible_from objective4 waypoint3)
    (= (recharges) 0)
    (= (energy rover0) 103)
    (= (energy rover1) 115)
    (= (energy rover2) 77)
    (= (energy rover3) 112)
)

(:goal (and
    (communicated_soil_data waypoint9)
    (communicated_soil_data waypoint13)
    (communicated_soil_data waypoint14)
    (communicated_soil_data waypoint10)
    (communicated_soil_data waypoint18)
    (communicated_rock_data waypoint6)
    (communicated_rock_data waypoint13)
    (communicated_rock_data waypoint8)
    (communicated_rock_data waypoint18)
    (communicated_image_data objective4 colour)
    (communicated_image_data objective0 colour)
    (communicated_image_data objective2 colour)
    (communicated_image_data objective2 high_res)
    (communicated_image_data objective4 high_res)
))

(:metric minimize (recharges))
)
