(define (problem roverprob-0) (:domain rover)
(:objects
    general - lander
    colour high_res low_res - mode
    rover0 rover1 rover2 - rover
    rover0store rover1store rover2store - store
    waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 waypoint7 waypoint8 waypoint9 waypoint10 waypoint11 waypoint12 waypoint13 waypoint14 waypoint15 - waypoint
    camera0 camera1 camera2 camera3 - camera
    objective0 objective1 objective2 objective3 objective4 objective5 - objective
)
(:init
    (visible waypoint0 waypoint3)
    (visible waypoint0 waypoint13)
    (visible waypoint0 waypoint14)
    (visible waypoint1 waypoint4)
    (visible waypoint1 waypoint5)
    (visible waypoint1 waypoint10)
    (visible waypoint1 waypoint13)
    (visible waypoint1 waypoint15)
    (visible waypoint2 waypoint12)
    (visible waypoint3 waypoint0)
    (visible waypoint3 waypoint6)
    (visible waypoint3 waypoint7)
    (visible waypoint3 waypoint8)
    (visible waypoint4 waypoint1)
    (visible waypoint5 waypoint1)
    (visible waypoint5 waypoint7)
    (visible waypoint5 waypoint9)
    (visible waypoint5 waypoint10)
    (visible waypoint5 waypoint13)
    (visible waypoint6 waypoint3)
    (visible waypoint6 waypoint13)
    (visible waypoint6 waypoint15)
    (visible waypoint7 waypoint3)
    (visible waypoint7 waypoint5)
    (visible waypoint8 waypoint3)
    (visible waypoint8 waypoint10)
    (visible waypoint8 waypoint11)
    (visible waypoint9 waypoint5)
    (visible waypoint9 waypoint12)
    (visible waypoint10 waypoint0)
    (visible waypoint10 waypoint1)
    (visible waypoint10 waypoint5)
    (visible waypoint10 waypoint8)
    (visible waypoint10 waypoint15)
    (visible waypoint11 waypoint8)
    (visible waypoint12 waypoint2)
    (visible waypoint12 waypoint9)
    (visible waypoint12 waypoint13)
    (visible waypoint13 waypoint0)
    (visible waypoint13 waypoint1)
    (visible waypoint13 waypoint5)
    (visible waypoint13 waypoint6)
    (visible waypoint13 waypoint12)
    (visible waypoint13 waypoint15)
    (visible waypoint14 waypoint0)
    (visible waypoint15 waypoint1)
    (visible waypoint15 waypoint6)
    (visible waypoint15 waypoint10)
    (visible waypoint15 waypoint13)
    (at_soil_sample waypoint2)
    (at_soil_sample waypoint3)
    (at_soil_sample waypoint10)
    (at_soil_sample waypoint9)
    (at_soil_sample waypoint12)
    (at_soil_sample waypoint4)
    (at_soil_sample waypoint13)
    (at_rock_sample waypoint9)
    (at_rock_sample waypoint2)
    (at_rock_sample waypoint10)
    (at_rock_sample waypoint1)
    (at_rock_sample waypoint6)
    (at_rock_sample waypoint8)
    (at_rock_sample waypoint11)
    (at_rock_sample waypoint0)
    (at_rock_sample waypoint3)
    (at_rock_sample waypoint4)
    (at_rock_sample waypoint5)
    (at_rock_sample waypoint15)
    (at_rock_sample waypoint7)
    (at_rock_sample waypoint12)
    (at_rock_sample waypoint13)
    (at_rock_sample waypoint14)
    (in_sun waypoint14)
    (in_sun waypoint9)
    (in_sun waypoint1)
    (at_lander general waypoint1)
    (channel_free general)
    (in rover0 waypoint0)
    (available rover0)
    (store_of rover0store rover0)
    (empty rover0store)
    (equipped_for_soil_analysis rover0)
    (equipped_for_rock_analysis rover0)
    (equipped_for_imaging rover0)
    (in rover1 waypoint13)
    (available rover1)
    (store_of rover1store rover1)
    (empty rover1store)
    (equipped_for_soil_analysis rover1)
    (equipped_for_rock_analysis rover1)
    (in rover2 waypoint15)
    (available rover2)
    (store_of rover2store rover2)
    (empty rover2store)
    (equipped_for_soil_analysis rover2)
    (equipped_for_rock_analysis rover2)
    (equipped_for_imaging rover2)
    (can_traverse rover0 waypoint0 waypoint10)
    (can_traverse rover0 waypoint0 waypoint14)
    (can_traverse rover0 waypoint1 waypoint4)
    (can_traverse rover0 waypoint1 waypoint5)
    (can_traverse rover0 waypoint2 waypoint12)
    (can_traverse rover0 waypoint3 waypoint6)
    (can_traverse rover0 waypoint3 waypoint7)
    (can_traverse rover0 waypoint3 waypoint8)
    (can_traverse rover0 waypoint4 waypoint1)
    (can_traverse rover0 waypoint5 waypoint1)
    (can_traverse rover0 waypoint5 waypoint7)
    (can_traverse rover0 waypoint5 waypoint9)
    (can_traverse rover0 waypoint5 waypoint10)
    (can_traverse rover0 waypoint5 waypoint13)
    (can_traverse rover0 waypoint6 waypoint3)
    (can_traverse rover0 waypoint6 waypoint13)
    (can_traverse rover0 waypoint7 waypoint3)
    (can_traverse rover0 waypoint7 waypoint5)
    (can_traverse rover0 waypoint8 waypoint3)
    (can_traverse rover0 waypoint8 waypoint11)
    (can_traverse rover0 waypoint9 waypoint5)
    (can_traverse rover0 waypoint10 waypoint0)
    (can_traverse rover0 waypoint10 waypoint5)
    (can_traverse rover0 waypoint10 waypoint15)
    (can_traverse rover0 waypoint11 waypoint8)
    (can_traverse rover0 waypoint12 waypoint2)
    (can_traverse rover0 waypoint12 waypoint13)
    (can_traverse rover0 waypoint13 waypoint0)
    (can_traverse rover0 waypoint13 waypoint1)
    (can_traverse rover0 waypoint13 waypoint6)
    (can_traverse rover0 waypoint13 waypoint12)
    (can_traverse rover0 waypoint13 waypoint15)
    (can_traverse rover0 waypoint14 waypoint0)
    (can_traverse rover0 waypoint15 waypoint6)
    (can_traverse rover0 waypoint15 waypoint10)
    (can_traverse rover0 waypoint15 waypoint13)
    (can_traverse rover1 waypoint0 waypoint3)
    (can_traverse rover1 waypoint0 waypoint10)
    (can_traverse rover1 waypoint0 waypoint13)
    (can_traverse rover1 waypoint0 waypoint14)
    (can_traverse rover1 waypoint1 waypoint4)
    (can_traverse rover1 waypoint1 waypoint5)
    (can_traverse rover1 waypoint1 waypoint10)
    (can_traverse rover1 waypoint2 waypoint12)
    (can_traverse rover1 waypoint3 waypoint0)
    (can_traverse rover1 waypoint3 waypoint7)
    (can_traverse rover1 waypoint3 waypoint8)
    (can_traverse rover1 waypoint4 waypoint1)
    (can_traverse rover1 waypoint5 waypoint1)
    (can_traverse rover1 waypoint5 waypoint7)
    (can_traverse rover1 waypoint5 waypoint13)
    (can_traverse rover1 waypoint6 waypoint3)
    (can_traverse rover1 waypoint6 waypoint13)
    (can_traverse rover1 waypoint6 waypoint15)
    (can_traverse rover1 waypoint7 waypoint3)
    (can_traverse rover1 waypoint7 waypoint5)
    (can_traverse rover1 waypoint8 waypoint3)
    (can_traverse rover1 waypoint8 waypoint11)
    (can_traverse rover1 waypoint9 waypoint12)
    (can_traverse rover1 waypoint10 waypoint0)
    (can_traverse rover1 waypoint10 waypoint1)
    (can_traverse rover1 waypoint10 waypoint5)
    (can_traverse rover1 waypoint10 waypoint8)
    (can_traverse rover1 waypoint11 waypoint8)
    (can_traverse rover1 waypoint12 waypoint2)
    (can_traverse rover1 waypoint12 waypoint9)
    (can_traverse rover1 waypoint12 waypoint13)
    (can_traverse rover1 waypoint13 waypoint0)
    (can_traverse rover1 waypoint13 waypoint5)
    (can_traverse rover1 waypoint13 waypoint6)
    (can_traverse rover1 waypoint13 waypoint12)
    (can_traverse rover1 waypoint14 waypoint0)
    (can_traverse rover1 waypoint15 waypoint6)
    (can_traverse rover1 waypoint15 waypoint10)
    (can_traverse rover2 waypoint0 waypoint10)
    (can_traverse rover2 waypoint0 waypoint13)
    (can_traverse rover2 waypoint0 waypoint14)
    (can_traverse rover2 waypoint1 waypoint4)
    (can_traverse rover2 waypoint1 waypoint5)
    (can_traverse rover2 waypoint1 waypoint15)
    (can_traverse rover2 waypoint2 waypoint12)
    (can_traverse rover2 waypoint3 waypoint0)
    (can_traverse rover2 waypoint3 waypoint6)
    (can_traverse rover2 waypoint3 waypoint7)
    (can_traverse rover2 waypoint3 waypoint8)
    (can_traverse rover2 waypoint4 waypoint1)
    (can_traverse rover2 waypoint5 waypoint1)
    (can_traverse rover2 waypoint5 waypoint7)
    (can_traverse rover2 waypoint5 waypoint9)
    (can_traverse rover2 waypoint5 waypoint10)
    (can_traverse rover2 waypoint5 waypoint13)
    (can_traverse rover2 waypoint6 waypoint3)
    (can_traverse rover2 waypoint6 waypoint13)
    (can_traverse rover2 waypoint6 waypoint15)
    (can_traverse rover2 waypoint7 waypoint3)
    (can_traverse rover2 waypoint7 waypoint5)
    (can_traverse rover2 waypoint8 waypoint10)
    (can_traverse rover2 waypoint8 waypoint11)
    (can_traverse rover2 waypoint9 waypoint5)
    (can_traverse rover2 waypoint10 waypoint0)
    (can_traverse rover2 waypoint10 waypoint8)
    (can_traverse rover2 waypoint10 waypoint15)
    (can_traverse rover2 waypoint11 waypoint8)
    (can_traverse rover2 waypoint12 waypoint2)
    (can_traverse rover2 waypoint12 waypoint13)
    (can_traverse rover2 waypoint13 waypoint0)
    (can_traverse rover2 waypoint13 waypoint5)
    (can_traverse rover2 waypoint13 waypoint6)
    (can_traverse rover2 waypoint13 waypoint12)
    (can_traverse rover2 waypoint14 waypoint0)
    (can_traverse rover2 waypoint15 waypoint1)
    (can_traverse rover2 waypoint15 waypoint10)
    (can_traverse rover2 waypoint15 waypoint13)
    (on_board camera0 rover2)
    (calibration_target camera0 objective4)
    (supports camera0 high_res)
    (supports camera0 low_res)
    (on_board camera1 rover0)
    (calibration_target camera1 objective3)
    (supports camera1 colour)
    (supports camera1 high_res)
    (on_board camera2 rover0)
    (calibration_target camera2 objective2)
    (supports camera2 high_res)
    (supports camera2 low_res)
    (on_board camera3 rover2)
    (calibration_target camera3 objective0)
    (supports camera3 low_res)
    (visible_from objective0 waypoint10)
    (visible_from objective1 waypoint13)
    (visible_from objective1 waypoint2)
    (visible_from objective1 waypoint14)
    (visible_from objective2 waypoint1)
    (visible_from objective2 waypoint8)
    (visible_from objective2 waypoint5)
    (visible_from objective3 waypoint15)
    (visible_from objective3 waypoint10)
    (visible_from objective4 waypoint14)
    (visible_from objective5 waypoint2)
    (visible_from objective5 waypoint1)
    (= (recharges) 0)
    (= (energy rover0) 94)
    (= (energy rover1) 102)
    (= (energy rover2) 91)
)

(:goal (and
    (communicated_soil_data waypoint13)
    (communicated_soil_data waypoint2)
    (communicated_soil_data waypoint9)
    (communicated_soil_data waypoint3)
    (communicated_soil_data waypoint12)
    (communicated_soil_data waypoint4)
    (communicated_rock_data waypoint11)
    (communicated_rock_data waypoint14)
    (communicated_rock_data waypoint10)
    (communicated_rock_data waypoint3)
    (communicated_rock_data waypoint12)
    (communicated_image_data objective0 low_res)
    (communicated_image_data objective3 high_res)
    (communicated_image_data objective4 high_res)
))

(:metric minimize (recharges))
)
