(define (problem mprime-x-21)
   (:domain mystery-prime-typed)
   (:objects muffin broccoli potato lettuce melon tofu orange cherry chicken apple pepper bacon turkey papaya rice-22 pear-23 flounder-24 okra-25 pork-26 - food
             achievement satisfaction entertainment rest-6 satiety-7 - pleasure
             jealousy sciatica hangover-12 depression-13 abrasion-14 anxiety-15 anger-16 angina-17 boils-18 grief-19 loneliness-20 dread-21 jealousy-22 sciatica-23 hangover-24 depression-25 abrasion-26 anxiety-27 anger-28 angina-29 boils-30 grief-31 loneliness-32 dread-33 jealousy-34 sciatica-35 hangover-36 depression-37 abrasion-38 anxiety-39 anger-40 - pain
)
   (:init
(= (locale muffin) 7)
(= (locale broccoli) 0)
(= (locale potato) 15)
(= (locale lettuce) 8)
(= (locale melon) 12)
(= (locale tofu) 11)
(= (locale orange) 3)
(= (locale cherry) 2)
(= (locale chicken) 6)
(= (locale apple) 3)
(= (locale pepper) 13)
(= (locale bacon) 11)
(= (locale turkey) 7)
(= (locale papaya) 8)
(= (locale rice-22) 9)
(= (locale pear-23) 5)
(= (locale flounder-24) 3)
(= (locale okra-25) 0)
(= (locale pork-26) 15)
(= (harmony achievement) 2)
(= (harmony satisfaction) 2)
(= (harmony entertainment) 3)
(= (harmony rest-6) 3)
(= (harmony satiety-7) 1)
(eats muffin pork-26)
(eats broccoli broccoli)
(eats potato broccoli)
(eats lettuce lettuce)
(eats lettuce okra-25)
(eats lettuce cherry)
(eats melon rice-22)
(eats melon bacon)
(eats melon pepper)
(eats tofu apple)
(eats orange rice-22)
(eats orange pork-26)
(eats orange broccoli)
(eats cherry okra-25)
(eats cherry lettuce)
(eats cherry pear-23)
(eats chicken turkey)
(eats apple broccoli)
(eats apple melon)
(eats pepper apple)
(eats bacon broccoli)
(eats bacon apple)
(eats turkey cherry)
(eats papaya melon)
(eats papaya potato)
(eats rice-22 flounder-24)
(eats rice-22 apple)
(eats pear-23 rice-22)
(eats flounder-24 pork-26)
(eats flounder-24 tofu)
(eats flounder-24 muffin)
(eats okra-25 rice-22)
(eats pork-26 tofu)
(craves abrasion-14 rice-22)
(craves abrasion-26 muffin)
(craves abrasion-38 pepper)
(craves achievement pepper)
(craves anger-16 flounder-24)
(craves anger-16 papaya)
(craves anger-28 melon)
(craves anger-28 rice-22)
(craves anger-40 bacon)
(craves anger-40 flounder-24)
(craves angina-17 flounder-24)
(craves angina-29 chicken)
(craves angina-29 melon)
(craves anxiety-15 broccoli)
(craves anxiety-27 okra-25)
(craves anxiety-27 pear-23)
(craves anxiety-39 pepper)
(craves anxiety-39 pork-26)
(craves boils-18 okra-25)
(craves boils-18 pepper)
(craves boils-30 chicken)
(craves boils-30 orange)
(craves depression-13 cherry)
(craves depression-25 muffin)
(craves depression-25 okra-25)
(craves depression-37 rice-22)
(craves dread-21 bacon)
(craves dread-21 lettuce)
(craves dread-33 chicken)
(craves entertainment chicken)
(craves entertainment melon)
(craves grief-19 pork-26)
(craves grief-31 pepper)
(craves grief-31 potato)
(craves hangover-12 pear-23)
(craves hangover-24 okra-25)
(craves hangover-24 pepper)
(craves hangover-36 cherry)
(craves hangover-36 pepper)
(craves jealousy bacon)
(craves jealousy rice-22)
(craves jealousy-22 flounder-24)
(craves jealousy-34 melon)
(craves jealousy-34 turkey)
(craves loneliness-20 cherry)
(craves loneliness-32 bacon)
(craves rest-6 pear-23)
(craves satiety-7 broccoli)
(craves satiety-7 chicken)
(craves satiety-7 orange)
(craves satiety-7 potato)
(craves satisfaction tofu)
(craves sciatica okra-25)
(craves sciatica-23 flounder-24)
(craves sciatica-35 muffin)
(craves sciatica-35 turkey))
   (:goal (and (craves angina-29 potato))))
