(define (problem mprime-x-24)
   (:domain mystery-prime-typed)
   (:objects melon tofu orange cherry chicken apple pepper bacon turkey papaya rice-22 pear-23 flounder-24 okra-25 pork-26 lamb-27 wurst-28 - food
             achievement satisfaction entertainment rest-6 satiety-7 curiosity-8 - pleasure
             jealousy sciatica hangover-12 depression-13 abrasion-14 anxiety-15 anger-16 angina-17 boils-18 grief-19 loneliness-20 dread-21 jealousy-22 sciatica-23 hangover-24 depression-25 abrasion-26 anxiety-27 anger-28 angina-29 boils-30 grief-31 loneliness-32 dread-33 jealousy-34 sciatica-35 hangover-36 depression-37 abrasion-38 anxiety-39 anger-40 angina-41 boils-42 grief-43 loneliness-44 dread-45 jealousy-46 sciatica-47 hangover-48 depression-49 abrasion-50 anxiety-51 anger-52 - pain
)
   (:init
(= (locale melon) 2)
(= (locale tofu) 9)
(= (locale orange) 12)
(= (locale cherry) 11)
(= (locale chicken) 0)
(= (locale apple) 5)
(= (locale pepper) 11)
(= (locale bacon) 7)
(= (locale turkey) 12)
(= (locale papaya) 7)
(= (locale rice-22) 6)
(= (locale pear-23) 14)
(= (locale flounder-24) 13)
(= (locale okra-25) 3)
(= (locale pork-26) 15)
(= (locale lamb-27) 13)
(= (locale wurst-28) 6)
(= (harmony achievement) 2)
(= (harmony satisfaction) 2)
(= (harmony entertainment) 3)
(= (harmony rest-6) 3)
(= (harmony satiety-7) 1)
(= (harmony curiosity-8) 3)
(eats melon rice-22)
(eats melon melon)
(eats tofu melon)
(eats orange chicken)
(eats cherry pear-23)
(eats chicken bacon)
(eats chicken lamb-27)
(eats apple tofu)
(eats apple flounder-24)
(eats apple pear-23)
(eats pepper tofu)
(eats pepper pork-26)
(eats bacon pork-26)
(eats bacon rice-22)
(eats bacon flounder-24)
(eats turkey lamb-27)
(eats papaya melon)
(eats rice-22 melon)
(eats rice-22 wurst-28)
(eats rice-22 rice-22)
(eats pear-23 melon)
(eats flounder-24 melon)
(eats okra-25 okra-25)
(eats okra-25 tofu)
(eats pork-26 pepper)
(eats pork-26 melon)
(eats pork-26 wurst-28)
(eats lamb-27 papaya)
(eats lamb-27 pepper)
(eats lamb-27 okra-25)
(eats wurst-28 bacon)
(eats wurst-28 cherry)
(eats wurst-28 melon)
(craves abrasion-14 bacon)
(craves abrasion-26 bacon)
(craves abrasion-26 turkey)
(craves abrasion-38 cherry)
(craves abrasion-38 chicken)
(craves abrasion-50 orange)
(craves achievement wurst-28)
(craves anger-16 cherry)
(craves anger-16 pork-26)
(craves anger-28 papaya)
(craves anger-28 turkey)
(craves anger-40 okra-25)
(craves anger-40 rice-22)
(craves anger-52 rice-22)
(craves angina-17 rice-22)
(craves angina-29 turkey)
(craves angina-41 apple)
(craves anxiety-15 okra-25)
(craves anxiety-27 melon)
(craves anxiety-27 papaya)
(craves anxiety-39 melon)
(craves anxiety-51 pork-26)
(craves boils-18 pepper)
(craves boils-18 wurst-28)
(craves boils-30 bacon)
(craves boils-30 papaya)
(craves boils-42 lamb-27)
(craves boils-42 orange)
(craves curiosity-8 chicken)
(craves curiosity-8 lamb-27)
(craves depression-13 papaya)
(craves depression-25 bacon)
(craves depression-37 turkey)
(craves depression-49 pear-23)
(craves depression-49 pepper)
(craves dread-21 orange)
(craves dread-21 pork-26)
(craves dread-33 apple)
(craves dread-45 melon)
(craves dread-45 orange)
(craves entertainment melon)
(craves entertainment okra-25)
(craves entertainment orange)
(craves entertainment rice-22)
(craves grief-19 rice-22)
(craves grief-19 wurst-28)
(craves grief-31 turkey)
(craves grief-43 melon)
(craves hangover-12 melon)
(craves hangover-12 pepper)
(craves hangover-24 orange)
(craves hangover-36 bacon)
(craves hangover-36 papaya)
(craves hangover-48 lamb-27)
(craves hangover-48 tofu)
(craves jealousy tofu)
(craves jealousy wurst-28)
(craves jealousy-22 pork-26)
(craves jealousy-22 turkey)
(craves jealousy-34 lamb-27)
(craves jealousy-34 turkey)
(craves jealousy-46 chicken)
(craves jealousy-46 flounder-24)
(craves loneliness-20 pear-23)
(craves loneliness-32 cherry)
(craves loneliness-32 papaya)
(craves loneliness-44 bacon)
(craves loneliness-44 pork-26)
(craves rest-6 flounder-24)
(craves satiety-7 apple)
(craves satisfaction chicken)
(craves sciatica bacon)
(craves sciatica melon)
(craves sciatica-23 bacon)
(craves sciatica-23 wurst-28)
(craves sciatica-35 bacon)
(craves sciatica-35 pear-23)
(craves sciatica-47 pear-23))
   (:goal (and (craves anger-40 orange))))
