(define (problem mprime-x-29)
   (:domain mystery-prime-typed)
   (:objects okra pork lamb wurst shrimp muffin broccoli potato lettuce melon tofu orange cherry chicken apple pepper bacon turkey papaya - food
             satiety curiosity achievement satisfaction entertainment rest-6 - pleasure
             anxiety anger angina boils grief loneliness dread jealousy sciatica hangover-12 depression-13 abrasion-14 anxiety-15 anger-16 angina-17 boils-18 grief-19 loneliness-20 dread-21 jealousy-22 sciatica-23 hangover-24 depression-25 abrasion-26 anxiety-27 anger-28 angina-29 boils-30 grief-31 loneliness-32 dread-33 jealousy-34 sciatica-35 hangover-36 depression-37 abrasion-38 anxiety-39 anger-40 - pain
)
   (:init
(= (locale okra) 6)
(= (locale pork) 8)
(= (locale lamb) 13)
(= (locale wurst) 11)
(= (locale shrimp) 2)
(= (locale muffin) 11)
(= (locale broccoli) 14)
(= (locale potato) 10)
(= (locale lettuce) 3)
(= (locale melon) 9)
(= (locale tofu) 12)
(= (locale orange) 7)
(= (locale cherry) 14)
(= (locale chicken) 15)
(= (locale apple) 10)
(= (locale pepper) 5)
(= (locale bacon) 10)
(= (locale turkey) 4)
(= (locale papaya) 15)
(= (harmony satiety) 1)
(= (harmony curiosity) 2)
(= (harmony achievement) 1)
(= (harmony satisfaction) 1)
(= (harmony entertainment) 3)
(= (harmony rest-6) 2)
(eats okra turkey)
(eats okra pepper)
(eats pork wurst)
(eats lamb papaya)
(eats lamb bacon)
(eats lamb lamb)
(eats wurst muffin)
(eats wurst melon)
(eats wurst shrimp)
(eats shrimp pepper)
(eats shrimp cherry)
(eats muffin melon)
(eats muffin lamb)
(eats broccoli okra)
(eats broccoli lettuce)
(eats broccoli pepper)
(eats potato broccoli)
(eats lettuce muffin)
(eats lettuce lettuce)
(eats melon bacon)
(eats melon shrimp)
(eats tofu apple)
(eats tofu lamb)
(eats orange cherry)
(eats cherry lamb)
(eats chicken okra)
(eats chicken chicken)
(eats chicken broccoli)
(eats apple muffin)
(eats pepper wurst)
(eats pepper muffin)
(eats bacon pepper)
(eats bacon potato)
(eats turkey okra)
(eats turkey orange)
(eats turkey muffin)
(eats papaya cherry)
(eats papaya pork)
(craves abrasion-14 bacon)
(craves abrasion-14 pepper)
(craves abrasion-26 chicken)
(craves abrasion-26 potato)
(craves abrasion-38 lettuce)
(craves achievement bacon)
(craves achievement okra)
(craves achievement orange)
(craves anger cherry)
(craves anger papaya)
(craves anger-16 muffin)
(craves anger-28 tofu)
(craves anger-40 tofu)
(craves angina pepper)
(craves angina shrimp)
(craves angina-17 cherry)
(craves angina-29 lamb)
(craves angina-29 orange)
(craves anxiety lettuce)
(craves anxiety muffin)
(craves anxiety-15 melon)
(craves anxiety-27 broccoli)
(craves anxiety-39 bacon)
(craves anxiety-39 turkey)
(craves boils shrimp)
(craves boils-18 apple)
(craves boils-18 broccoli)
(craves boils-30 wurst)
(craves curiosity broccoli)
(craves depression-13 broccoli)
(craves depression-25 apple)
(craves depression-25 bacon)
(craves depression-37 apple)
(craves depression-37 pepper)
(craves dread chicken)
(craves dread pepper)
(craves dread-21 turkey)
(craves dread-33 cherry)
(craves entertainment melon)
(craves grief potato)
(craves grief-19 chicken)
(craves grief-19 melon)
(craves grief-31 shrimp)
(craves hangover-12 broccoli)
(craves hangover-24 apple)
(craves hangover-36 lamb)
(craves jealousy pork)
(craves jealousy-22 shrimp)
(craves jealousy-34 turkey)
(craves loneliness pepper)
(craves loneliness wurst)
(craves loneliness-20 bacon)
(craves loneliness-20 muffin)
(craves loneliness-32 melon)
(craves loneliness-32 tofu)
(craves rest-6 apple)
(craves rest-6 papaya)
(craves rest-6 pepper)
(craves satiety broccoli)
(craves satiety cherry)
(craves satiety turkey)
(craves satisfaction broccoli)
(craves sciatica lettuce)
(craves sciatica papaya)
(craves sciatica-23 okra)
(craves sciatica-35 cherry)
(craves sciatica-35 okra))
   (:goal (and (craves depression-25 pepper) (craves sciatica-23 bacon) (craves jealousy-34 broccoli))))
