(define (problem mprime-x-23)
   (:domain mystery-prime-typed)
   (:objects flounder okra pork lamb wurst shrimp muffin broccoli potato lettuce melon tofu orange cherry chicken apple pepper bacon turkey papaya - food
             rest satiety curiosity achievement - pleasure
             abrasion anxiety anger angina boils grief loneliness dread jealousy sciatica hangover-12 depression-13 abrasion-14 anxiety-15 anger-16 angina-17 boils-18 grief-19 loneliness-20 dread-21 jealousy-22 sciatica-23 hangover-24 depression-25 abrasion-26 anxiety-27 anger-28 angina-29 boils-30 grief-31 loneliness-32 dread-33 jealousy-34 sciatica-35 hangover-36 depression-37 abrasion-38 anxiety-39 anger-40 angina-41 boils-42 grief-43 - pain
)
   (:init
(= (locale flounder) 9)
(= (locale okra) 6)
(= (locale pork) 8)
(= (locale lamb) 8)
(= (locale wurst) 11)
(= (locale shrimp) 1)
(= (locale muffin) 13)
(= (locale broccoli) 6)
(= (locale potato) 7)
(= (locale lettuce) 1)
(= (locale melon) 15)
(= (locale tofu) 6)
(= (locale orange) 0)
(= (locale cherry) 1)
(= (locale chicken) 10)
(= (locale apple) 0)
(= (locale pepper) 3)
(= (locale bacon) 0)
(= (locale turkey) 3)
(= (locale papaya) 7)
(= (harmony rest) 2)
(= (harmony satiety) 3)
(= (harmony curiosity) 1)
(= (harmony achievement) 2)
(eats flounder papaya)
(eats flounder shrimp)
(eats okra wurst)
(eats okra pork)
(eats okra lamb)
(eats pork wurst)
(eats lamb chicken)
(eats lamb muffin)
(eats wurst flounder)
(eats wurst tofu)
(eats wurst melon)
(eats shrimp papaya)
(eats shrimp pepper)
(eats shrimp potato)
(eats muffin pepper)
(eats broccoli cherry)
(eats broccoli papaya)
(eats potato cherry)
(eats lettuce turkey)
(eats lettuce flounder)
(eats lettuce bacon)
(eats melon potato)
(eats melon shrimp)
(eats melon orange)
(eats tofu tofu)
(eats tofu muffin)
(eats orange apple)
(eats orange papaya)
(eats cherry wurst)
(eats cherry shrimp)
(eats cherry cherry)
(eats chicken lettuce)
(eats apple orange)
(eats apple flounder)
(eats pepper cherry)
(eats bacon wurst)
(eats bacon lettuce)
(eats turkey shrimp)
(eats papaya orange)
(craves abrasion okra)
(craves abrasion potato)
(craves abrasion-14 muffin)
(craves abrasion-14 turkey)
(craves abrasion-26 turkey)
(craves abrasion-38 pepper)
(craves achievement flounder)
(craves anger chicken)
(craves anger okra)
(craves anger-16 potato)
(craves anger-16 turkey)
(craves anger-28 lettuce)
(craves anger-28 shrimp)
(craves anger-40 turkey)
(craves angina melon)
(craves angina-17 cherry)
(craves angina-29 shrimp)
(craves angina-41 chicken)
(craves angina-41 melon)
(craves anxiety tofu)
(craves anxiety turkey)
(craves anxiety-15 okra)
(craves anxiety-15 wurst)
(craves anxiety-27 lamb)
(craves anxiety-39 lamb)
(craves anxiety-39 shrimp)
(craves boils orange)
(craves boils-18 broccoli)
(craves boils-30 orange)
(craves boils-30 papaya)
(craves boils-42 papaya)
(craves curiosity tofu)
(craves depression-13 melon)
(craves depression-13 papaya)
(craves depression-25 pepper)
(craves depression-37 turkey)
(craves dread lamb)
(craves dread-21 broccoli)
(craves dread-33 cherry)
(craves dread-33 potato)
(craves grief wurst)
(craves grief-19 muffin)
(craves grief-19 papaya)
(craves grief-31 okra)
(craves grief-31 turkey)
(craves grief-43 orange)
(craves hangover-12 bacon)
(craves hangover-12 melon)
(craves hangover-24 lettuce)
(craves hangover-36 apple)
(craves jealousy chicken)
(craves jealousy okra)
(craves jealousy-22 turkey)
(craves jealousy-34 orange)
(craves loneliness bacon)
(craves loneliness cherry)
(craves loneliness-20 lamb)
(craves loneliness-20 potato)
(craves loneliness-32 lamb)
(craves rest broccoli)
(craves rest cherry)
(craves rest pepper)
(craves rest pork)
(craves satiety pepper)
(craves sciatica pork)
(craves sciatica-23 apple)
(craves sciatica-23 lettuce)
(craves sciatica-35 potato))
   (:goal (and (craves angina-17 pepper))))
