(define (problem roverprob-0) (:domain rover)
(:objects
    general - lander
    colour high_res low_res - mode
    rover0 rover1 - rover
    rover0store rover1store - store
    waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 waypoint7 - waypoint
    camera0 camera1 camera2 - camera
    objective0 objective1 - objective
)
(:init
    (visible waypoint0 waypoint7)
    (visible waypoint1 waypoint4)
    (visible waypoint1 waypoint5)
    (visible waypoint1 waypoint6)
    (visible waypoint2 waypoint3)
    (visible waypoint2 waypoint6)
    (visible waypoint3 waypoint2)
    (visible waypoint3 waypoint5)
    (visible waypoint3 waypoint7)
    (visible waypoint4 waypoint1)
    (visible waypoint4 waypoint6)
    (visible waypoint5 waypoint1)
    (visible waypoint6 waypoint1)
    (visible waypoint6 waypoint2)
    (visible waypoint6 waypoint4)
    (visible waypoint7 waypoint0)
    (visible waypoint7 waypoint3)
    (at_soil_sample waypoint7)
    (at_soil_sample waypoint0)
    (at_soil_sample waypoint5)
    (at_soil_sample waypoint6)
    (at_soil_sample waypoint4)
    (at_soil_sample waypoint3)
    (at_soil_sample waypoint1)
    (at_soil_sample waypoint2)
    (at_rock_sample waypoint2)
    (at_rock_sample waypoint4)
    (at_rock_sample waypoint5)
    (at_rock_sample waypoint3)
    (at_rock_sample waypoint1)
    (in_sun waypoint2)
    (in_sun waypoint6)
    (in_sun waypoint1)
    (in_sun waypoint3)
    (in_sun waypoint7)
    (in_sun waypoint0)
    (in_sun waypoint4)
    (in_sun waypoint5)
    (at_lander general waypoint3)
    (channel_free general)
    (in rover0 waypoint0)
    (available rover0)
    (store_of rover0store rover0)
    (empty rover0store)
    (equipped_for_rock_analysis rover0)
    (equipped_for_imaging rover0)
    (in rover1 waypoint2)
    (available rover1)
    (store_of rover1store rover1)
    (empty rover1store)
    (equipped_for_soil_analysis rover1)
    (equipped_for_rock_analysis rover1)
    (equipped_for_imaging rover1)
    (can_traverse rover0 waypoint0 waypoint7)
    (can_traverse rover0 waypoint1 waypoint5)
    (can_traverse rover0 waypoint1 waypoint6)
    (can_traverse rover0 waypoint2 waypoint3)
    (can_traverse rover0 waypoint2 waypoint6)
    (can_traverse rover0 waypoint3 waypoint2)
    (can_traverse rover0 waypoint3 waypoint5)
    (can_traverse rover0 waypoint3 waypoint7)
    (can_traverse rover0 waypoint4 waypoint6)
    (can_traverse rover0 waypoint5 waypoint1)
    (can_traverse rover0 waypoint5 waypoint3)
    (can_traverse rover0 waypoint6 waypoint1)
    (can_traverse rover0 waypoint6 waypoint2)
    (can_traverse rover0 waypoint6 waypoint4)
    (can_traverse rover0 waypoint7 waypoint0)
    (can_traverse rover0 waypoint7 waypoint3)
    (can_traverse rover1 waypoint0 waypoint7)
    (can_traverse rover1 waypoint1 waypoint4)
    (can_traverse rover1 waypoint1 waypoint5)
    (can_traverse rover1 waypoint1 waypoint6)
    (can_traverse rover1 waypoint2 waypoint6)
    (can_traverse rover1 waypoint3 waypoint2)
    (can_traverse rover1 waypoint3 waypoint5)
    (can_traverse rover1 waypoint3 waypoint7)
    (can_traverse rover1 waypoint4 waypoint1)
    (can_traverse rover1 waypoint4 waypoint6)
    (can_traverse rover1 waypoint5 waypoint1)
    (can_traverse rover1 waypoint5 waypoint3)
    (can_traverse rover1 waypoint6 waypoint1)
    (can_traverse rover1 waypoint6 waypoint2)
    (can_traverse rover1 waypoint7 waypoint0)
    (can_traverse rover1 waypoint7 waypoint3)
    (on_board camera0 rover1)
    (calibration_target camera0 objective0)
    (supports camera0 high_res)
    (on_board camera1 rover0)
    (calibration_target camera1 objective0)
    (supports camera1 high_res)
    (on_board camera2 rover1)
    (calibration_target camera2 objective1)
    (supports camera2 colour)
    (visible_from objective0 waypoint1)
    (visible_from objective1 waypoint3)
    (visible_from objective1 waypoint1)
    (= (recharges) 0)
    (= (energy rover0) 72)
    (= (energy rover1) 52)
)

(:goal (and
    (communicated_soil_data waypoint4)
    (communicated_soil_data waypoint2)
    (communicated_rock_data waypoint2)
    (communicated_image_data objective0 high_res)
))

(:metric minimize (recharges))
)
