(define (problem mprime-x-30)
   (:domain mystery-prime-typed)
   (:objects tofu orange cherry chicken apple pepper bacon turkey papaya rice-22 pear-23 flounder-24 okra-25 pork-26 lamb-27 wurst-28 shrimp-29 - food
             entertainment rest-6 satiety-7 curiosity-8 - pleasure
             dread jealousy sciatica hangover-12 depression-13 abrasion-14 anxiety-15 anger-16 angina-17 boils-18 grief-19 loneliness-20 dread-21 jealousy-22 sciatica-23 hangover-24 depression-25 abrasion-26 anxiety-27 anger-28 angina-29 boils-30 grief-31 loneliness-32 dread-33 jealousy-34 sciatica-35 hangover-36 depression-37 abrasion-38 anxiety-39 anger-40 angina-41 boils-42 grief-43 - pain
)
   (:init
(= (locale tofu) 15)
(= (locale orange) 13)
(= (locale cherry) 6)
(= (locale chicken) 3)
(= (locale apple) 12)
(= (locale pepper) 15)
(= (locale bacon) 12)
(= (locale turkey) 11)
(= (locale papaya) 13)
(= (locale rice-22) 11)
(= (locale pear-23) 2)
(= (locale flounder-24) 5)
(= (locale okra-25) 4)
(= (locale pork-26) 8)
(= (locale lamb-27) 14)
(= (locale wurst-28) 10)
(= (locale shrimp-29) 13)
(= (harmony entertainment) 3)
(= (harmony rest-6) 3)
(= (harmony satiety-7) 3)
(= (harmony curiosity-8) 2)
(eats tofu turkey)
(eats tofu lamb-27)
(eats orange turkey)
(eats orange chicken)
(eats orange lamb-27)
(eats cherry papaya)
(eats chicken lamb-27)
(eats chicken turkey)
(eats apple tofu)
(eats apple wurst-28)
(eats apple chicken)
(eats pepper flounder-24)
(eats pepper wurst-28)
(eats pepper bacon)
(eats bacon lamb-27)
(eats turkey rice-22)
(eats turkey pork-26)
(eats papaya pear-23)
(eats papaya pepper)
(eats rice-22 lamb-27)
(eats rice-22 turkey)
(eats rice-22 shrimp-29)
(eats pear-23 papaya)
(eats pear-23 okra-25)
(eats flounder-24 pepper)
(eats flounder-24 wurst-28)
(eats flounder-24 pear-23)
(eats okra-25 pear-23)
(eats okra-25 lamb-27)
(eats okra-25 pork-26)
(eats pork-26 flounder-24)
(eats lamb-27 chicken)
(eats lamb-27 flounder-24)
(eats wurst-28 pepper)
(eats wurst-28 rice-22)
(eats shrimp-29 papaya)
(craves abrasion-14 lamb-27)
(craves abrasion-26 chicken)
(craves abrasion-38 lamb-27)
(craves anger-16 okra-25)
(craves anger-28 pear-23)
(craves anger-40 cherry)
(craves anger-40 pepper)
(craves angina-17 pepper)
(craves angina-17 pork-26)
(craves angina-29 flounder-24)
(craves angina-41 flounder-24)
(craves anxiety-15 rice-22)
(craves anxiety-15 tofu)
(craves anxiety-27 turkey)
(craves anxiety-39 papaya)
(craves anxiety-39 shrimp-29)
(craves boils-18 pork-26)
(craves boils-18 tofu)
(craves boils-30 papaya)
(craves boils-42 cherry)
(craves boils-42 turkey)
(craves curiosity-8 apple)
(craves curiosity-8 cherry)
(craves curiosity-8 orange)
(craves depression-13 pepper)
(craves depression-25 bacon)
(craves depression-25 pepper)
(craves depression-37 cherry)
(craves dread lamb-27)
(craves dread-21 turkey)
(craves dread-33 apple)
(craves dread-33 cherry)
(craves entertainment apple)
(craves grief-19 flounder-24)
(craves grief-19 pear-23)
(craves grief-31 lamb-27)
(craves grief-31 okra-25)
(craves grief-43 bacon)
(craves grief-43 lamb-27)
(craves hangover-12 lamb-27)
(craves hangover-12 pear-23)
(craves hangover-24 lamb-27)
(craves hangover-36 okra-25)
(craves jealousy shrimp-29)
(craves jealousy-22 papaya)
(craves jealousy-34 turkey)
(craves loneliness-20 rice-22)
(craves loneliness-20 tofu)
(craves loneliness-32 flounder-24)
(craves loneliness-32 papaya)
(craves rest-6 bacon)
(craves rest-6 rice-22)
(craves rest-6 tofu)
(craves rest-6 turkey)
(craves satiety-7 apple)
(craves satiety-7 chicken)
(craves satiety-7 papaya)
(craves sciatica okra-25)
(craves sciatica papaya)
(craves sciatica-23 apple)
(craves sciatica-35 wurst-28))
   (:goal (and (craves jealousy-22 chicken) (craves boils-18 turkey) (craves dread-33 orange))))
