(define (problem mprime-x-22)
   (:domain mystery-prime-typed)
   (:objects okra pork lamb wurst shrimp muffin broccoli potato lettuce melon tofu orange cherry chicken apple pepper bacon - food
             entertainment rest-6 satiety-7 curiosity-8 achievement-9 satisfaction-10 - pleasure
             anger angina boils grief loneliness dread jealousy sciatica hangover-12 depression-13 abrasion-14 anxiety-15 anger-16 angina-17 boils-18 grief-19 loneliness-20 dread-21 jealousy-22 sciatica-23 hangover-24 depression-25 abrasion-26 anxiety-27 anger-28 angina-29 boils-30 - pain
)
   (:init
(= (locale okra) 10)
(= (locale pork) 8)
(= (locale lamb) 10)
(= (locale wurst) 15)
(= (locale shrimp) 9)
(= (locale muffin) 14)
(= (locale broccoli) 6)
(= (locale potato) 5)
(= (locale lettuce) 13)
(= (locale melon) 0)
(= (locale tofu) 3)
(= (locale orange) 0)
(= (locale cherry) 1)
(= (locale chicken) 10)
(= (locale apple) 14)
(= (locale pepper) 10)
(= (locale bacon) 0)
(= (harmony entertainment) 3)
(= (harmony rest-6) 2)
(= (harmony satiety-7) 2)
(= (harmony curiosity-8) 1)
(= (harmony achievement-9) 2)
(= (harmony satisfaction-10) 2)
(eats okra broccoli)
(eats pork bacon)
(eats pork muffin)
(eats lamb shrimp)
(eats lamb bacon)
(eats lamb orange)
(eats wurst cherry)
(eats shrimp shrimp)
(eats shrimp lettuce)
(eats muffin orange)
(eats muffin wurst)
(eats broccoli orange)
(eats broccoli apple)
(eats broccoli lamb)
(eats potato pork)
(eats potato wurst)
(eats lettuce broccoli)
(eats melon shrimp)
(eats melon wurst)
(eats tofu melon)
(eats tofu apple)
(eats tofu okra)
(eats orange wurst)
(eats cherry broccoli)
(eats cherry potato)
(eats chicken pork)
(eats apple okra)
(eats apple lamb)
(eats pepper lamb)
(eats bacon okra)
(eats bacon melon)
(craves abrasion-14 tofu)
(craves abrasion-26 pepper)
(craves abrasion-26 pork)
(craves achievement-9 okra)
(craves achievement-9 shrimp)
(craves anger lettuce)
(craves anger pepper)
(craves anger-16 cherry)
(craves anger-28 melon)
(craves angina chicken)
(craves angina potato)
(craves angina-17 chicken)
(craves angina-29 lettuce)
(craves anxiety-15 lamb)
(craves anxiety-15 orange)
(craves anxiety-27 okra)
(craves boils shrimp)
(craves boils-18 pepper)
(craves boils-30 bacon)
(craves boils-30 okra)
(craves curiosity-8 lettuce)
(craves depression-13 potato)
(craves depression-25 potato)
(craves dread shrimp)
(craves dread-21 cherry)
(craves entertainment lamb)
(craves entertainment pork)
(craves grief okra)
(craves grief-19 pork)
(craves hangover-12 apple)
(craves hangover-12 muffin)
(craves hangover-24 orange)
(craves hangover-24 pork)
(craves jealousy muffin)
(craves jealousy-22 pepper)
(craves loneliness apple)
(craves loneliness-20 broccoli)
(craves rest-6 apple)
(craves rest-6 wurst)
(craves satiety-7 okra)
(craves satisfaction-10 cherry)
(craves satisfaction-10 lettuce)
(craves satisfaction-10 orange)
(craves sciatica tofu)
(craves sciatica-23 wurst))
   (:goal (and (craves hangover-24 lettuce) (craves grief shrimp))))
