(define (problem mprime-x-26)
   (:domain mystery-prime-typed)
   (:objects broccoli potato lettuce melon tofu orange cherry chicken apple pepper bacon turkey papaya rice-22 pear-23 flounder-24 okra-25 pork-26 lamb-27 wurst-28 shrimp-29 - food
             entertainment rest-6 satiety-7 curiosity-8 achievement-9 satisfaction-10 - pleasure
             sciatica hangover-12 depression-13 abrasion-14 anxiety-15 anger-16 angina-17 boils-18 grief-19 loneliness-20 dread-21 jealousy-22 sciatica-23 hangover-24 depression-25 abrasion-26 anxiety-27 anger-28 angina-29 boils-30 grief-31 loneliness-32 dread-33 jealousy-34 sciatica-35 - pain
)
   (:init
(= (locale broccoli) 14)
(= (locale potato) 7)
(= (locale lettuce) 10)
(= (locale melon) 8)
(= (locale tofu) 3)
(= (locale orange) 13)
(= (locale cherry) 10)
(= (locale chicken) 15)
(= (locale apple) 2)
(= (locale pepper) 9)
(= (locale bacon) 12)
(= (locale turkey) 3)
(= (locale papaya) 0)
(= (locale rice-22) 9)
(= (locale pear-23) 8)
(= (locale flounder-24) 14)
(= (locale okra-25) 5)
(= (locale pork-26) 10)
(= (locale lamb-27) 12)
(= (locale wurst-28) 0)
(= (locale shrimp-29) 9)
(= (harmony entertainment) 3)
(= (harmony rest-6) 2)
(= (harmony satiety-7) 1)
(= (harmony curiosity-8) 3)
(= (harmony achievement-9) 3)
(= (harmony satisfaction-10) 3)
(eats broccoli potato)
(eats broccoli pear-23)
(eats potato shrimp-29)
(eats potato papaya)
(eats potato pepper)
(eats lettuce tofu)
(eats lettuce okra-25)
(eats melon lamb-27)
(eats melon rice-22)
(eats melon lettuce)
(eats tofu chicken)
(eats tofu potato)
(eats orange melon)
(eats orange apple)
(eats orange bacon)
(eats cherry melon)
(eats chicken broccoli)
(eats apple turkey)
(eats pepper melon)
(eats pepper cherry)
(eats bacon shrimp-29)
(eats bacon wurst-28)
(eats bacon cherry)
(eats turkey potato)
(eats papaya okra-25)
(eats papaya pear-23)
(eats papaya potato)
(eats rice-22 broccoli)
(eats rice-22 bacon)
(eats rice-22 papaya)
(eats pear-23 apple)
(eats flounder-24 rice-22)
(eats okra-25 cherry)
(eats okra-25 flounder-24)
(eats pork-26 turkey)
(eats lamb-27 pork-26)
(eats wurst-28 potato)
(eats wurst-28 pepper)
(eats wurst-28 pork-26)
(eats shrimp-29 papaya)
(eats shrimp-29 tofu)
(eats shrimp-29 wurst-28)
(craves abrasion-14 broccoli)
(craves abrasion-26 wurst-28)
(craves achievement-9 papaya)
(craves anger-16 potato)
(craves anger-28 papaya)
(craves anger-28 turkey)
(craves angina-17 broccoli)
(craves angina-17 okra-25)
(craves angina-29 broccoli)
(craves anxiety-15 bacon)
(craves anxiety-27 orange)
(craves boils-18 bacon)
(craves boils-18 melon)
(craves boils-30 broccoli)
(craves curiosity-8 cherry)
(craves curiosity-8 chicken)
(craves curiosity-8 okra-25)
(craves curiosity-8 potato)
(craves depression-13 pepper)
(craves depression-13 rice-22)
(craves depression-25 cherry)
(craves dread-21 apple)
(craves dread-21 lamb-27)
(craves dread-33 pear-23)
(craves dread-33 pepper)
(craves entertainment tofu)
(craves grief-19 shrimp-29)
(craves grief-19 wurst-28)
(craves grief-31 chicken)
(craves grief-31 lettuce)
(craves hangover-12 cherry)
(craves hangover-12 potato)
(craves hangover-24 melon)
(craves hangover-24 rice-22)
(craves jealousy-22 cherry)
(craves jealousy-22 turkey)
(craves jealousy-34 pork-26)
(craves jealousy-34 potato)
(craves loneliness-20 papaya)
(craves loneliness-32 bacon)
(craves loneliness-32 rice-22)
(craves rest-6 papaya)
(craves satiety-7 okra-25)
(craves satisfaction-10 melon)
(craves sciatica shrimp-29)
(craves sciatica-23 cherry)
(craves sciatica-35 apple)
(craves sciatica-35 flounder-24))
   (:goal (and (craves angina-17 cherry))))
