(define (problem mprime-x-27)
   (:domain mystery-prime-typed)
   (:objects melon tofu orange cherry chicken apple pepper bacon turkey papaya rice-22 pear-23 flounder-24 okra-25 pork-26 lamb-27 wurst-28 shrimp-29 muffin-30 - food
             satisfaction entertainment rest-6 satiety-7 curiosity-8 - pleasure
             depression abrasion anxiety anger angina boils grief loneliness dread jealousy sciatica hangover-12 depression-13 abrasion-14 anxiety-15 anger-16 angina-17 boils-18 grief-19 loneliness-20 dread-21 jealousy-22 sciatica-23 hangover-24 depression-25 abrasion-26 - pain
)
   (:init
(= (locale melon) 6)
(= (locale tofu) 3)
(= (locale orange) 5)
(= (locale cherry) 11)
(= (locale chicken) 1)
(= (locale apple) 3)
(= (locale pepper) 1)
(= (locale bacon) 1)
(= (locale turkey) 12)
(= (locale papaya) 0)
(= (locale rice-22) 4)
(= (locale pear-23) 2)
(= (locale flounder-24) 4)
(= (locale okra-25) 3)
(= (locale pork-26) 6)
(= (locale lamb-27) 6)
(= (locale wurst-28) 1)
(= (locale shrimp-29) 10)
(= (locale muffin-30) 3)
(= (harmony satisfaction) 1)
(= (harmony entertainment) 3)
(= (harmony rest-6) 1)
(= (harmony satiety-7) 3)
(= (harmony curiosity-8) 3)
(eats melon rice-22)
(eats tofu orange)
(eats orange pork-26)
(eats orange okra-25)
(eats cherry pepper)
(eats chicken okra-25)
(eats chicken shrimp-29)
(eats apple chicken)
(eats apple bacon)
(eats pepper bacon)
(eats pepper flounder-24)
(eats bacon flounder-24)
(eats turkey pork-26)
(eats turkey muffin-30)
(eats turkey turkey)
(eats papaya cherry)
(eats rice-22 cherry)
(eats pear-23 melon)
(eats pear-23 flounder-24)
(eats pear-23 okra-25)
(eats flounder-24 pear-23)
(eats flounder-24 turkey)
(eats flounder-24 rice-22)
(eats okra-25 pork-26)
(eats pork-26 cherry)
(eats pork-26 flounder-24)
(eats pork-26 lamb-27)
(eats lamb-27 orange)
(eats wurst-28 melon)
(eats wurst-28 pork-26)
(eats shrimp-29 apple)
(eats shrimp-29 bacon)
(eats shrimp-29 pork-26)
(eats muffin-30 pear-23)
(craves abrasion muffin-30)
(craves abrasion wurst-28)
(craves abrasion-14 apple)
(craves abrasion-14 wurst-28)
(craves abrasion-26 chicken)
(craves anger flounder-24)
(craves anger shrimp-29)
(craves anger-16 melon)
(craves angina bacon)
(craves angina shrimp-29)
(craves angina-17 pork-26)
(craves angina-17 shrimp-29)
(craves anxiety chicken)
(craves anxiety papaya)
(craves anxiety-15 cherry)
(craves boils wurst-28)
(craves boils-18 pepper)
(craves curiosity-8 apple)
(craves curiosity-8 lamb-27)
(craves depression lamb-27)
(craves depression papaya)
(craves depression-13 orange)
(craves depression-25 flounder-24)
(craves depression-25 okra-25)
(craves dread pepper)
(craves dread tofu)
(craves dread-21 shrimp-29)
(craves entertainment papaya)
(craves entertainment shrimp-29)
(craves grief apple)
(craves grief-19 pork-26)
(craves hangover-12 cherry)
(craves hangover-12 wurst-28)
(craves hangover-24 turkey)
(craves jealousy orange)
(craves jealousy-22 orange)
(craves loneliness tofu)
(craves loneliness-20 cherry)
(craves rest-6 apple)
(craves rest-6 chicken)
(craves rest-6 orange)
(craves rest-6 rice-22)
(craves satiety-7 flounder-24)
(craves satisfaction apple)
(craves sciatica chicken)
(craves sciatica shrimp-29)
(craves sciatica-23 wurst-28))
   (:goal (and (craves abrasion-14 rice-22))))
