(define (problem mprime-x-15)
   (:domain mystery-prime-typed)
   (:objects wurst shrimp muffin broccoli potato lettuce melon tofu orange cherry chicken apple pepper bacon - food
             satiety curiosity achievement - pleasure
             dread jealousy sciatica hangover-12 depression-13 abrasion-14 anxiety-15 anger-16 angina-17 boils-18 grief-19 loneliness-20 dread-21 jealousy-22 sciatica-23 hangover-24 - pain
)
   (:init
(= (locale wurst) 8)
(= (locale shrimp) 0)
(= (locale muffin) 6)
(= (locale broccoli) 11)
(= (locale potato) 5)
(= (locale lettuce) 3)
(= (locale melon) 0)
(= (locale tofu) 5)
(= (locale orange) 11)
(= (locale cherry) 10)
(= (locale chicken) 1)
(= (locale apple) 7)
(= (locale pepper) 1)
(= (locale bacon) 2)
(= (harmony satiety) 2)
(= (harmony curiosity) 2)
(= (harmony achievement) 2)
(eats wurst broccoli)
(eats wurst muffin)
(eats wurst orange)
(eats shrimp bacon)
(eats shrimp apple)
(eats muffin pepper)
(eats muffin muffin)
(eats broccoli shrimp)
(eats potato melon)
(eats lettuce pepper)
(eats melon lettuce)
(eats melon shrimp)
(eats tofu apple)
(eats orange cherry)
(eats orange lettuce)
(eats orange orange)
(eats cherry chicken)
(eats cherry shrimp)
(eats chicken muffin)
(eats chicken shrimp)
(eats chicken bacon)
(eats apple muffin)
(eats apple apple)
(eats pepper shrimp)
(eats pepper pepper)
(eats bacon potato)
(craves abrasion-14 chicken)
(craves abrasion-14 melon)
(craves achievement apple)
(craves achievement melon)
(craves achievement orange)
(craves anger-16 orange)
(craves anger-16 potato)
(craves angina-17 pepper)
(craves anxiety-15 melon)
(craves boils-18 broccoli)
(craves curiosity muffin)
(craves curiosity orange)
(craves curiosity potato)
(craves depression-13 tofu)
(craves dread bacon)
(craves dread potato)
(craves dread-21 pepper)
(craves dread-21 wurst)
(craves grief-19 pepper)
(craves hangover-12 chicken)
(craves hangover-24 chicken)
(craves jealousy shrimp)
(craves jealousy wurst)
(craves jealousy-22 apple)
(craves jealousy-22 chicken)
(craves loneliness-20 melon)
(craves loneliness-20 pepper)
(craves satiety cherry)
(craves satiety orange)
(craves satiety pepper)
(craves satiety potato)
(craves sciatica shrimp)
(craves sciatica-23 potato))
   (:goal (and (craves loneliness-20 orange) (craves dread muffin) (craves anxiety-15 apple))))
