(define (problem mprime-x-16)
   (:domain mystery-prime-typed)
   (:objects lettuce melon tofu orange cherry chicken apple pepper bacon turkey papaya rice-22 pear-23 flounder-24 okra-25 pork-26 - food
             rest satiety curiosity achievement - pleasure
             hangover depression abrasion anxiety anger angina boils grief loneliness dread jealousy sciatica hangover-12 depression-13 - pain
)
   (:init
(= (locale lettuce) 5)
(= (locale melon) 9)
(= (locale tofu) 9)
(= (locale orange) 7)
(= (locale cherry) 5)
(= (locale chicken) 10)
(= (locale apple) 12)
(= (locale pepper) 10)
(= (locale bacon) 0)
(= (locale turkey) 7)
(= (locale papaya) 10)
(= (locale rice-22) 4)
(= (locale pear-23) 0)
(= (locale flounder-24) 2)
(= (locale okra-25) 7)
(= (locale pork-26) 11)
(= (harmony rest) 3)
(= (harmony satiety) 1)
(= (harmony curiosity) 3)
(= (harmony achievement) 1)
(eats lettuce rice-22)
(eats lettuce turkey)
(eats melon tofu)
(eats tofu turkey)
(eats orange pear-23)
(eats orange rice-22)
(eats cherry bacon)
(eats chicken bacon)
(eats chicken pepper)
(eats chicken apple)
(eats apple tofu)
(eats apple pepper)
(eats pepper orange)
(eats pepper turkey)
(eats pepper papaya)
(eats bacon apple)
(eats turkey melon)
(eats papaya flounder-24)
(eats rice-22 chicken)
(eats pear-23 bacon)
(eats pear-23 papaya)
(eats pear-23 okra-25)
(eats flounder-24 lettuce)
(eats flounder-24 papaya)
(eats flounder-24 bacon)
(eats okra-25 orange)
(eats okra-25 cherry)
(eats pork-26 melon)
(craves abrasion apple)
(craves abrasion pork-26)
(craves achievement flounder-24)
(craves anger flounder-24)
(craves anger tofu)
(craves angina tofu)
(craves anxiety cherry)
(craves boils pear-23)
(craves curiosity bacon)
(craves curiosity rice-22)
(craves depression apple)
(craves depression-13 cherry)
(craves dread lettuce)
(craves dread tofu)
(craves grief flounder-24)
(craves grief tofu)
(craves hangover pear-23)
(craves hangover pork-26)
(craves hangover-12 pear-23)
(craves jealousy okra-25)
(craves loneliness flounder-24)
(craves loneliness turkey)
(craves rest apple)
(craves rest okra-25)
(craves satiety papaya)
(craves satiety pepper)
(craves satiety pork-26)
(craves satiety tofu)
(craves sciatica turkey))
   (:goal (and (craves hangover pepper))))
