(define (problem mprime-x-17)
   (:domain mystery-prime-typed)
   (:objects pork lamb wurst shrimp muffin broccoli potato lettuce melon tofu orange cherry - food
             curiosity achievement satisfaction entertainment - pleasure
             jealousy sciatica hangover-12 depression-13 abrasion-14 anxiety-15 anger-16 angina-17 boils-18 grief-19 loneliness-20 dread-21 jealousy-22 sciatica-23 hangover-24 depression-25 abrasion-26 - pain
)
   (:init
(= (locale pork) 0)
(= (locale lamb) 3)
(= (locale wurst) 12)
(= (locale shrimp) 10)
(= (locale muffin) 0)
(= (locale broccoli) 8)
(= (locale potato) 10)
(= (locale lettuce) 1)
(= (locale melon) 0)
(= (locale tofu) 7)
(= (locale orange) 7)
(= (locale cherry) 0)
(= (harmony curiosity) 1)
(= (harmony achievement) 2)
(= (harmony satisfaction) 3)
(= (harmony entertainment) 1)
(eats pork orange)
(eats lamb cherry)
(eats lamb orange)
(eats lamb muffin)
(eats wurst broccoli)
(eats wurst muffin)
(eats wurst orange)
(eats shrimp orange)
(eats shrimp broccoli)
(eats muffin tofu)
(eats broccoli melon)
(eats broccoli cherry)
(eats broccoli lamb)
(eats potato melon)
(eats potato broccoli)
(eats potato muffin)
(eats lettuce tofu)
(eats melon orange)
(eats melon lamb)
(eats tofu cherry)
(eats tofu broccoli)
(eats tofu wurst)
(eats orange pork)
(eats cherry melon)
(eats cherry wurst)
(eats cherry pork)
(craves abrasion-14 pork)
(craves abrasion-14 potato)
(craves abrasion-26 shrimp)
(craves abrasion-26 wurst)
(craves achievement broccoli)
(craves achievement pork)
(craves achievement shrimp)
(craves anger-16 pork)
(craves anger-16 potato)
(craves angina-17 potato)
(craves anxiety-15 broccoli)
(craves anxiety-15 pork)
(craves boils-18 muffin)
(craves boils-18 potato)
(craves curiosity potato)
(craves curiosity shrimp)
(craves depression-13 shrimp)
(craves depression-25 broccoli)
(craves depression-25 potato)
(craves dread-21 broccoli)
(craves dread-21 tofu)
(craves entertainment cherry)
(craves entertainment lettuce)
(craves entertainment shrimp)
(craves entertainment wurst)
(craves grief-19 lamb)
(craves grief-19 potato)
(craves hangover-12 lettuce)
(craves hangover-12 tofu)
(craves hangover-24 lettuce)
(craves hangover-24 tofu)
(craves jealousy melon)
(craves jealousy-22 pork)
(craves loneliness-20 pork)
(craves loneliness-20 potato)
(craves satisfaction shrimp)
(craves satisfaction wurst)
(craves sciatica cherry)
(craves sciatica-23 potato)
(craves sciatica-23 wurst))
   (:goal (and (craves angina-17 shrimp) (craves sciatica-23 lettuce) (craves loneliness-20 shrimp))))
