(define (problem mprime-x-18)
   (:domain mystery-prime-typed)
   (:objects orange cherry chicken apple pepper bacon turkey papaya rice-22 pear-23 flounder-24 okra-25 pork-26 lamb-27 - food
             rest satiety curiosity - pleasure
             jealousy sciatica hangover-12 depression-13 abrasion-14 anxiety-15 anger-16 angina-17 boils-18 grief-19 loneliness-20 dread-21 jealousy-22 sciatica-23 hangover-24 depression-25 abrasion-26 - pain
)
   (:init
(= (locale orange) 12)
(= (locale cherry) 3)
(= (locale chicken) 2)
(= (locale apple) 7)
(= (locale pepper) 10)
(= (locale bacon) 2)
(= (locale turkey) 8)
(= (locale papaya) 3)
(= (locale rice-22) 2)
(= (locale pear-23) 5)
(= (locale flounder-24) 10)
(= (locale okra-25) 8)
(= (locale pork-26) 7)
(= (locale lamb-27) 10)
(= (harmony rest) 3)
(= (harmony satiety) 2)
(= (harmony curiosity) 1)
(eats orange pear-23)
(eats orange turkey)
(eats orange bacon)
(eats cherry cherry)
(eats chicken lamb-27)
(eats apple papaya)
(eats apple pear-23)
(eats pepper lamb-27)
(eats pepper pear-23)
(eats bacon rice-22)
(eats bacon flounder-24)
(eats bacon papaya)
(eats turkey pear-23)
(eats papaya turkey)
(eats rice-22 pork-26)
(eats rice-22 apple)
(eats pear-23 pear-23)
(eats pear-23 pork-26)
(eats flounder-24 bacon)
(eats flounder-24 lamb-27)
(eats flounder-24 pork-26)
(eats okra-25 chicken)
(eats pork-26 cherry)
(eats pork-26 turkey)
(eats lamb-27 apple)
(eats lamb-27 chicken)
(craves abrasion-14 cherry)
(craves abrasion-26 lamb-27)
(craves abrasion-26 pepper)
(craves anger-16 pepper)
(craves angina-17 orange)
(craves anxiety-15 cherry)
(craves anxiety-15 turkey)
(craves boils-18 cherry)
(craves curiosity cherry)
(craves depression-13 chicken)
(craves depression-13 rice-22)
(craves depression-25 pear-23)
(craves dread-21 bacon)
(craves grief-19 lamb-27)
(craves grief-19 rice-22)
(craves hangover-12 lamb-27)
(craves hangover-12 orange)
(craves hangover-24 flounder-24)
(craves hangover-24 pepper)
(craves jealousy cherry)
(craves jealousy rice-22)
(craves jealousy-22 okra-25)
(craves loneliness-20 lamb-27)
(craves rest orange)
(craves rest pork-26)
(craves rest rice-22)
(craves rest turkey)
(craves satiety cherry)
(craves sciatica orange)
(craves sciatica papaya)
(craves sciatica-23 lamb-27)
(craves sciatica-23 pepper))
   (:goal (and (craves angina-17 rice-22))))
