(define (problem mprime-x-20)
   (:domain mystery-prime-typed)
   (:objects flounder okra pork lamb wurst shrimp muffin broccoli potato lettuce melon tofu orange cherry chicken - food
             satiety curiosity achievement satisfaction entertainment - pleasure
             dread jealousy sciatica hangover-12 depression-13 abrasion-14 anxiety-15 anger-16 angina-17 boils-18 grief-19 loneliness-20 dread-21 jealousy-22 sciatica-23 hangover-24 depression-25 abrasion-26 anxiety-27 anger-28 angina-29 - pain
)
   (:init
(= (locale flounder) 2)
(= (locale okra) 10)
(= (locale pork) 9)
(= (locale lamb) 8)
(= (locale wurst) 3)
(= (locale shrimp) 3)
(= (locale muffin) 8)
(= (locale broccoli) 2)
(= (locale potato) 11)
(= (locale lettuce) 12)
(= (locale melon) 12)
(= (locale tofu) 2)
(= (locale orange) 7)
(= (locale cherry) 10)
(= (locale chicken) 2)
(= (harmony satiety) 2)
(= (harmony curiosity) 2)
(= (harmony achievement) 1)
(= (harmony satisfaction) 2)
(= (harmony entertainment) 1)
(eats flounder pork)
(eats flounder shrimp)
(eats flounder tofu)
(eats okra chicken)
(eats okra broccoli)
(eats okra lamb)
(eats pork shrimp)
(eats pork lettuce)
(eats pork flounder)
(eats lamb cherry)
(eats lamb broccoli)
(eats lamb wurst)
(eats wurst okra)
(eats wurst potato)
(eats wurst melon)
(eats shrimp okra)
(eats shrimp tofu)
(eats muffin lettuce)
(eats muffin shrimp)
(eats muffin pork)
(eats broccoli okra)
(eats broccoli shrimp)
(eats broccoli melon)
(eats potato potato)
(eats potato flounder)
(eats lettuce lamb)
(eats melon chicken)
(eats tofu broccoli)
(eats orange muffin)
(eats orange broccoli)
(eats orange okra)
(eats cherry shrimp)
(eats cherry okra)
(eats cherry potato)
(eats chicken broccoli)
(eats chicken lamb)
(craves abrasion-14 lamb)
(craves abrasion-26 cherry)
(craves achievement cherry)
(craves achievement melon)
(craves achievement muffin)
(craves anger-16 broccoli)
(craves anger-16 lettuce)
(craves anger-28 broccoli)
(craves angina-17 lamb)
(craves angina-17 pork)
(craves angina-29 lamb)
(craves angina-29 tofu)
(craves anxiety-15 tofu)
(craves anxiety-27 melon)
(craves boils-18 broccoli)
(craves boils-18 wurst)
(craves curiosity broccoli)
(craves curiosity cherry)
(craves curiosity okra)
(craves curiosity pork)
(craves depression-13 broccoli)
(craves depression-13 flounder)
(craves depression-25 melon)
(craves dread cherry)
(craves dread-21 potato)
(craves entertainment lamb)
(craves entertainment melon)
(craves entertainment okra)
(craves entertainment tofu)
(craves grief-19 pork)
(craves grief-19 potato)
(craves hangover-12 cherry)
(craves hangover-12 wurst)
(craves hangover-24 cherry)
(craves hangover-24 wurst)
(craves jealousy broccoli)
(craves jealousy wurst)
(craves jealousy-22 tofu)
(craves jealousy-22 wurst)
(craves loneliness-20 broccoli)
(craves satiety okra)
(craves satisfaction melon)
(craves satisfaction pork)
(craves sciatica chicken)
(craves sciatica pork)
(craves sciatica-23 chicken)
(craves sciatica-23 melon))
   (:goal (and (craves abrasion-14 tofu) (craves anger-16 cherry) (craves sciatica-23 muffin))))
