(define (problem mprime-x-13)
   (:domain mystery-prime-typed)
   (:objects okra pork lamb wurst shrimp muffin broccoli potato lettuce melon tofu orange cherry chicken - food
             rest satiety curiosity achievement satisfaction - pleasure
             jealousy sciatica hangover-12 depression-13 abrasion-14 anxiety-15 anger-16 angina-17 boils-18 grief-19 loneliness-20 dread-21 jealousy-22 sciatica-23 hangover-24 depression-25 abrasion-26 anxiety-27 anger-28 angina-29 boils-30 grief-31 - pain
)
   (:init
(= (locale okra) 11)
(= (locale pork) 8)
(= (locale lamb) 1)
(= (locale wurst) 8)
(= (locale shrimp) 8)
(= (locale muffin) 11)
(= (locale broccoli) 6)
(= (locale potato) 11)
(= (locale lettuce) 7)
(= (locale melon) 6)
(= (locale tofu) 2)
(= (locale orange) 10)
(= (locale cherry) 10)
(= (locale chicken) 3)
(= (harmony rest) 2)
(= (harmony satiety) 3)
(= (harmony curiosity) 1)
(= (harmony achievement) 1)
(= (harmony satisfaction) 3)
(eats okra potato)
(eats okra broccoli)
(eats okra wurst)
(eats pork shrimp)
(eats lamb okra)
(eats lamb cherry)
(eats lamb broccoli)
(eats wurst melon)
(eats shrimp melon)
(eats muffin cherry)
(eats muffin okra)
(eats broccoli lettuce)
(eats broccoli orange)
(eats potato cherry)
(eats lettuce cherry)
(eats lettuce wurst)
(eats melon potato)
(eats melon cherry)
(eats tofu lamb)
(eats tofu wurst)
(eats orange orange)
(eats orange wurst)
(eats cherry lettuce)
(eats cherry broccoli)
(eats cherry okra)
(eats chicken potato)
(eats chicken broccoli)
(craves abrasion-14 potato)
(craves abrasion-26 tofu)
(craves achievement broccoli)
(craves achievement lamb)
(craves achievement potato)
(craves anger-16 melon)
(craves anger-16 shrimp)
(craves anger-28 chicken)
(craves anger-28 tofu)
(craves angina-17 lettuce)
(craves angina-29 broccoli)
(craves angina-29 okra)
(craves anxiety-15 okra)
(craves anxiety-27 broccoli)
(craves anxiety-27 tofu)
(craves boils-18 broccoli)
(craves boils-18 melon)
(craves boils-30 broccoli)
(craves curiosity broccoli)
(craves curiosity muffin)
(craves depression-13 broccoli)
(craves depression-25 pork)
(craves dread-21 lettuce)
(craves dread-21 orange)
(craves grief-19 melon)
(craves grief-19 shrimp)
(craves grief-31 cherry)
(craves grief-31 lettuce)
(craves hangover-12 chicken)
(craves hangover-12 shrimp)
(craves hangover-24 orange)
(craves jealousy pork)
(craves jealousy potato)
(craves jealousy-22 cherry)
(craves loneliness-20 tofu)
(craves rest broccoli)
(craves rest lettuce)
(craves rest melon)
(craves rest wurst)
(craves satiety cherry)
(craves satisfaction cherry)
(craves satisfaction potato)
(craves sciatica melon)
(craves sciatica pork)
(craves sciatica-23 pork)
(craves sciatica-23 wurst))
   (:goal (and (craves grief-19 lettuce) (craves jealousy broccoli))))
